//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SDActivityKey.h"

__attribute__((visibility("hidden")))
@interface SDActivityDecryptionKey : SDActivityKey
{
}

- (_Bool)getResultWhileDecryptingBytesInPlace:(unsigned char [10])arg1 andCounter:(unsigned char [2])arg2 withTag:(unsigned char)arg3 version:(unsigned char)arg4;	// IMP=0x0000000100152234

@end

