//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SDXPCDaemon.h"

#import "IDSServiceDelegate-Protocol.h"

@class IDSService, NSArray, NSString;

__attribute__((visibility("hidden")))
@interface SDActivityController : SDXPCDaemon <IDSServiceDelegate>
{
    _Bool _shouldStart;	// 8 = 0x8
    IDSService *_activityService;	// 16 = 0x10
    NSArray *_allPeerBTIdentifiers;	// 24 = 0x18
    NSString *_appleID;	// 32 = 0x20
}

@property(copy, nonatomic) NSString *appleID; // @synthesize appleID=_appleID;
@property(retain, nonatomic) NSArray *allPeerBTIdentifiers; // @synthesize allPeerBTIdentifiers=_allPeerBTIdentifiers;
@property(nonatomic) _Bool shouldStart; // @synthesize shouldStart=_shouldStart;
@property(retain, nonatomic) IDSService *activityService; // @synthesize activityService=_activityService;
- (void).cxx_destruct;	// IMP=0x00000001000251b8
- (void)service:(id)arg1 nearbyDevicesChanged:(id)arg2;	// IMP=0x0000000100024ff8
- (void)service:(id)arg1 devicesChanged:(id)arg2;	// IMP=0x0000000100024e78
- (void)nearbyServiceDevicesChanged:(id)arg1;	// IMP=0x00000001000249a0
- (void)activityServiceDevicesChanged:(id)arg1;	// IMP=0x000000010002499c
- (id)idsDeviceFromBTIdentifier:(id)arg1;	// IMP=0x0000000100024654
- (void)stop;	// IMP=0x0000000100024650
- (_Bool)restart;	// IMP=0x0000000100024648
- (void)start;	// IMP=0x0000000100024644
- (id)init;	// IMP=0x00000001000245a0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

