//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SDAirDropHandlerGenericFiles.h"

__attribute__((visibility("hidden")))
@interface SDAirDropHandlerPlaygroundItems : SDAirDropHandlerGenericFiles
{
}

- (id)suitableContentsDescription;	// IMP=0x00000001000f01e0
- (long long)transferTypes;	// IMP=0x00000001000f01a8
- (_Bool)canHandleTransfer;	// IMP=0x00000001000f0188
- (id)initWithTransfer:(id)arg1;	// IMP=0x00000001000f0154

@end

