//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SDAirDropHandlerGenericLinks.h"

__attribute__((visibility("hidden")))
@interface SDAirDropHandlerWebLinks : SDAirDropHandlerGenericLinks
{
}

- (id)suitableContentsDescription;	// IMP=0x000000010014236c
- (long long)transferTypes;	// IMP=0x0000000100142334
- (_Bool)canHandleTransfer;	// IMP=0x0000000100142314
- (id)initWithTransfer:(id)arg1;	// IMP=0x00000001001422ac

@end

