//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SDAirDropHandler.h"

__attribute__((visibility("hidden")))
@interface SDAirDropHandlerProfiles : SDAirDropHandler
{
}

- (void)updatePossibleActions;	// IMP=0x000000010015d810
- (id)suitableContentsDescription;	// IMP=0x000000010015d664
- (long long)transferTypes;	// IMP=0x000000010015d62c
- (_Bool)canHandleTransfer;	// IMP=0x000000010015d60c
- (id)initWithTransfer:(id)arg1;	// IMP=0x000000010015d58c

@end

