//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@interface SDUnlockLockStateUpdated : PBCodable <NSCopying>
{
    unsigned int _version;	// 8 = 0x8
    _Bool _unlocked;	// 12 = 0xc
    struct {
        unsigned int version:1;
        unsigned int unlocked:1;
    } _has;	// 16 = 0x10
}

@property(nonatomic) _Bool unlocked; // @synthesize unlocked=_unlocked;
@property(nonatomic) unsigned int version; // @synthesize version=_version;
- (void)mergeFrom:(id)arg1;	// IMP=0x0000000100064d80
- (unsigned long long)hash;	// IMP=0x0000000100064d1c
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000100064c40
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100064ba8
- (void)copyTo:(id)arg1;	// IMP=0x0000000100064b34
- (void)writeTo:(id)arg1;	// IMP=0x0000000100064ab8
- (_Bool)readFrom:(id)arg1;	// IMP=0x0000000100064ab0
- (id)dictionaryRepresentation;	// IMP=0x00000001000646b4
- (id)description;	// IMP=0x0000000100064600
@property(nonatomic) _Bool hasUnlocked;
@property(nonatomic) _Bool hasVersion;

@end

