//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SDBonjourBrowserDelegate-Protocol.h"

@class NSArray, NSString, SDBonjourBrowser;
@protocol SDWindowsBrowserDelegate;

__attribute__((visibility("hidden")))
@interface SDWindowsBrowser : NSObject <SDBonjourBrowserDelegate>
{
    SDBonjourBrowser *_browser;	// 8 = 0x8
    NSString *_workgroup;	// 16 = 0x10
    id <SDWindowsBrowserDelegate> _delegate;	// 24 = 0x18
}

@property __weak id <SDWindowsBrowserDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, copy) NSString *workgroup; // @synthesize workgroup=_workgroup;
- (void).cxx_destruct;	// IMP=0x00000001000ee6a4
- (void)stop;	// IMP=0x00000001000ee600
- (void)start;	// IMP=0x00000001000ee4e0
- (void)bonjourNodesDidChange:(id)arg1;	// IMP=0x00000001000ee49c
@property(readonly, copy) NSArray *nodes;
- (void)dealloc;	// IMP=0x00000001000ee438
- (id)initWithWorkgroup:(id)arg1;	// IMP=0x00000001000ee3a4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

