//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewFlowLayout.h"

@interface TVNPRoutingDestinationsCollectionViewLayout : UICollectionViewFlowLayout
{
    _Bool _enabled;	// 8 = 0x8
}

+ (Class)invalidationContextClass;	// IMP=0x0000000100014784
+ (Class)layoutAttributesClass;	// IMP=0x0000000100014770
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;	// IMP=0x0000000100014aa0
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;	// IMP=0x000000010001495c
- (struct CGPoint)targetContentOffsetForIndexPath:(id)arg1;	// IMP=0x0000000100014838
- (void)invalidateLayoutWithContext:(id)arg1;	// IMP=0x0000000100014798

@end

