//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "TVNPRoutingDestinationsCollectionViewControllerDelegate.h"
#import "TVNPRoutingRoutesCollectionViewControllerDelegate.h"

@class MPRouteLabel, NSObject<TVNPRoutingController>, NSString, PBSAssertion, TVNPRoutingDestinationsCollectionViewController, TVNPRoutingRoutesCollectionViewController, UILabel;

@interface TVNPRoutingMainViewController : UIViewController <TVNPRoutingDestinationsCollectionViewControllerDelegate, TVNPRoutingRoutesCollectionViewControllerDelegate>
{
    _Bool _editingVolume;	// 8 = 0x8
    id <TVNPRoutingMainViewControllerDelegate> _delegate;	// 16 = 0x10
    PBSAssertion *_playPauseAssertion;	// 24 = 0x18
    MPRouteLabel *_titleView;	// 32 = 0x20
    UILabel *_hintView;	// 40 = 0x28
    TVNPRoutingDestinationsCollectionViewController *_destinationsCollectionViewController;	// 48 = 0x30
    TVNPRoutingRoutesCollectionViewController *_routesCollectionViewController;	// 56 = 0x38
    NSObject<TVNPRoutingController> *_routingController;	// 64 = 0x40
}

+ (id)_routesLayout;	// IMP=0x0000000100014144
+ (id)_destinationLayout;	// IMP=0x0000000100014030
@property(readonly, nonatomic) NSObject<TVNPRoutingController> *routingController; // @synthesize routingController=_routingController;
@property(readonly, nonatomic) TVNPRoutingRoutesCollectionViewController *routesCollectionViewController; // @synthesize routesCollectionViewController=_routesCollectionViewController;
@property(readonly, nonatomic) TVNPRoutingDestinationsCollectionViewController *destinationsCollectionViewController; // @synthesize destinationsCollectionViewController=_destinationsCollectionViewController;
@property(readonly, nonatomic) UILabel *hintView; // @synthesize hintView=_hintView;
@property(readonly, nonatomic) MPRouteLabel *titleView; // @synthesize titleView=_titleView;
@property(readonly, nonatomic) PBSAssertion *playPauseAssertion; // @synthesize playPauseAssertion=_playPauseAssertion;
@property(readonly, nonatomic) _Bool editingVolume; // @synthesize editingVolume=_editingVolume;
@property(nonatomic) __weak id <TVNPRoutingMainViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x000000010001434c
- (void)_updateHintText;	// IMP=0x00000001000138f4
- (void)_updateTitleView;	// IMP=0x000000010001384c
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x0000000100013760
- (void)didPressPlayPause:(id)arg1;	// IMP=0x00000001000136ec
- (void)didPressMenu:(id)arg1;	// IMP=0x00000001000136a0
- (void)routingViewControllerWillEndEditingVolume:(id)arg1;	// IMP=0x0000000100013650
- (void)routingViewControllerWillBeginEditingVolume:(id)arg1;	// IMP=0x00000001000135fc
- (void)viewControllerDidRequestDismissal:(id)arg1;	// IMP=0x00000001000135f0
- (void)requestDismissal;	// IMP=0x00000001000135a8
- (id)preferredFocusEnvironments;	// IMP=0x0000000100013590
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x0000000100013538
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x00000001000134e0
- (void)viewDidLoad;	// IMP=0x00000001000127cc
- (void)dealloc;	// IMP=0x0000000100012678
- (id)initWithRoutingController:(id)arg1 options:(id)arg2;	// IMP=0x00000001000120a0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

