//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewLayoutAttributes.h"

@interface TVNPRoutingDestinationsCollectionViewLayoutAttributes : UICollectionViewLayoutAttributes
{
    _Bool _enabled;	// 8 = 0x8
}

@property(nonatomic, getter=isEnabled) _Bool enabled; // @synthesize enabled=_enabled;
- (unsigned long long)hash;	// IMP=0x0000000100014c58
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000100014bbc
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100014b50
- (id)init;	// IMP=0x0000000100014b08

@end

