//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "RetrievingDialogDelegate.h"

@class CKContainer, CKShareMetadata, CKShareParticipant, NSArray, NSDictionary, NSError, NSPersonNameComponents, NSString, NSURL, NSXPCConnection, RetrievingDialog;

@interface ShareAcceptor : NSObject <RetrievingDialogDelegate>
{
    _Bool _hasValidConnection;	// 8 = 0x8
    _Bool _accepting;	// 9 = 0x9
    _Bool _cancelled;	// 10 = 0xa
    unsigned long long _backgroundTaskID;	// 16 = 0x10
    NSURL *_url;	// 24 = 0x18
    RetrievingDialog *_retrievingDialog;	// 32 = 0x20
    CKShareMetadata *_shareMetadata;	// 40 = 0x28
    NSString *_shareName;	// 48 = 0x30
    NSArray *_whitelistedAppBundleIDs;	// 56 = 0x38
    NSArray *_whitelistedDaemonBundleIDs;	// 64 = 0x40
    NSDictionary *_localBundleIDsToDisplayNames;	// 72 = 0x48
    NSString *_chosenAppBundleID;	// 80 = 0x50
    CKShareParticipant *_singleOONMatch;	// 88 = 0x58
    NSPersonNameComponents *_currentUserNameComponents;	// 96 = 0x60
    NSString *_currentUserFormattedUsername;	// 104 = 0x68
    CKContainer *_clouddContainer;	// 112 = 0x70
    CKContainer *_metadataIndicatedContainer;	// 120 = 0x78
    NSXPCConnection *_xpcConnection;	// 128 = 0x80
    long long _state;	// 136 = 0x88
    NSError *_fallbackFlowCause;	// 144 = 0x90
    NSString *_webFlowReason;	// 152 = 0x98
}

@property(retain, nonatomic) NSString *webFlowReason; // @synthesize webFlowReason=_webFlowReason;
@property(retain, nonatomic) NSError *fallbackFlowCause; // @synthesize fallbackFlowCause=_fallbackFlowCause;
@property(nonatomic, setter=setState:) long long state; // @synthesize state=_state;
@property _Bool cancelled; // @synthesize cancelled=_cancelled;
@property(nonatomic) _Bool accepting; // @synthesize accepting=_accepting;
@property(nonatomic) _Bool hasValidConnection; // @synthesize hasValidConnection=_hasValidConnection;
@property(retain, nonatomic) NSXPCConnection *xpcConnection; // @synthesize xpcConnection=_xpcConnection;
@property(retain, nonatomic) CKContainer *metadataIndicatedContainer; // @synthesize metadataIndicatedContainer=_metadataIndicatedContainer;
@property(retain, nonatomic) CKContainer *clouddContainer; // @synthesize clouddContainer=_clouddContainer;
@property(copy, nonatomic) NSString *currentUserFormattedUsername; // @synthesize currentUserFormattedUsername=_currentUserFormattedUsername;
@property(copy, nonatomic) NSPersonNameComponents *currentUserNameComponents; // @synthesize currentUserNameComponents=_currentUserNameComponents;
@property(copy, nonatomic) CKShareParticipant *singleOONMatch; // @synthesize singleOONMatch=_singleOONMatch;
@property(copy, nonatomic) NSString *chosenAppBundleID; // @synthesize chosenAppBundleID=_chosenAppBundleID;
@property(copy, nonatomic) NSDictionary *localBundleIDsToDisplayNames; // @synthesize localBundleIDsToDisplayNames=_localBundleIDsToDisplayNames;
@property(copy, nonatomic) NSArray *whitelistedDaemonBundleIDs; // @synthesize whitelistedDaemonBundleIDs=_whitelistedDaemonBundleIDs;
@property(copy, nonatomic) NSArray *whitelistedAppBundleIDs; // @synthesize whitelistedAppBundleIDs=_whitelistedAppBundleIDs;
@property(copy, nonatomic) NSString *shareName; // @synthesize shareName=_shareName;
@property(copy, nonatomic) CKShareMetadata *shareMetadata; // @synthesize shareMetadata=_shareMetadata;
@property(readonly, retain, nonatomic) RetrievingDialog *retrievingDialog; // @synthesize retrievingDialog=_retrievingDialog;
@property(copy, nonatomic) NSURL *url; // @synthesize url=_url;
@property(nonatomic) unsigned long long backgroundTaskID; // @synthesize backgroundTaskID=_backgroundTaskID;
- (void).cxx_destruct;	// IMP=0x0000000100010900
- (void)acceptShareWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100010104
- (_Bool)makeStateTransition:(id *)arg1;	// IMP=0x000000010000f98c
- (_Bool)_launchApp:(id *)arg1;	// IMP=0x000000010000f698
- (long long)_handlePotentialOONMatches;	// IMP=0x000000010000f600
- (_Bool)_isDataclassEnabled:(id)arg1 forContainerIdentifierWithPrefix:(id)arg2 error:(id *)arg3;	// IMP=0x000000010000f36c
- (_Bool)_checkDataclass:(id)arg1 withContainer:(id)arg2 error:(id *)arg3;	// IMP=0x000000010000f034
- (_Bool)_verifySelectedApp:(id *)arg1;	// IMP=0x000000010000ee14
- (_Bool)_promptAppSelection:(id *)arg1;	// IMP=0x000000010000eaec
- (long long)_lookUpLocalBundleIDs:(id *)arg1 success:(_Bool *)arg2;	// IMP=0x000000010000e4bc
- (_Bool)_handlePotentialAppleInternalDaemon:(id *)arg1;	// IMP=0x000000010000d97c
- (_Bool)_handleAppleInternalDaemon:(id)arg1 response:(id)arg2 error:(id *)arg3;	// IMP=0x000000010000d848
- (_Bool)_lookUpWhitelistedBundleIDs:(id *)arg1;	// IMP=0x000000010000cf34
- (_Bool)_urlHasALongToken:(id)arg1;	// IMP=0x000000010000cc70
- (_Bool)_urlIsALegacyiWorkShareURL:(id)arg1;	// IMP=0x000000010000cc04
- (_Bool)_fetchMetadata:(id *)arg1;	// IMP=0x000000010000c598
- (_Bool)_notifyBladeRunner:(id *)arg1;	// IMP=0x000000010000c44c
- (_Bool)_validateShareURL:(id *)arg1;	// IMP=0x000000010000c3b0
- (id)_iosShowAppSelectionDialogWithTitlesDictionary:(id)arg1;	// IMP=0x000000010000c0b8
- (id)chooseFromMultipleBundleIDs;	// IMP=0x000000010000c028
- (id)_deduplicateBundleToNamesMapping:(id)arg1;	// IMP=0x000000010000be34
- (void)_initiateVettingForParticipantID:(id)arg1 address:(id)arg2 andThen:(CDUnknownBlockType)arg3;	// IMP=0x000000010000badc
- (id)_iosShowVettingAlert;	// IMP=0x000000010000ae34
- (_Bool)_requestSelectionFromMultipleOONMatches:(id *)arg1;	// IMP=0x000000010000ad80
- (_Bool)_initiateVettingOfSingleOONMatch:(id *)arg1;	// IMP=0x000000010000a5e4
- (long long)initiateVetting;	// IMP=0x000000010000a568
- (id)_showVettingAlert;	// IMP=0x000000010000a55c
- (id)_trySelectingOONParticipant;	// IMP=0x0000000100009a94
- (void)_extractEmailAddressesFromProperties:(id)arg1 into:(id)arg2;	// IMP=0x00000001000096c8
- (_Bool)_getShareName;	// IMP=0x0000000100009468
- (id)promptForSingleBundleID;	// IMP=0x0000000100008c18
- (id)_fetchCurrentUserNameComponents;	// IMP=0x00000001000089ac
- (_Bool)shareNeedsAcceptance;	// IMP=0x0000000100008900
- (id)fetchMetadata;	// IMP=0x0000000100008358
- (long long)_checkICloudDriveEnabled:(id *)arg1 appCandidatesPresent:(_Bool)arg2;	// IMP=0x0000000100007bcc
- (_Bool)_promptToOpenAppStoreLink:(id *)arg1 alertOptions:(id)arg2 appURL:(id)arg3;	// IMP=0x00000001000078b4
- (id)_findStoreDataForBundleIDs:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100006f6c
- (_Bool)_fallbackFlowDownloadAppUpdate:(id *)arg1;	// IMP=0x0000000100006b34
- (_Bool)_fallbackFlowDownloadApp:(id *)arg1;	// IMP=0x0000000100006640
- (id)_iosHandleMultipleAppStoreCandidates:(id)arg1 error:(id *)arg2;	// IMP=0x00000001000064bc
- (_Bool)_fallbackFlowWebRedirect:(id *)arg1;	// IMP=0x0000000100005f5c
- (_Bool)_fallbackFlowWarnShareUnavailable:(id *)arg1;	// IMP=0x0000000100005d9c
- (_Bool)_fallbackFlowWarnServiceUnavailable:(id *)arg1;	// IMP=0x0000000100005c9c
- (_Bool)_fallbackFlowWarnNetworkUnavailable:(id *)arg1;	// IMP=0x0000000100005b9c
- (long long)_fallbackFlowICloudAccountSettings:(id *)arg1 success:(_Bool *)arg2;	// IMP=0x00000001000058c4
- (_Bool)_shouldSendURLToPhotos:(id)arg1;	// IMP=0x0000000100005840
- (_Bool)_shouldSendURLToBladeRunner:(id)arg1;	// IMP=0x00000001000056f8
- (_Bool)_urlIsAniWorkShareURL:(id)arg1;	// IMP=0x00000001000055bc
- (void)retrievingDialogCancelled;	// IMP=0x00000001000055b0
- (_Bool)retrievingDialogShouldDisplay;	// IMP=0x0000000100005540
- (_Bool)shouldShowRetrievingDialogForState:(long long)arg1;	// IMP=0x000000010000551c
- (_Bool)_shouldShowICloudLoginPrompt:(id)arg1;	// IMP=0x0000000100005280
- (void)_cancel;	// IMP=0x0000000100005270
- (id)initWithShareMetadata:(id)arg1 shareURL:(id)arg2;	// IMP=0x00000001000051fc
- (id)initWithCloudKitURL:(id)arg1;	// IMP=0x0000000100005100

@end

