//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDateFormatter, NSMutableArray, NSMutableDictionary, NSMutableString, NSString, NSURL, W5DiagnosticsManager, W5LogItemRequestInternal, W5StatusManager;
@protocol OS_dispatch_queue;

@interface W5LogManager : NSObject
{
    W5StatusManager *_status;	// 8 = 0x8
    W5DiagnosticsManager *_diagnostics;	// 16 = 0x10
    NSString *_model;	// 24 = 0x18
    NSURL *_homeDirectory;	// 32 = 0x20
    NSURL *_outputDirectory;	// 40 = 0x28
    NSObject<OS_dispatch_queue> *_queue;	// 48 = 0x30
    NSObject<OS_dispatch_queue> *_taskQueue;	// 56 = 0x38
    NSMutableArray *_pendingRequests;	// 64 = 0x40
    W5LogItemRequestInternal *_activeRequest;	// 72 = 0x48
    NSDateFormatter *_dateFormatter;	// 80 = 0x50
    NSMutableDictionary *_taskUUIDMap;	// 88 = 0x58
    NSObject<OS_dispatch_queue> *_debugLogQueue;	// 96 = 0x60
    NSMutableString *_debugLog;	// 104 = 0x68
    struct __IOReportSubscriptionCF *_ioReportSubscription;	// 112 = 0x70
    unsigned long long _ioReportBaseMachAbsoluteTime;	// 120 = 0x78
    unsigned long long _ioReportDeltaMachAbsoluteTime;	// 128 = 0x80
    struct __CFDictionary *_ioReportChannels;	// 136 = 0x88
    struct __CFDictionary *_ioReportBase;	// 144 = 0x90
    struct __CFDictionary *_ioReportDelta;	// 152 = 0x98
    CDUnknownBlockType _collectedItemCallback;	// 160 = 0xa0
    CDUnknownBlockType _pingCallback;	// 168 = 0xa8
}

+ (id)__temporaryDirectory;	// IMP=0x000000010006e298
+ (void)__parsePingOutput:(id)arg1 result:(id)arg2;	// IMP=0x000000010006bdc0
+ (id)__logAWDLInfoWithAWDLInterface:(id)arg1 awdlStatus:(id)arg2;	// IMP=0x000000010006a830
+ (id)__logBluetoothStatus:(id)arg1;	// IMP=0x0000000100068c70
+ (id)__logWiFiStatus:(id)arg1;	// IMP=0x0000000100067e10
+ (id)__logNetworkStatus:(id)arg1;	// IMP=0x000000010006793c
+ (id)__logTxPower:(struct apple80211_per_chain_power_data_get)arg1;	// IMP=0x0000000100067868
+ (id)__logBTCProfile:(struct apple80211_btc_profile_osx)arg1;	// IMP=0x00000001000674d8
+ (id)__logScanResults:(id)arg1;	// IMP=0x0000000100066aec
+ (id)__descriptionForNetwork:(id)arg1;	// IMP=0x00000001000667c4
+ (id)__model;	// IMP=0x00000001000527f8
@property(copy, nonatomic) CDUnknownBlockType pingCallback; // @synthesize pingCallback=_pingCallback;
@property(copy, nonatomic) CDUnknownBlockType collectedItemCallback; // @synthesize collectedItemCallback=_collectedItemCallback;
- (_Bool)__dittoSource:(id)arg1 destination:(id)arg2 timeout:(double)arg3 error:(id *)arg4;	// IMP=0x000000010006f600
- (_Bool)__tarballWithSource:(id)arg1 destination:(id)arg2 error:(id *)arg3;	// IMP=0x000000010006f57c
- (_Bool)__tarballUsingBOMWithSource:(id)arg1 destination:(id)arg2 error:(id *)arg3;	// IMP=0x000000010006f338
- (_Bool)__dittoUsingBOMWithSource:(id)arg1 destination:(id)arg2 error:(id *)arg3;	// IMP=0x000000010006f118
- (_Bool)__tarballUsingToolWithSource:(id)arg1 destination:(id)arg2 error:(id *)arg3;	// IMP=0x000000010006ed48
- (void)__mobilewifitoolWithOutput:(id)arg1 arguments:(id)arg2;	// IMP=0x000000010006e874
- (void)__securityWithOutput:(id)arg1 arguments:(id)arg2;	// IMP=0x000000010006e3a0
- (_Bool)__dittoUsingToolWithSource:(id)arg1 destination:(id)arg2 timeout:(double)arg3 error:(id *)arg4;	// IMP=0x000000010006df00
- (void)__dumpCoreCaptureLogsWithReason:(id)arg1 delay:(long long)arg2;	// IMP=0x000000010006de04
- (void)__arpWithOutput:(id)arg1 arguments:(id)arg2;	// IMP=0x000000010006d880
- (void)__ndpWithOutput:(id)arg1 arguments:(id)arg2;	// IMP=0x000000010006d2fc
- (void)__ifconfigWithOutput:(id)arg1 arguments:(id)arg2;	// IMP=0x000000010006cd78
- (void)__netstatWithOutput:(id)arg1 arguments:(id)arg2;	// IMP=0x000000010006c7f4
- (void)__pingWithOutput:(id)arg1 arguments:(id)arg2;	// IMP=0x000000010006c0f8
- (id)__pingUsingIMFoundationWithAddress:(id)arg1 timeout:(long long)arg2;	// IMP=0x000000010006b918
- (id)__pingUsingCFNetworkWithAddress:(id)arg1 count:(long long)arg2 timeout:(long long)arg3 trafficClass:(id)arg4 networkServiceType:(id)arg5;	// IMP=0x000000010006b27c
- (id)__pingWithAddress:(id)arg1 count:(long long)arg2 timeout:(double)arg3 wait:(double)arg4 interval:(double)arg5 trafficClass:(id)arg6 interfaceName:(id)arg7 dataLength:(long long)arg8;	// IMP=0x000000010006ad14
- (id)__logDiagnosticsTestResults:(id)arg1;	// IMP=0x0000000100067290
- (id)__logDiagnosticsPingResults:(id)arg1;	// IMP=0x0000000100066e20
- (id)__runDiagnosticsTests:(id)arg1 timeout:(long long)arg2 error:(id *)arg3;	// IMP=0x00000001000664b4
- (id)__collectLogItem:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100065a34
- (id)__collectWiFiStatsPost:(id)arg1;	// IMP=0x0000000100065664
- (id)__collectWiFiStatsPre:(id)arg1;	// IMP=0x0000000100065584
- (void)__setupWiFiStats;	// IMP=0x0000000100065044
- (void)__teardownWiFiStats;	// IMP=0x0000000100064fb0
- (void)__startWiFiStats;	// IMP=0x0000000100064f38
- (void)__endWiFiStats;	// IMP=0x0000000100064e84
- (id)__collect_mobilewifitool:(id)arg1;	// IMP=0x0000000100064bfc
- (id)__collect_security:(id)arg1;	// IMP=0x0000000100064924
- (id)__collectMultiple:(id)arg1;	// IMP=0x0000000100064298
- (id)__collectAdditionalLog:(id)arg1 url:(id)arg2;	// IMP=0x0000000100064074
- (id)__collectEventHistory:(id)arg1;	// IMP=0x00000001000630d4
- (id)__collectLogArchive24WithOutputDirectory:(id)arg1;	// IMP=0x0000000100062c4c
- (id)__collectLogArchive2MBWithOutputDirectory:(id)arg1;	// IMP=0x0000000100062854
- (id)__collectCrashesAndSpins24:(id)arg1;	// IMP=0x0000000100062304
- (id)__collectBluetoothLogs:(id)arg1;	// IMP=0x0000000100061fb4
- (id)__collectSharingLogs:(id)arg1;	// IMP=0x0000000100061d6c
- (id)__collectWirelessProxLogs:(id)arg1;	// IMP=0x0000000100061ba4
- (id)__collectAirPlayLogs:(id)arg1;	// IMP=0x0000000100061890
- (id)__collectSystemLogs24:(id)arg1;	// IMP=0x000000010006172c
- (id)__collectSystemLogs:(id)arg1;	// IMP=0x00000001000615c8
- (id)__collectSyslogWithOutputDirectory:(id)arg1;	// IMP=0x0000000100061264
- (id)__collectIPConfigurationLogs:(id)arg1;	// IMP=0x0000000100060f50
- (id)__collectEAP8021XLogs:(id)arg1;	// IMP=0x0000000100060c3c
- (id)__collectWiFiLogsDump:(id)arg1;	// IMP=0x000000010006093c
- (id)__collectWiFiLogs24:(id)arg1;	// IMP=0x000000010006063c
- (id)__collectWiFiLogs:(id)arg1;	// IMP=0x000000010006033c
- (void)__dumpWiFiLogs;	// IMP=0x00000001000602e4
- (id)__possibleTempWiFiLogPaths;	// IMP=0x0000000100060294
- (id)__collectWiFiPreferences:(id)arg1;	// IMP=0x000000010005ff4c
- (id)__collectCoreCapture:(id)arg1;	// IMP=0x000000010005fb74
- (id)__collectCoreCaptureDump:(id)arg1;	// IMP=0x000000010005f728
- (id)__collectCoreCapture24:(id)arg1;	// IMP=0x000000010005f2e4
- (id)__collectCoreCapture_POST:(id)arg1;	// IMP=0x000000010005ed30
- (id)__collectCoreCapture_PRE:(id)arg1;	// IMP=0x000000010005e864
- (void)__filterCoreCaptureContent:(id)arg1;	// IMP=0x000000010005e58c
- (id)__possibleCoreCapturePaths;	// IMP=0x000000010005e504
- (id)__mostRecentInDirectories:(id)arg1 matchingPrefix:(id)arg2 matchingSuffix:(id)arg3 excludingPrefix:(id)arg4 excludingSuffix:(id)arg5 maxAge:(double)arg6;	// IMP=0x000000010005e09c
- (id)__mostRecentInDirectories:(id)arg1 include:(id)arg2 exclude:(id)arg3 maxAge:(double)arg4;	// IMP=0x000000010005dc3c
- (id)__collectFileAtURL:(id)arg1 outputDirectory:(id)arg2 maxAge:(double)arg3 maxSize:(long long)arg4 compress:(_Bool)arg5 remainingSize:(unsigned long long *)arg6;	// IMP=0x000000010005d950
- (id)__collectFilesInDirectories:(id)arg1 include:(id)arg2 exclude:(id)arg3 maxAge:(double)arg4 maxCount:(long long)arg5 maxSize:(long long)arg6 outputDirectory:(id)arg7 compress:(_Bool)arg8 remainingSize:(unsigned long long *)arg9 contentFilter:(CDUnknownBlockType)arg10;	// IMP=0x000000010005d3f4
- (unsigned long long)__calculateSizeAtPath:(id)arg1;	// IMP=0x000000010005d170
- (id)__collect_pmset:(id)arg1;	// IMP=0x000000010005ccdc
- (id)__collectTCPDump_POST:(id)arg1;	// IMP=0x000000010005cbc8
- (id)__collectTCPDump_PRE:(id)arg1;	// IMP=0x000000010005c7e8
- (id)__collect_ndp:(id)arg1;	// IMP=0x000000010005c4c8
- (id)__collect_sysdiagnose:(id)arg1;	// IMP=0x000000010005c084
- (id)__collect_hosts:(id)arg1;	// IMP=0x000000010005bedc
- (id)__collect_darwinup:(id)arg1;	// IMP=0x000000010005ba48
- (id)__collect_spindump:(id)arg1;	// IMP=0x000000010005b4c4
- (id)__collect_wl_curpower:(id)arg1;	// IMP=0x000000010005b030
- (id)__collect_configd:(id)arg1;	// IMP=0x000000010005ab08
- (id)__collectSystemConfiguration:(id)arg1;	// IMP=0x000000010005a960
- (id)__collect_netstat:(id)arg1;	// IMP=0x000000010005a5a8
- (id)__collect_top:(id)arg1;	// IMP=0x000000010005a114
- (id)__collect_ioreg:(id)arg1;	// IMP=0x0000000100059b8c
- (id)__collect_kextstat:(id)arg1;	// IMP=0x00000001000596f8
- (id)__collect_traceroute:(id)arg1;	// IMP=0x0000000100059218
- (id)__collect_ipconfig:(id)arg1;	// IMP=0x0000000100058d50
- (id)__collect_ifconfig:(id)arg1;	// IMP=0x0000000100058ae0
- (id)__collect_CFNetworkPing:(id)arg1;	// IMP=0x0000000100057d0c
- (id)__collect_ping:(id)arg1;	// IMP=0x0000000100056c98
- (id)__collect_IMFoundationPing:(id)arg1;	// IMP=0x00000001000564dc
- (id)__collect_arp:(id)arg1;	// IMP=0x00000001000562a0
- (id)__collect_swvers:(id)arg1;	// IMP=0x0000000100055e0c
- (id)__collectBluetoothStatus:(id)arg1;	// IMP=0x0000000100055b28
- (id)__collectWiFiStatus:(id)arg1;	// IMP=0x0000000100055844
- (id)__collectNetworkStatus:(id)arg1;	// IMP=0x0000000100055560
- (id)__collectAWDLStatus:(id)arg1;	// IMP=0x0000000100055258
- (id)__collectBonjourRecords:(id)arg1;	// IMP=0x0000000100054d70
- (id)__resolveBonjourInstance:(id)arg1 serviceType:(id)arg2 duration:(unsigned long long)arg3;	// IMP=0x0000000100054b6c
- (id)__browseBonjourInstancesWithServiceType:(id)arg1 duration:(unsigned long long)arg2;	// IMP=0x00000001000547f8
- (id)__collectLeakyAPStats:(id)arg1;	// IMP=0x0000000100054578
- (id)__collectPerSSIDDiagnosticsHistory:(id)arg1;	// IMP=0x0000000100054144
- (id)__collectDiagnostics:(id)arg1;	// IMP=0x0000000100053d2c
- (id)__collectWiFiScanResults:(id)arg1;	// IMP=0x0000000100053ab0
- (void)__runRequest:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00000001000530e8
- (id)__expandLogItems:(id)arg1;	// IMP=0x0000000100052e70
- (id)__basicWiFiLogsWithFilteredContent:(_Bool)arg1;	// IMP=0x00000001000528fc
- (id)__logItemsForSysdiagnoseWithFilteredContent:(_Bool)arg1;	// IMP=0x0000000100051ea0
- (id)__fastEnvironmentDiagnosticsLogItemWithTimeout:(double)arg1;	// IMP=0x0000000100051bb8
- (id)__fastDiagnosticsLogItemWithTimeout:(double)arg1;	// IMP=0x0000000100051664
- (id)__concurrentConnectivityDiagnosticsTest;	// IMP=0x0000000100050954
- (id)__logItemsForTapToRadar;	// IMP=0x0000000100050948
- (id)__logItemsForFeedbackAssistant;	// IMP=0x000000010005093c
- (id)__logItemsForWiFiDiagnosticsExtension;	// IMP=0x0000000100050274
- (id)__logItemsForWiFiDiagnosticsApp;	// IMP=0x00000001000501fc
- (void)__nextRequest;	// IMP=0x000000010004fb78
- (id)__pendingRequestWithUUID:(id)arg1;	// IMP=0x000000010004fa2c
- (void)teardownAndNotify:(CDUnknownBlockType)arg1;	// IMP=0x000000010004f838
- (void)cancelRequestWithUUID:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010004f5f0
- (void)addRequest:(id)arg1;	// IMP=0x000000010004f53c
- (void)dealloc;	// IMP=0x000000010004f148
- (id)initWithStatusManager:(id)arg1 diagnosticsManager:(id)arg2;	// IMP=0x000000010004ef00

@end

