//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;
@protocol OS_dispatch_queue;

@interface W5NetworkServiceConfiguration : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    struct __SCDynamicStore *_storeRef;	// 16 = 0x10
    struct __SCPreferences *_prefsRef;	// 24 = 0x18
    _Bool _isMonitoringEvents;	// 32 = 0x20
    CDUnknownBlockType _updatedNetworkServiceCallback;	// 40 = 0x28
    NSString *_interfaceName;	// 48 = 0x30
    NSString *_serviceID;	// 56 = 0x38
}

@property(readonly, nonatomic) NSString *serviceID; // @synthesize serviceID=_serviceID;
@property(readonly, nonatomic) NSString *interfaceName; // @synthesize interfaceName=_interfaceName;
@property(copy, nonatomic) CDUnknownBlockType updatedNetworkServiceCallback; // @synthesize updatedNetworkServiceCallback=_updatedNetworkServiceCallback;
- (id)dhcpLeaseExpirationTimestamp;	// IMP=0x0000000100078944
- (id)dhcpLeaseStartTimestamp;	// IMP=0x000000010007880c
- (id)__dhcpInfo;	// IMP=0x000000010007879c
- (_Bool)isUsingCustomProxySetting;	// IMP=0x00000001000785e8
- (_Bool)isUsingCustomDNSSettings;	// IMP=0x0000000100078504
- (id)dnsServerAddresses;	// IMP=0x0000000100078360
- (id)dnsDomainName;	// IMP=0x00000001000781bc
- (long long)ipv4ConfigMethod;	// IMP=0x0000000100077f88
- (long long)ipv6ConfigMethod;	// IMP=0x0000000100077dac
- (id)ipv6Addresses;	// IMP=0x0000000100077c08
- (id)ipv6Router;	// IMP=0x0000000100077a64
- (id)ipv4Addresses;	// IMP=0x00000001000778c0
- (id)ipv4Router;	// IMP=0x0000000100077700
- (void)refreshNetworkServiceID;	// IMP=0x00000001000775f8
- (id)__proxiesSetupConfig;	// IMP=0x0000000100077538
- (id)__dnsSetupConfig;	// IMP=0x0000000100077478
- (id)__dnsStateConfig;	// IMP=0x00000001000773b8
- (id)__ipv6SetupConfig;	// IMP=0x00000001000772f8
- (id)__ipv4SetupConfig;	// IMP=0x0000000100077238
- (id)__ipv6StateConfig;	// IMP=0x0000000100077178
- (id)__ipv4StateConfig;	// IMP=0x00000001000770b8
- (void)stopEventMonitoring;	// IMP=0x0000000100076ff8
- (void)__stopEventMonitoring;	// IMP=0x0000000100076fb4
- (void)startEventMonitoring;	// IMP=0x0000000100076ef0
- (void)__startEventMonitoring;	// IMP=0x0000000100076eb0
- (void)__refreshNotificationKeys;	// IMP=0x0000000100076c40
- (void)dealloc;	// IMP=0x0000000100076b80
- (id)init;	// IMP=0x0000000100076a30
- (id)initWithInterfaceName:(id)arg1;	// IMP=0x0000000100076744
- (id)__wifiServiceID;	// IMP=0x0000000100076098

@end

