//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSString, NSUUID, W5DebugConfiguration, W5Peer, W5PerfConfiguration, W5WiFiChannel, W5XPCConnection;

@protocol W5XPCConnectionDelegate <NSObject>
- (void)xpcConnection:(W5XPCConnection *)arg1 cancelWiFiSnifferWithUUID:(NSUUID *)arg2 peerID:(NSString *)arg3 reply:(void (^)(NSError *))arg4;
- (void)xpcConnection:(W5XPCConnection *)arg1 cancelPerformanceTestWithUUID:(NSUUID *)arg2 peerID:(NSString *)arg3 reply:(void (^)(NSError *))arg4;
- (void)xpcConnection:(W5XPCConnection *)arg1 cancelCollectLogsWithUUID:(NSUUID *)arg2 peerID:(NSString *)arg3 reply:(void (^)(NSError *))arg4;
- (void)xpcConnection:(W5XPCConnection *)arg1 cancelDiagnosticsWithUUID:(NSUUID *)arg2 peerID:(NSString *)arg3 reply:(void (^)(NSError *))arg4;
- (void)xpcConnection:(W5XPCConnection *)arg1 runPerformanceTest:(W5PerfConfiguration *)arg2 uuid:(NSUUID *)arg3 reply:(void (^)(NSError *, W5PerfResult *))arg4;
- (void)xpcConnection:(W5XPCConnection *)arg1 runWiFiSnifferOnChannel:(W5WiFiChannel *)arg2 duration:(double)arg3 peer:(W5Peer *)arg4 uuid:(NSUUID *)arg5 reply:(void (^)(NSError *, NSURL *))arg6;
- (void)xpcConnection:(W5XPCConnection *)arg1 collectLogItems:(NSArray *)arg2 compress:(_Bool)arg3 peer:(W5Peer *)arg4 uuid:(NSUUID *)arg5 reply:(void (^)(NSError *, NSArray *, NSURL *))arg6;
- (void)xpcConnection:(W5XPCConnection *)arg1 setDebugConfiguration:(W5DebugConfiguration *)arg2 peer:(W5Peer *)arg3 reply:(void (^)(NSError *))arg4;
- (void)xpcConnection:(W5XPCConnection *)arg1 queryDebugConfigurationForPeer:(W5Peer *)arg2 reply:(void (^)(NSError *, W5DebugConfiguration *))arg3;
- (void)xpcConnection:(W5XPCConnection *)arg1 runDiagnosticsTests:(NSArray *)arg2 peer:(W5Peer *)arg3 uuid:(NSUUID *)arg4 reply:(void (^)(NSError *, NSArray *))arg5;
- (void)xpcConnection:(W5XPCConnection *)arg1 queryStatusForPeer:(W5Peer *)arg2 reply:(void (^)(NSError *, W5Status *))arg3;
- (void)xpcConnection:(W5XPCConnection *)arg1 queryLocalPeerAndReply:(void (^)(NSError *, W5Peer *))arg2;
- (void)xpcConnection:(W5XPCConnection *)arg1 queryPeerCacheAndReply:(void (^)(NSError *, NSArray *))arg2;
- (void)xpcConnection:(W5XPCConnection *)arg1 stopMonitoringEvents:(NSArray *)arg2 reply:(void (^)(NSError *))arg3;
- (void)xpcConnection:(W5XPCConnection *)arg1 startMonitoringEvents:(NSArray *)arg2 reply:(void (^)(NSError *))arg3;
- (void)xpcConnection:(W5XPCConnection *)arg1 stopBrowsingAndReply:(void (^)(NSError *))arg2;
- (void)xpcConnection:(W5XPCConnection *)arg1 startBrowsingAndReply:(void (^)(NSError *))arg2;
@end

