//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "MSDContentServerLocatorDelegate-Protocol.h"

@class MSDContentServerConnection, MSDContentServerLocator, NSDate, NSString, NSTimer;

@interface MSDMailProcessor : NSObject <MSDContentServerLocatorDelegate>
{
    _Bool _waitingForCommand;	// 8 = 0x8
    _Bool _fullKeysSent;	// 9 = 0x9
    unsigned long long _pingInterval;	// 16 = 0x10
    NSTimer *_pingTimer;	// 24 = 0x18
    MSDContentServerLocator *_serverLocator;	// 32 = 0x20
    NSString *_serverAddress;	// 40 = 0x28
    NSString *_port;	// 48 = 0x30
    MSDContentServerConnection *_serverConnection;	// 56 = 0x38
    NSDate *_lastPingTimeStamp;	// 64 = 0x40
}

+ (id)sharedInstance;	// IMP=0x000000010004ddcc
@property(retain) NSDate *lastPingTimeStamp; // @synthesize lastPingTimeStamp=_lastPingTimeStamp;
@property _Bool fullKeysSent; // @synthesize fullKeysSent=_fullKeysSent;
@property(retain) MSDContentServerConnection *serverConnection; // @synthesize serverConnection=_serverConnection;
@property(retain) NSString *port; // @synthesize port=_port;
@property(retain) NSString *serverAddress; // @synthesize serverAddress=_serverAddress;
@property(retain) MSDContentServerLocator *serverLocator; // @synthesize serverLocator=_serverLocator;
@property(retain) NSTimer *pingTimer; // @synthesize pingTimer=_pingTimer;
- (void).cxx_destruct;	// IMP=0x00000001000505d0
- (long long)pingIntervalToUse;	// IMP=0x000000010005048c
- (_Bool)processRequest:(id)arg1;	// IMP=0x000000010004f850
- (id)reducedKeyList;	// IMP=0x000000010004f7c8
- (id)fullKeyList;	// IMP=0x000000010004f710
- (_Bool)ack:(_Bool)arg1;	// IMP=0x000000010004f3c0
- (id)ping;	// IMP=0x000000010004ec74
- (void)pingAndProcess:(id)arg1;	// IMP=0x000000010004e8b8
@property _Bool waitingForCommand; // @synthesize waitingForCommand=_waitingForCommand;
@property unsigned long long pingInterval; // @synthesize pingInterval=_pingInterval;
- (_Bool)startPeriodicPing;	// IMP=0x000000010004e5e0
- (_Bool)start;	// IMP=0x000000010004e23c
- (void)contentServerDidDisappear;	// IMP=0x000000010004e238
- (void)contentServerDidAppear:(id)arg1 port:(id)arg2;	// IMP=0x000000010004df6c
- (id)init;	// IMP=0x000000010004de4c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

