//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSError.h>

@interface NSError (MSDExtension)
+ (id)masterServerErrorRetryAfter:(id)arg1;	// IMP=0x00000001000554d4
+ (id)masterServerErrorWithCode:(unsigned long long)arg1 mesage:(id)arg2 reason:(id)arg3;	// IMP=0x00000001000553d8
+ (id)errorDomainMSDWithCode:(long long)arg1 message:(id)arg2 reason:(id)arg3;	// IMP=0x0000000100055344
+ (id)errorDomainMSDWithCode:(long long)arg1 message:(id)arg2;	// IMP=0x00000001000552d4
- (id)initWithDomainMSDCode:(long long)arg1 message:(id)arg2 reason:(id)arg3;	// IMP=0x0000000100055618
- (id)initWithDomainMSDCode:(long long)arg1 message:(id)arg2;	// IMP=0x000000010005558c
@end

