//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface WhitelistChecker : NSObject
{
    NSDictionary *_domains;	// 8 = 0x8
}

@property(retain, nonatomic) NSDictionary *domains; // @synthesize domains=_domains;
- (void).cxx_destruct;	// IMP=0x0000000100010140
- (_Bool)handleSystemContainerFiles:(id)arg1 withMetadata:(id)arg2;	// IMP=0x000000010000feb8
- (_Bool)shouldRestoreSystemContainer_WatchAndTV:(id)arg1 shared:(_Bool)arg2;	// IMP=0x000000010000fe10
- (_Bool)shouldRestoreSystemContainer_iOS:(id)arg1 shared:(_Bool)arg2;	// IMP=0x000000010000fbe0
- (_Bool)file:(id)arg1 blacklisted:(id)arg2;	// IMP=0x000000010000f9c0
- (_Bool)file:(id)arg1 whitelisted:(id)arg2;	// IMP=0x000000010000f848
- (id)createFullPathList:(id)arg1 rootPath:(id)arg2 isAllowList:(_Bool)arg3;	// IMP=0x000000010000f590
- (_Bool)annotated:(id)arg1;	// IMP=0x000000010000f410
- (_Bool)checkFile_WatchAndTV:(id)arg1 withMetaData:(id)arg2;	// IMP=0x000000010000f26c
- (_Bool)checkFile_iOS:(id)arg1 withMetaData:(id)arg2;	// IMP=0x000000010000ec1c
- (_Bool)checkManifest:(id)arg1;	// IMP=0x000000010000ea30
- (_Bool)checkManifestFile:(id)arg1;	// IMP=0x000000010000e850
- (_Bool)load;	// IMP=0x000000010000e784

@end

