//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NESMFilterSessionState.h"

@interface NESMFilterSessionStateRunning : NESMFilterSessionState
{
}

- (void)handleUpdateConfiguration;	// IMP=0x000000010003c6c0
- (void)handleWakeup;	// IMP=0x000000010003c660
- (_Bool)handleSleep;	// IMP=0x000000010003c5f8
- (void)enterWithSession:(id)arg1;	// IMP=0x000000010003c52c
- (id)init;	// IMP=0x000000010003c4f0

@end

