//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NESMSession.h"

@class NEVPNProtocol, NSDictionary, NSString;

@interface NESMLegacySession : NESMSession
{
    int _sessionType;	// 8 = 0x8
    NEVPNProtocol *_protocol;	// 16 = 0x10
    struct _ne_sm_bridge *_bridge;	// 24 = 0x18
    NSDictionary *_userOptions;	// 32 = 0x20
}

@property(retain) NSDictionary *userOptions; // @synthesize userOptions=_userOptions;
@property struct _ne_sm_bridge *bridge; // @synthesize bridge=_bridge;
@property int sessionType; // @synthesize sessionType=_sessionType;
@property(retain) NEVPNProtocol *protocol; // @synthesize protocol=_protocol;
- (void).cxx_destruct;	// IMP=0x0000000100039898
- (void)handleInitializeState;	// IMP=0x00000001000394e8
- (void)handleInstalledAppsChanged;	// IMP=0x00000001000391d8
- (void)handleDeviceUnlock;	// IMP=0x00000001000390fc
- (void)handleDeviceLock;	// IMP=0x0000000100039020
- (void)handleUserSwitch;	// IMP=0x0000000100038f44
- (void)handleUserLogout;	// IMP=0x0000000100038e68
- (_Bool)handleUpdateConfiguration:(id)arg1;	// IMP=0x0000000100038b9c
- (void)uninstall;	// IMP=0x00000001000389ac
- (void)install;	// IMP=0x0000000100038438
- (void)handleGetInfoMessage:(id)arg1 withType:(int)arg2;	// IMP=0x0000000100037fe4
- (void)handleSecuritySessionInfoRequest:(id)arg1;	// IMP=0x0000000100037e58
- (void)handleChangeEventForInterface:(id)arg1 newFlags:(unsigned long long)arg2 previousFlags:(unsigned long long)arg3;	// IMP=0x0000000100037b5c
- (void)handleWakeup;	// IMP=0x0000000100037a20
- (void)handleSleepTime:(double)arg1;	// IMP=0x0000000100037950
- (_Bool)handleSleep;	// IMP=0x0000000100037854
- (void)handleStopMessageWithReason:(int)arg1;	// IMP=0x0000000100037754
- (void)handleStartMessage:(id)arg1;	// IMP=0x0000000100036e7c
- (id)addDecryptedPasswordsToOptions:(id)arg1;	// IMP=0x0000000100036710
- (void)performBlockOnMainRunLoop:(CDUnknownBlockType)arg1;	// IMP=0x00000001000366c8
- (void)handleDisposable;	// IMP=0x0000000100036620
- (_Bool)hasDNSInstalled;	// IMP=0x000000010003653c
- (_Bool)hasProxiesInstalled;	// IMP=0x00000001000363f8
@property(readonly) NSString *interfaceName;
- (void)dealloc;	// IMP=0x0000000100035ff8
- (int)type;	// IMP=0x0000000100035fec
- (id)initWithConfiguration:(id)arg1 andServer:(id)arg2 andProtocol:(id)arg3 andSessionType:(int)arg4;	// IMP=0x0000000100035c50

@end

