//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NESMVPNSessionState.h"

@interface NESMVPNSessionStateAuthenticating : NESMVPNSessionState
{
}

- (void)handleTimeout;	// IMP=0x000000010005c8e4
- (void)handlePlugin:(id)arg1 authenticationCompleteWithResults:(id)arg2 status:(int)arg3 andError:(id)arg4;	// IMP=0x000000010005c580
- (void)handlePlugin:(id)arg1 didStartWithPID:(int)arg2;	// IMP=0x000000010005c3b0
- (void)enterWithSession:(id)arg1;	// IMP=0x000000010005c218
- (id)init;	// IMP=0x000000010005c1dc

@end

