//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NEAgentAppProxyExtension.h"

@interface NEAgentDNSProxyExtension : NEAgentAppProxyExtension
{
}

- (int)requiredEntitlement;	// IMP=0x000000010000b2c0
- (void)handleDNSSettingsMessage:(id)arg1;	// IMP=0x000000010000b210
- (void)handleMessage:(id)arg1 withOuterMessage:(id)arg2;	// IMP=0x000000010000b164

@end

