//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NEHelperDelegate-Protocol.h"

@class NSString;

@interface NEHelperHotspotConfigurationManager : NSObject <NEHelperDelegate>
{
    NSString *_bundleID;	// 8 = 0x8
}

+ (void)checkAppForConfigurationCleanup:(id)arg1;	// IMP=0x0000000100004858
+ (_Bool)verifyEntitlement:(id)arg1;	// IMP=0x0000000100002578
+ (void)initGlobals;	// IMP=0x000000010000246c
@property(readonly) NSString *bundleID; // @synthesize bundleID=_bundleID;
- (void).cxx_destruct;	// IMP=0x0000000100004a60
- (void)handleMessage:(id)arg1;	// IMP=0x000000010000467c
- (_Bool)processRequest:(id)arg1;	// IMP=0x0000000100004608
- (_Bool)processQueryNetworks:(id)arg1;	// IMP=0x00000001000042dc
- (_Bool)processRemoveConfigurationRequest:(id)arg1;	// IMP=0x0000000100004128
- (void)removeWiFiNetworkConfiguration:(id)arg1;	// IMP=0x0000000100003e64
- (_Bool)checkIfJoinOnceNetworkAndDisassociate:(struct __WiFiManagerClient *)arg1;	// IMP=0x0000000100003be8
- (_Bool)processAddConfigurationRequest:(id)arg1;	// IMP=0x0000000100003510
- (_Bool)checkIfSystemAppOrDaemon;	// IMP=0x00000001000033b4
- (struct __WiFiNetwork *)createWiFiNetworkFromConfiguration:(id)arg1;	// IMP=0x0000000100002eac
- (id)createEAPClientConfiguration:(id)arg1;	// IMP=0x000000010000294c
- (id)getTTLSInnerAuthenticationString:(long long)arg1;	// IMP=0x00000001000028c4
@property(readonly, nonatomic) NSString *name;
- (id)initWithFirstMessage:(id)arg1;	// IMP=0x0000000100002738

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

