//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NEConfigurationManagerDelegate-Protocol.h"

@class NSMutableArray;
@protocol OS_dispatch_queue, OS_xpc_object;

@interface NEHelperServer : NSObject <NEConfigurationManagerDelegate>
{
    int _firstUnlockToken;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_queue;	// 16 = 0x10
    NSObject<OS_xpc_object> *_listener;	// 24 = 0x18
    NSMutableArray *_clients;	// 32 = 0x20
}

+ (Class)classFromID:(int)arg1;	// IMP=0x000000010001bc78
+ (_Bool)containsExtension:(id)arg1 extensionProtocol:(id)arg2;	// IMP=0x000000010001ad38
+ (_Bool)verifyConnection:(id)arg1 hasEntitlement:(const char *)arg2;	// IMP=0x0000000100019944
+ (void)sendReplyForMessage:(id)arg1 result:(long long)arg2 data:(id)arg3;	// IMP=0x0000000100019890
+ (void)sendAppPathsToEventAgent:(id)arg1;	// IMP=0x0000000100019188
+ (void)sendSocketToEventAgent:(int)arg1;	// IMP=0x0000000100019124
+ (id)sharedServer;	// IMP=0x00000001000180fc
@property int firstUnlockToken; // @synthesize firstUnlockToken=_firstUnlockToken;
@property(readonly) NSMutableArray *clients; // @synthesize clients=_clients;
@property(readonly) NSObject<OS_xpc_object> *listener; // @synthesize listener=_listener;
@property(readonly) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void).cxx_destruct;	// IMP=0x000000010001be00
- (id)copyClientsWithName:(id)arg1 delegateClassID:(int)arg2;	// IMP=0x000000010001ba20
- (void)handleEvent:(id)arg1 ofType:(const char *)arg2;	// IMP=0x000000010001afdc
- (_Bool)handleOnDemandPolicy:(id)arg1 applicationRemoved:(_Bool)arg2;	// IMP=0x000000010001a5dc
- (void)stopConfig:(id)arg1;	// IMP=0x000000010001a068
- (void)handleControlSettingsFileChanged;	// IMP=0x0000000100019c88
- (void)handleManagedPreferencesChangedForInitCheck:(_Bool)arg1;	// IMP=0x0000000100019ab8
- (void)handleSCPreferencesChangedEvent;	// IMP=0x0000000100019818
- (void)handleNetworkDetectionEvaluateEvent:(id)arg1;	// IMP=0x00000001000193f8
- (void)acceptNewConnection:(id)arg1;	// IMP=0x0000000100018688
- (void)removeProfile:(id)arg1;	// IMP=0x0000000100018618
- (void)stop;	// IMP=0x00000001000185e0
- (void)start;	// IMP=0x0000000100018180
- (id)initPrivate;	// IMP=0x0000000100017f0c
- (id)init;	// IMP=0x0000000100017ee4

@end

