//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKCollectionDataSource.h"

@class GKGameRecord, NSArray;

@interface GKAchievementDataSource : GKCollectionDataSource
{
    GKGameRecord *_gameRecord;	// 8 = 0x8
    NSArray *_achievements;	// 16 = 0x10
    NSArray *_localAchievements;	// 24 = 0x18
    struct UIEdgeInsets _collectionLayoutInsets;	// 32 = 0x20
}

@property(nonatomic) struct UIEdgeInsets collectionLayoutInsets; // @synthesize collectionLayoutInsets=_collectionLayoutInsets;
@property(retain, nonatomic) NSArray *localAchievements; // @synthesize localAchievements=_localAchievements;
@property(retain, nonatomic) NSArray *achievements; // @synthesize achievements=_achievements;
@property(retain, nonatomic) GKGameRecord *gameRecord; // @synthesize gameRecord=_gameRecord;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x000000010002651c
- (_Bool)collectionView:(id)arg1 shouldSelectItemAtIndexPath:(id)arg2;	// IMP=0x00000001000264e8
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;	// IMP=0x00000001000264dc
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;	// IMP=0x00000001000264d0
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;	// IMP=0x000000010002644c
- (id)heightMultipliersForSizeCategories;	// IMP=0x000000010002640c
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;	// IMP=0x0000000100026158
- (id)itemForIndexPath:(id)arg1;	// IMP=0x00000001000260b8
- (double)preferredCollectionHeight;	// IMP=0x0000000100026014
- (id)sectionHeaderText;	// IMP=0x0000000100025f1c
- (long long)itemCount;	// IMP=0x0000000100025f04
- (void)loadDataWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100025c3c
- (void)setupCollectionView:(id)arg1;	// IMP=0x0000000100025ab8
- (void)dealloc;	// IMP=0x0000000100025a34
- (id)initWithGameRecord:(id)arg1;	// IMP=0x00000001000259c0

@end

