//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKDashboardLabel.h"

@interface GKDashboardLabelCallout : GKDashboardLabel
{
}

- (id)fontTextStyle;	// IMP=0x00000001000035b0

@end

