//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class UICollectionView;

@interface GKDashboardNestedCollectionCell : UICollectionViewCell
{
    UICollectionView *_collectionView;	// 8 = 0x8
}

@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (id)preferredFocusEnvironments;	// IMP=0x000000010001cda0
- (_Bool)canBecomeFocused;	// IMP=0x000000010001cd98
- (void)dealloc;	// IMP=0x000000010001cd40
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010001cb9c

@end

