//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class GKDashboardFloatingCircleView, NSLayoutConstraint, UIColor, UIImageView, UILabel;

@interface GKDashboardCircleButtonCell : UICollectionViewCell
{
    UIImageView *_imageView;	// 8 = 0x8
    UILabel *_label;	// 16 = 0x10
    NSLayoutConstraint *_imageViewBottomToLabelTopConstraint;	// 24 = 0x18
    double _imageViewBottomToLabelTopConstant;	// 32 = 0x20
    GKDashboardFloatingCircleView *_floatingView;	// 40 = 0x28
    UIColor *_labelColor;	// 48 = 0x30
}

@property(retain, nonatomic) UIColor *labelColor; // @synthesize labelColor=_labelColor;
@property(nonatomic) GKDashboardFloatingCircleView *floatingView; // @synthesize floatingView=_floatingView;
@property(nonatomic) double imageViewBottomToLabelTopConstant; // @synthesize imageViewBottomToLabelTopConstant=_imageViewBottomToLabelTopConstant;
@property(nonatomic) NSLayoutConstraint *imageViewBottomToLabelTopConstraint; // @synthesize imageViewBottomToLabelTopConstraint=_imageViewBottomToLabelTopConstraint;
@property(nonatomic) UILabel *label; // @synthesize label=_label;
@property(nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x000000010001c760
- (void)setupForAddPlayer;	// IMP=0x000000010001c650
- (void)setupForShowMore;	// IMP=0x000000010001c540
- (void)dealloc;	// IMP=0x000000010001c4e8
- (void)awakeFromNib;	// IMP=0x000000010001c340

@end

