//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKDashboardMultiCollectionViewController.h"

@class GKAchievementDataSource, GKDashboardChallengesTurnsDataSource, GKDashboardLeaderboardListDataSource, GKDashboardLeaderboardSetDataSource, GKGameRecord, GKLogoImageView, NSDictionary, NSString, UITapGestureRecognizer;

@interface GKDashboardViewController : GKDashboardMultiCollectionViewController
{
    _Bool _shouldShowPlayForChallenge;	// 8 = 0x8
    _Bool _shouldShowPlayForTurnBasedMatch;	// 9 = 0x9
    _Bool _shouldShowQuitForTurnBasedMatch;	// 10 = 0xa
    long long _viewState;	// 16 = 0x10
    NSString *_leaderboardIdentifier;	// 24 = 0x18
    GKGameRecord *_gameRecord;	// 32 = 0x20
    GKDashboardChallengesTurnsDataSource *_challengesTurnsDataSource;	// 40 = 0x28
    GKDashboardLeaderboardSetDataSource *_leaderboardSetDataSource;	// 48 = 0x30
    GKDashboardLeaderboardListDataSource *_leaderboardListDataSource;	// 56 = 0x38
    GKAchievementDataSource *_achievementDataSource;	// 64 = 0x40
    GKLogoImageView *_headerImageView;	// 72 = 0x48
    NSDictionary *_dashboardAssetNames;	// 80 = 0x50
    NSDictionary *_leaderboardSetAssetNames;	// 88 = 0x58
    NSDictionary *_leaderboardAssetNames;	// 96 = 0x60
    UITapGestureRecognizer *_menuGestureRecognizer;	// 104 = 0x68
}

@property(retain, nonatomic) UITapGestureRecognizer *menuGestureRecognizer; // @synthesize menuGestureRecognizer=_menuGestureRecognizer;
@property(retain, nonatomic) NSDictionary *leaderboardAssetNames; // @synthesize leaderboardAssetNames=_leaderboardAssetNames;
@property(retain, nonatomic) NSDictionary *leaderboardSetAssetNames; // @synthesize leaderboardSetAssetNames=_leaderboardSetAssetNames;
@property(retain, nonatomic) NSDictionary *dashboardAssetNames; // @synthesize dashboardAssetNames=_dashboardAssetNames;
@property(retain, nonatomic) GKLogoImageView *headerImageView; // @synthesize headerImageView=_headerImageView;
@property(nonatomic) GKAchievementDataSource *achievementDataSource; // @synthesize achievementDataSource=_achievementDataSource;
@property(nonatomic) GKDashboardLeaderboardListDataSource *leaderboardListDataSource; // @synthesize leaderboardListDataSource=_leaderboardListDataSource;
@property(nonatomic) GKDashboardLeaderboardSetDataSource *leaderboardSetDataSource; // @synthesize leaderboardSetDataSource=_leaderboardSetDataSource;
@property(nonatomic) GKDashboardChallengesTurnsDataSource *challengesTurnsDataSource; // @synthesize challengesTurnsDataSource=_challengesTurnsDataSource;
@property(retain, nonatomic) GKGameRecord *gameRecord; // @synthesize gameRecord=_gameRecord;
@property(nonatomic) _Bool shouldShowQuitForTurnBasedMatch; // @synthesize shouldShowQuitForTurnBasedMatch=_shouldShowQuitForTurnBasedMatch;
@property(nonatomic) _Bool shouldShowPlayForTurnBasedMatch; // @synthesize shouldShowPlayForTurnBasedMatch=_shouldShowPlayForTurnBasedMatch;
@property(nonatomic) _Bool shouldShowPlayForChallenge; // @synthesize shouldShowPlayForChallenge=_shouldShowPlayForChallenge;
@property(retain, nonatomic) NSString *leaderboardIdentifier; // @synthesize leaderboardIdentifier=_leaderboardIdentifier;
@property(nonatomic) long long viewState; // @synthesize viewState=_viewState;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;	// IMP=0x000000010001903c
- (void)setDashboardAssetNames:(id)arg1 leaderboardSetAssetNames:(id)arg2 leaderboardAssetNames:(id)arg3;	// IMP=0x0000000100018f84
- (void)showLeaderboardVC;	// IMP=0x0000000100018e54
@property(nonatomic) long long leaderboardTimeScope;
- (void)didPressMenuButton;	// IMP=0x0000000100018664
- (void)_gkRefreshContentsForDataType:(unsigned int)arg1 userInfo:(id)arg2;	// IMP=0x00000001000184b0
- (_Bool)_gkShouldRefreshContentsForDataType:(unsigned int)arg1 userInfo:(id)arg2;	// IMP=0x00000001000184a8
- (void)loadData;	// IMP=0x0000000100017f9c
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x0000000100017efc
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100017e7c
- (void)viewDidLoad;	// IMP=0x0000000100017d1c
- (void)dealloc;	// IMP=0x0000000100017c48
- (id)initWithGameRecord:(id)arg1;	// IMP=0x00000001000179b0

@end

