//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKCollectionDataSource.h"

@class GKTurnBasedMatch;

@interface GKDashboardTurnDetailDataSource : GKCollectionDataSource
{
    GKTurnBasedMatch *_match;	// 8 = 0x8
}

@property(retain, nonatomic) GKTurnBasedMatch *match; // @synthesize match=_match;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;	// IMP=0x00000001000031d8
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;	// IMP=0x000000010000300c
- (long long)numberOfSectionsInCollectionView:(id)arg1;	// IMP=0x0000000100003004
- (id)sectionHeaderText;	// IMP=0x0000000100002f8c
- (id)itemForIndexPath:(id)arg1;	// IMP=0x0000000100002edc
- (double)preferredCollectionHeight;	// IMP=0x0000000100002ec8
- (long long)itemCount;	// IMP=0x0000000100002e98
- (void)loadDataWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100002e7c
- (void)setupCollectionView:(id)arg1;	// IMP=0x0000000100002e04
- (void)dealloc;	// IMP=0x0000000100002dac
- (id)initWithMatch:(id)arg1;	// IMP=0x0000000100002d14

@end

