//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSSet, NSString, NSURL;

@interface MIBundle : NSObject
{
    unsigned char _bundleType;	// 8 = 0x8
    NSDictionary *_infoPlistSubset;	// 16 = 0x10
    NSURL *_bundleParentDirectoryURL;	// 24 = 0x18
    NSString *_parentBundleID;	// 32 = 0x20
    NSString *_bundleName;	// 40 = 0x28
    NSString *_bundleParentSubdirectory;	// 48 = 0x30
    MIBundle *_parentBundle;	// 56 = 0x38
    NSArray *_pluginKitBundles;	// 64 = 0x40
    NSArray *_frameworkBundles;	// 72 = 0x48
    NSArray *_xpcServiceBundles;	// 80 = 0x50
}

+ (id)bundleForURL:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100026884
+ (_Bool)bundleIsBlacklisted:(id)arg1;	// IMP=0x0000000100025d60
+ (id)bundlesInParentBundle:(id)arg1 subDirectory:(id)arg2 matchingPredicate:(CDUnknownBlockType)arg3 error:(id *)arg4;	// IMP=0x0000000100023c8c
+ (id)_URLOfFirstBundleInDirectory:(id)arg1 withExtension:(id)arg2 error:(id *)arg3;	// IMP=0x0000000100022c4c
@property(retain, nonatomic) NSArray *xpcServiceBundles; // @synthesize xpcServiceBundles=_xpcServiceBundles;
@property(retain, nonatomic) NSArray *frameworkBundles; // @synthesize frameworkBundles=_frameworkBundles;
@property(retain, nonatomic) NSArray *pluginKitBundles; // @synthesize pluginKitBundles=_pluginKitBundles;
@property(readonly, nonatomic) __weak MIBundle *parentBundle; // @synthesize parentBundle=_parentBundle;
@property(readonly, copy, nonatomic) NSString *bundleParentSubdirectory; // @synthesize bundleParentSubdirectory=_bundleParentSubdirectory;
@property(readonly, copy, nonatomic) NSString *bundleName; // @synthesize bundleName=_bundleName;
@property(readonly, copy, nonatomic) NSString *parentBundleID; // @synthesize parentBundleID=_parentBundleID;
- (void).cxx_destruct;	// IMP=0x0000000100028c10
@property(readonly, nonatomic) _Bool nameIsLocalized;
- (id)_hasAtLeastOneOfKeysSet:(id)arg1 inPlistAtURL:(id)arg2 result:(_Bool *)arg3;	// IMP=0x00000001000282fc
- (_Bool)validateAppMetadataWithError:(id *)arg1;	// IMP=0x00000001000280bc
@property(readonly, nonatomic) NSSet *siriIntents;
- (id)description;	// IMP=0x0000000100027d28
- (_Bool)thinningMatchesCurrentDeviceWithError:(id *)arg1;	// IMP=0x0000000100027838
@property(readonly, copy, nonatomic) NSArray *supportedDevices;
- (_Bool)isApplicableToCurrentDeviceCapabilitiesWithError:(id *)arg1;	// IMP=0x0000000100027490
- (_Bool)isApplicableToOSVersion:(id)arg1 error:(id *)arg2;	// IMP=0x00000001000272bc
- (_Bool)isApplicableToCurrentOSVersionWithError:(id *)arg1;	// IMP=0x00000001000271d8
- (_Bool)isApplicableToCurrentDeviceFamilyWithError:(id *)arg1;	// IMP=0x0000000100026e2c
- (_Bool)isCompatibleWithDeviceFamily:(int)arg1;	// IMP=0x0000000100026ca0
@property(readonly, nonatomic) _Bool isLaunchProhibited;
@property(readonly, nonatomic) _Bool isWatchApp;
@property(readonly, copy, nonatomic) NSArray *deviceFamilies;
@property(readonly, copy, nonatomic) NSString *minimumOSVersion;
@property(readonly, nonatomic) _Bool needsDataContainer;
@property(readonly, nonatomic) NSURL *bundleURL;
@property(retain, nonatomic) NSURL *bundleParentDirectoryURL; // @synthesize bundleParentDirectoryURL=_bundleParentDirectoryURL;
- (id)xpcServiceBundlesWithError:(id *)arg1;	// IMP=0x00000001000261c0
- (id)frameworkBundlesWithError:(id *)arg1;	// IMP=0x0000000100025fc0
- (_Bool)validatePluginMetadataWithError:(id *)arg1;	// IMP=0x00000001000248a4
- (id)pluginKitBundlesWithError:(id *)arg1;	// IMP=0x0000000100024890
- (id)pluginKitBundlesSkippingPlatformValidation:(_Bool)arg1 withError:(id *)arg2;	// IMP=0x0000000100024118
@property(readonly, nonatomic) _Bool isPlaceholder;
@property(readonly, copy, nonatomic) NSString *bundleTypeDescription;
@property(readonly, nonatomic) unsigned char bundleType; // @synthesize bundleType=_bundleType;
@property(readonly, nonatomic) _Bool isRemovableSystemApp;
@property(readonly, copy, nonatomic) NSString *identifier;
@property(readonly, copy, nonatomic) NSDictionary *infoPlistSubset; // @synthesize infoPlistSubset=_infoPlistSubset;
- (id)_infoPlistKeysToLoad;	// IMP=0x0000000100023064
- (id)initWithBundleInDirectory:(id)arg1 withExtension:(id)arg2 error:(id *)arg3;	// IMP=0x0000000100022f8c
- (id)initWithBundleURL:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100022b90
- (id)initWithParentBundle:(id)arg1 parentSubdirectory:(id)arg2 bundleName:(id)arg3 error:(id *)arg4;	// IMP=0x0000000100022a14
- (id)initWithBundleParentURL:(id)arg1 parentSubdirectory:(id)arg2 bundleName:(id)arg3 error:(id *)arg4;	// IMP=0x00000001000228e4
- (_Bool)_validateWithError:(id *)arg1;	// IMP=0x00000001000224e4

@end

