//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSURLSessionDataDelegate-Protocol.h"
#import "NSURLSessionDelegate-Protocol.h"
#import "NSURLSessionStreamDelegate-Protocol.h"
#import "NSURLSessionTaskDelegate-Protocol.h"
#import "ReportingSessionConnectivityInterface-Protocol.h"

@class NSDictionary, NSMutableDictionary, NSOperationQueue, NSString, NSURLSession;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface ReportingSessionConnectivityHelper : NSObject <ReportingSessionConnectivityInterface, NSURLSessionDelegate, NSURLSessionTaskDelegate, NSURLSessionDataDelegate, NSURLSessionStreamDelegate>
{
    NSURLSession *_privateURLSession;	// 8 = 0x8
    id _reportingdSessionDelegate;	// 16 = 0x10
    NSMutableDictionary *_tasks;	// 24 = 0x18
    NSDictionary *_userInfo;	// 32 = 0x20
    int _mode;	// 40 = 0x28
    NSObject<OS_dispatch_queue> *_stateQueue;	// 48 = 0x30
    NSOperationQueue *_NSURLDelegateQueue;	// 56 = 0x38
    _Bool _isActive;	// 64 = 0x40
    NSMutableDictionary *_requestInProgress;	// 72 = 0x48
    unsigned int _usageCount;	// 80 = 0x50
    unsigned int _totalSessionsServedCount;	// 84 = 0x54
    unsigned int _releaseTimeout;	// 88 = 0x58
    NSObject<OS_dispatch_source> *_connectivityHelperReleaseTimer;	// 96 = 0x60
    CDUnknownBlockType _connectivityHelperReleaseTimerBlock;	// 104 = 0x68
    NSObject<OS_dispatch_queue> *_connectivityHelperReleaseTimerQueue;	// 112 = 0x70
}

+ (int)POSTRequestMode;	// IMP=0x000000010001a3c0
+ (int)GETRequestMode;	// IMP=0x000000010001a3b8
+ (_Bool)deleteContainerAtURL:(id)arg1;	// IMP=0x000000010001a360
+ (id)composeUniqueContainerURL;	// IMP=0x000000010001a2c0
+ (void)cleanupStorageRootFolder;	// IMP=0x000000010001a1c8
+ (id)storageRootFolder;	// IMP=0x000000010001a1a8
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveData:(id)arg3;	// IMP=0x000000010001aa34
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didBecomeDownloadTask:(id)arg3;	// IMP=0x000000010001a988
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveResponse:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x000000010001a898
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;	// IMP=0x000000010001a674
- (void)URLSession:(id)arg1 task:(id)arg2 didSendBodyData:(long long)arg3 totalBytesSent:(long long)arg4 totalBytesExpectedToSend:(long long)arg5;	// IMP=0x000000010001a580
- (void)URLSession:(id)arg1 didBecomeInvalidWithError:(id)arg2;	// IMP=0x000000010001a3c8
- (void)getURLRequestWithCompletionHandler:(id)arg1 isUrgent:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010001996c
- (void)postURLRequestWithCompletionHandler:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100019604
- (void)createHelperForTask:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100019478
- (id)privateURLSessionConfigWithMode:(int)arg1;	// IMP=0x00000001000192e0
- (void)ownerDecrementUsageCountWithBlock:(CDUnknownBlockType)arg1 queue:(id)arg2;	// IMP=0x0000000100018f98
- (void)ownerIncrementUsageCount;	// IMP=0x0000000100018e04
- (void)incrementTotalSessionsServedCount;	// IMP=0x0000000100018d3c
- (void)activate:(unsigned int)arg1;	// IMP=0x000000010001894c
- (void)setReleaseTimeout:(unsigned int)arg1;	// IMP=0x00000001000188d0
- (void)stopConnectivityHelperReleaseTimer;	// IMP=0x00000001000187e0
- (void)startConnectivityHelperReleaseTimerWithBlock:(CDUnknownBlockType)arg1 queue:(id)arg2;	// IMP=0x00000001000180e4
- (void)invalidate;	// IMP=0x0000000100017f34
- (void)releaseAllXPCTransactions;	// IMP=0x0000000100017eb0
- (void)dealloc;	// IMP=0x0000000100017d3c
- (id)initWithDelegate:(id)arg1 mode:(int)arg2 userInfo:(id)arg3;	// IMP=0x0000000100017ba0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

