//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RTCReportingBackend.h"

@class NSString;

@interface UploadBackend : RTCReportingBackend
{
    NSString *_uploadURL;	// 216 = 0xd8
}

@property(copy) NSString *uploadURL; // @synthesize uploadURL=_uploadURL;
- (_Bool)uploadFileAtPath:(id)arg1 extensionToken:(char *)arg2;	// IMP=0x000000010000e8f0
- (void)dealloc;	// IMP=0x000000010000e898
- (id)initWithName:(id)arg1 profile:(id)arg2 productFamily:(id)arg3;	// IMP=0x000000010000e76c

@end

