//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class PDURLSessionProxyTaskMessage;

@interface PDURLSessionProxyOpenBodyStream : PBCodable <NSCopying>
{
    PDURLSessionProxyTaskMessage *_task;	// 8 = 0x8
}

@property(retain, nonatomic) PDURLSessionProxyTaskMessage *task; // @synthesize task=_task;
- (void).cxx_destruct;	// IMP=0x000000010003c98c
- (void)mergeFrom:(id)arg1;	// IMP=0x000000010003c904
- (unsigned long long)hash;	// IMP=0x000000010003c8ec
- (_Bool)isEqual:(id)arg1;	// IMP=0x000000010003c844
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010003c7c0
- (void)copyTo:(id)arg1;	// IMP=0x000000010003c798
- (void)writeTo:(id)arg1;	// IMP=0x000000010003c774
- (_Bool)readFrom:(id)arg1;	// IMP=0x000000010003c76c
- (id)dictionaryRepresentation;	// IMP=0x000000010003c4d0
- (id)description;	// IMP=0x000000010003c41c
@property(readonly, nonatomic) _Bool hasTask;

@end

