//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class NSData, PDURLSessionProxyTaskMessage;

@interface PDURLSessionProxyDidReceiveData : PBCodable <NSCopying>
{
    NSData *_receivedData;	// 8 = 0x8
    PDURLSessionProxyTaskMessage *_task;	// 16 = 0x10
}

@property(retain, nonatomic) NSData *receivedData; // @synthesize receivedData=_receivedData;
@property(retain, nonatomic) PDURLSessionProxyTaskMessage *task; // @synthesize task=_task;
- (void).cxx_destruct;	// IMP=0x000000010002d8ac
- (void)mergeFrom:(id)arg1;	// IMP=0x000000010002d7e0
- (unsigned long long)hash;	// IMP=0x000000010002d784
- (_Bool)isEqual:(id)arg1;	// IMP=0x000000010002d6ac
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010002d5f4
- (void)copyTo:(id)arg1;	// IMP=0x000000010002d588
- (void)writeTo:(id)arg1;	// IMP=0x000000010002d524
- (_Bool)readFrom:(id)arg1;	// IMP=0x000000010002d51c
- (id)dictionaryRepresentation;	// IMP=0x000000010002d220
- (id)description;	// IMP=0x000000010002d16c
@property(readonly, nonatomic) _Bool hasReceivedData;
@property(readonly, nonatomic) _Bool hasTask;

@end

