/*
* This header is generated by classdump-dyld 1.0
* on Saturday, August 24, 2019 at 9:49:29 PM Mountain Standard Time
* Operating System: Version 12.4 (Build 16M568)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class GEOMapFeatureRoad, NSString;

@interface RTRouteFinderRoadItem : NSObject {

	GEOMapFeatureRoad* _road;
	NSString* _uniqueID;
	double _distance;
	double _cost;
	RTRouteFinderRoadItem* _prevRoadItem;

}

@property (nonatomic,retain) GEOMapFeatureRoad * road;                          //@synthesize road=_road - In the implementation block
@property (nonatomic,retain) NSString * uniqueID;                               //@synthesize uniqueID=_uniqueID - In the implementation block
@property (assign,nonatomic) double distance;                                   //@synthesize distance=_distance - In the implementation block
@property (assign,nonatomic) double cost;                                       //@synthesize cost=_cost - In the implementation block
@property (nonatomic,retain) RTRouteFinderRoadItem * prevRoadItem;              //@synthesize prevRoadItem=_prevRoadItem - In the implementation block
-(void)setUniqueID:(NSString *)arg1 ;
-(NSString *)uniqueID;
-(void)setDistance:(double)arg1 ;
-(double)distance;
-(void)setRoad:(GEOMapFeatureRoad *)arg1 ;
-(GEOMapFeatureRoad *)road;
-(double)cost;
-(void)setCost:(double)arg1 ;
-(id)initWithRoad:(id)arg1 distance:(double)arg2 cost:(double)arg3 prevRoadItem:(id)arg4 ;
-(id)initWithRoad:(id)arg1 distance:(double)arg2 cost:(double)arg3 ;
-(RTRouteFinderRoadItem *)prevRoadItem;
-(void)setPrevRoadItem:(RTRouteFinderRoadItem *)arg1 ;
-(id)description;
-(long long)compare:(id)arg1 ;
@end

