//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "ConfigAgent.h"

@class NSString, NSUUID;

@interface ProxyAgent : ConfigAgent
{
    NSUUID *agentUUID;	// 8 = 0x8
    NSString *agentDescription;	// 16 = 0x10
    unsigned long long _internalAgentType;	// 24 = 0x18
    NSString *_internalAgentName;	// 32 = 0x20
    unsigned long long _internalAgentSubType;	// 40 = 0x28
}

+ (id)agentType;	// IMP=0x00000001000215c4
@property(nonatomic) unsigned long long internalAgentSubType; // @synthesize internalAgentSubType=_internalAgentSubType;
@property(retain, nonatomic) NSString *internalAgentName; // @synthesize internalAgentName=_internalAgentName;
@property(nonatomic) unsigned long long internalAgentType; // @synthesize internalAgentType=_internalAgentType;
- (void)setAgentDescription:(id)arg1;	// IMP=0x0000000100021a74
- (id)agentDescription;	// IMP=0x0000000100021a24
- (void)setAgentUUID:(id)arg1;	// IMP=0x00000001000219d8
- (id)agentUUID;	// IMP=0x0000000100021988
- (void).cxx_destruct;	// IMP=0x0000000100021ca4
- (id)getAgentUUID;	// IMP=0x0000000100021938
- (unsigned long long)getAgentSubType;	// IMP=0x00000001000218e8
- (id)getAgentName;	// IMP=0x0000000100021898
- (unsigned long long)getAgentType;	// IMP=0x0000000100021848
- (id)initWithParameters:(id)arg1;	// IMP=0x0000000100021624

@end

