//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "HBCloudSyncOperationDelegate.h"

@class ACAccount, HBCloudSyncDatabaseFacade, NSError, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_source>, NSString, TVSPreferences, TVSStateMachine;

@interface HBCloudSyncManager : NSObject <HBCloudSyncOperationDelegate>
{
    id _headboardPrefsObserverToken;	// 8 = 0x8
    _Bool _isDeviceToCloudSyncRequestPending;	// 16 = 0x10
    _Bool _didPerformMigrationCheck;	// 17 = 0x11
    NSError *_cloudSyncOperationError;	// 24 = 0x18
    TVSStateMachine *_stateMachine;	// 32 = 0x20
    TVSPreferences *_sharedHeadBoardPreferences;	// 40 = 0x28
    ACAccount *_activeAccount;	// 48 = 0x30
    HBCloudSyncDatabaseFacade *_cloudSyncDatabaseFacade;	// 56 = 0x38
    long long _totalRetryAttemptsMadePostFailure;	// 64 = 0x40
    double _waitTimeBeforeRetryingSyncOperation;	// 72 = 0x48
    NSObject<OS_dispatch_queue> *_cloudSyncManagerQueue;	// 80 = 0x50
    NSObject<OS_dispatch_source> *_cloudSyncTimerSource;	// 88 = 0x58
    NSObject<OS_dispatch_source> *_cloudSyncOperationRetryTimerSource;	// 96 = 0x60
}

+ (id)sharedCloudSyncManager;	// IMP=0x000000010001c748
+ (void)initialize;	// IMP=0x000000010001c6dc
@property(retain, nonatomic) NSObject<OS_dispatch_source> *cloudSyncOperationRetryTimerSource; // @synthesize cloudSyncOperationRetryTimerSource=_cloudSyncOperationRetryTimerSource;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *cloudSyncTimerSource; // @synthesize cloudSyncTimerSource=_cloudSyncTimerSource;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *cloudSyncManagerQueue; // @synthesize cloudSyncManagerQueue=_cloudSyncManagerQueue;
@property(nonatomic) double waitTimeBeforeRetryingSyncOperation; // @synthesize waitTimeBeforeRetryingSyncOperation=_waitTimeBeforeRetryingSyncOperation;
@property(nonatomic) long long totalRetryAttemptsMadePostFailure; // @synthesize totalRetryAttemptsMadePostFailure=_totalRetryAttemptsMadePostFailure;
@property(nonatomic) _Bool didPerformMigrationCheck; // @synthesize didPerformMigrationCheck=_didPerformMigrationCheck;
@property(nonatomic) _Bool isDeviceToCloudSyncRequestPending; // @synthesize isDeviceToCloudSyncRequestPending=_isDeviceToCloudSyncRequestPending;
@property(retain, nonatomic) HBCloudSyncDatabaseFacade *cloudSyncDatabaseFacade; // @synthesize cloudSyncDatabaseFacade=_cloudSyncDatabaseFacade;
@property(retain, nonatomic) ACAccount *activeAccount; // @synthesize activeAccount=_activeAccount;
@property(retain, nonatomic) TVSPreferences *sharedHeadBoardPreferences; // @synthesize sharedHeadBoardPreferences=_sharedHeadBoardPreferences;
@property(retain, nonatomic) TVSStateMachine *stateMachine; // @synthesize stateMachine=_stateMachine;
@property(retain, nonatomic) NSError *cloudSyncOperationError; // @synthesize cloudSyncOperationError=_cloudSyncOperationError;
- (void).cxx_destruct;	// IMP=0x00000001000216e4
- (id)_updateInternalCloudSyncState;	// IMP=0x00000001000214a8
- (id)_beginCloudToDeviceSync;	// IMP=0x0000000100021450
- (id)_beginDeviceToCloudSync;	// IMP=0x00000001000213f8
- (void)_resetRetryParameters;	// IMP=0x0000000100021378
- (void)_cancelRetryTimerSource;	// IMP=0x0000000100021334
- (void)_cancelTimerSource;	// IMP=0x00000001000212f0
- (_Bool)_fireDeviceToCloudSyncOperationIfPending;	// IMP=0x0000000100021178
- (void)_scheduleSyncOperationRetryTimerForPostingEvent:(id)arg1;	// IMP=0x0000000100020dd8
- (void)_scheduleCloudSyncTimerWithDefaultTimeOut;	// IMP=0x0000000100020b18
- (void)_retryFailedOperationByPostingEvent:(id)arg1;	// IMP=0x000000010002083c
- (_Bool)_shouldRetryFailedOperation;	// IMP=0x00000001000207d8
- (void)cloudSyncOperationDidCompleteSuccessfully:(id)arg1;	// IMP=0x00000001000205a0
- (void)cloudSyncOperationDidFailWithError:(id)arg1;	// IMP=0x0000000100020418
- (void)cloudSyncOperationWillBegin;	// IMP=0x00000001000203a0
- (void)_initializeStateMachine;	// IMP=0x000000010001d6cc
- (void)networkUpdated:(id)arg1;	// IMP=0x000000010001d5d4
- (_Bool)isiCloudSyncEnabled;	// IMP=0x000000010001d454
- (void)enableCloudSync;	// IMP=0x000000010001d3a8
- (void)disableCloudSync;	// IMP=0x000000010001d2fc
- (void)startSyncingCloudChangesToDevice:(_Bool)arg1;	// IMP=0x000000010001d130
- (void)saveAndStartSyncingDeviceToCloud;	// IMP=0x000000010001cff8
- (void)dealloc;	// IMP=0x000000010001cf70
- (id)init;	// IMP=0x000000010001c7c8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

