//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MPModelTVSeason.h"

@interface MPModelTVSeason (TVMusicAdditions)
- (id)tvm_seasonTitle;	// IMP=0x000000010003f748
@end

