//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVMusicMPRequestViewController.h"

#import "TVCollectionViewDelegate.h"

@class MPModelPlaylist, NSString;

@interface TVMusicLibraryPlaylistsViewController : TVMusicMPRequestViewController <TVCollectionViewDelegate>
{
    MPModelPlaylist *_parentPlaylistFolder;	// 8 = 0x8
}

@property(retain, nonatomic) MPModelPlaylist *parentPlaylistFolder; // @synthesize parentPlaylistFolder=_parentPlaylistFolder;
- (void).cxx_destruct;	// IMP=0x0000000100058050
- (id)cellForItemAtIndexPath:(id)arg1;	// IMP=0x0000000100057ce4
- (void)collectionView:(id)arg1 didReceiveLongPressForItemAtIndexPath:(id)arg2;	// IMP=0x0000000100057bf4
- (_Bool)collectionView:(id)arg1 shouldHandleLongPressForItemAtIndexPath:(id)arg2;	// IMP=0x0000000100057b54
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x00000001000577f0
- (void)_handlePlayPause:(id)arg1;	// IMP=0x000000010005758c
- (void)didMoveToParentViewController:(id)arg1;	// IMP=0x0000000100057580
- (void)viewDidLoad;	// IMP=0x000000010005742c
- (id)init;	// IMP=0x000000010005741c
- (id)initWithParentPlaylistFolder:(id)arg1;	// IMP=0x00000001000572d8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

