//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVMusicLibraryAlbumsViewController.h"

@interface TVMusicLibraryComposerDetailViewController : TVMusicLibraryAlbumsViewController
{
}

- (double)cellsTopMargin;	// IMP=0x0000000100093fd0
- (struct CGPoint)cellSpacing;	// IMP=0x0000000100093fbc
- (struct CGSize)cellSize;	// IMP=0x0000000100093fa8
- (struct CGSize)artworkSize;	// IMP=0x0000000100093f98

@end

