//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TVThemeManager : NSObject
{
}

+ (long long)_userInterfaceStyle;	// IMP=0x00000001000916cc
+ (id)feedNavigationColor;	// IMP=0x0000000100091620
+ (id)feedListItemFocusedColor;	// IMP=0x0000000100091574
+ (id)feedRatingsStarColor;	// IMP=0x00000001000914e0
+ (id)feedPageIndicatorCurrentPageColor;	// IMP=0x0000000100091458
+ (id)feedPageIndicatorColor;	// IMP=0x00000001000913d0
+ (id)feedSubtitleColor;	// IMP=0x0000000100091348
+ (id)feedTitleColor;	// IMP=0x00000001000912c0
+ (id)menuBarButtonHighlightedTextColor;	// IMP=0x0000000100091244
+ (id)menuBarButtonTextColor;	// IMP=0x00000001000911bc
+ (id)_darkModeMetadataLongDescriptionColor;	// IMP=0x0000000100091134
+ (id)_lightModeMetadataLongDescriptionColor;	// IMP=0x00000001000910b0
+ (id)metadataLongDescriptionTextColor;	// IMP=0x0000000100091028
+ (id)_darkModeListItemSelectedOuterStrokeColor;	// IMP=0x0000000100090fa0
+ (id)_lightModeListItemSelectedOuterStrokeColor;	// IMP=0x0000000100090f18
+ (id)listItemSelectedOuterStrokeColor;	// IMP=0x0000000100090e90
+ (id)_darkModeListItemSelectedOverlayFillColor;	// IMP=0x0000000100090df8
+ (id)_lightModeListItemSelectedOverlayFillColor;	// IMP=0x0000000100090d70
+ (id)listItemSelectedOverlayFillColor;	// IMP=0x0000000100090ce8
+ (id)reviewRowTitleTextColor;	// IMP=0x0000000100090c64
+ (id)_darkModeReviewNameTextColor;	// IMP=0x0000000100090bdc
+ (id)_lightModeReviewNameTextColor;	// IMP=0x0000000100090b54
+ (id)reviewNameTextColor;	// IMP=0x0000000100090acc
+ (id)_darkModeReviewTextColor;	// IMP=0x0000000100090a48
+ (id)_lightModeReviewTextColor;	// IMP=0x00000001000909c4
+ (id)reviewTextColor;	// IMP=0x000000010009093c
+ (id)_darkModeReviewScoreTextColor;	// IMP=0x00000001000908b8
+ (id)_lightModeReviewScoreTextColor;	// IMP=0x0000000100090834
+ (id)reviewScoreTextColor;	// IMP=0x00000001000907ac
+ (id)productionTitlesTextColor;	// IMP=0x0000000100090728
+ (id)rowTitleSelectedTextColor;	// IMP=0x00000001000906a0
+ (id)rowTitleTextColor;	// IMP=0x0000000100090618
+ (id)gridItemTextColor;	// IMP=0x0000000100090594
+ (id)folderTitleTextColor;	// IMP=0x000000010009050c
+ (id)listItemSelectedTextColor;	// IMP=0x0000000100090488
+ (id)_darkModeListItemTextColor;	// IMP=0x0000000100090404
+ (id)_lightModeListItemTextColor;	// IMP=0x0000000100090380
+ (id)listItemTextColor;	// IMP=0x00000001000902f8
+ (id)_darkModeListSubheadTextColor;	// IMP=0x0000000100090270
+ (id)_lightModeListSubheadTextColor;	// IMP=0x00000001000901e8
+ (id)imageHeaderSubtitleColor;	// IMP=0x0000000100090160
+ (id)listSubheadTextColor;	// IMP=0x00000001000900d8
+ (id)_darkModeListTitleTextColor;	// IMP=0x0000000100090050
+ (id)_lightModeListTitleTextColor;	// IMP=0x000000010008ffc8
+ (id)listTitleTextColor;	// IMP=0x000000010008ff40
+ (id)fontWithWeight:(id)arg1 fromFont:(id)arg2;	// IMP=0x000000010008fbb8
+ (id)caption2Font;	// IMP=0x000000010008fb30
+ (id)caption1Font;	// IMP=0x000000010008faa8
+ (id)footnoteFont;	// IMP=0x000000010008fa20
+ (id)subheadFont;	// IMP=0x000000010008f998
+ (id)bodyFont;	// IMP=0x000000010008f910
+ (id)calloutFont;	// IMP=0x000000010008f888
+ (id)subtitle3Font;	// IMP=0x000000010008f800
+ (id)subtitle2Font;	// IMP=0x000000010008f778
+ (id)subtitle1Font;	// IMP=0x000000010008f6f0
+ (id)headline3Font;	// IMP=0x000000010008f668
+ (id)headline2Font;	// IMP=0x000000010008f5e0
+ (id)headlineFont;	// IMP=0x000000010008f558
+ (id)title4Font;	// IMP=0x000000010008f4d0
+ (id)title3Font;	// IMP=0x000000010008f448
+ (id)title2Font;	// IMP=0x000000010008f3c0
+ (id)title1Font;	// IMP=0x000000010008f338

@end

