//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class CLSilo;

@interface CLBundleLocationProviderContext : NSObject
{
    struct CLBundleLocationProvider *_provider;	// 8 = 0x8
    CLSilo *_silo;	// 16 = 0x10
}

@property(readonly, nonatomic) CLSilo *silo; // @synthesize silo=_silo;
- (void)invalidate;	// IMP=0x00000001004a0244
@property(readonly, nonatomic) struct CLBundleLocationProvider *provider; // @synthesize provider=_provider;
@property(readonly, nonatomic, getter=isValid) _Bool valid;
- (void)dealloc;	// IMP=0x00000001004a01b4
- (id)initWithBundleLocationProvider:(struct CLBundleLocationProvider *)arg1 inSilo:(id)arg2;	// IMP=0x00000001004a0134

@end

