//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CLNotifierServiceAdapter.h"

#import "CLCatherineNotifierProtocol-Protocol.h"

@class NSString;

@interface CLCatherineNotifierAdapter : CLNotifierServiceAdapter <CLCatherineNotifierProtocol>
{
}

+ (id)getSilo;	// IMP=0x00000001003c9d80
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x00000001003c9d5c
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x00000001003c9cd8
+ (_Bool)isSupported;	// IMP=0x00000001003ca1cc
- (_Bool)syncgetDoSync:(CDUnknownBlockType)arg1;	// IMP=0x00000001003ca190
- (void)doAsync:(CDUnknownBlockType)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x00000001003ca14c
- (void)doAsync:(CDUnknownBlockType)arg1;	// IMP=0x00000001003ca118
- (struct CLCatherineNotifier *)adaptee;	// IMP=0x00000001003ca0e0
- (void)endService;	// IMP=0x00000001003ca0bc
- (void)beginService;	// IMP=0x00000001003c9e44
- (id)init;	// IMP=0x00000001003c9e00

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

