//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CLNotifierServiceAdapter.h"

#import "CLClientManagerProtocol-Protocol.h"

@class NSString;

@interface CLClientManagerAdapter : CLNotifierServiceAdapter <CLClientManagerProtocol>
{
}

+ (id)getSilo;	// IMP=0x0000000100300418
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x00000001003003f4
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x0000000100300370
- (_Bool)syncgetIsMapsANonSystemLocationClient;	// IMP=0x0000000100305aec
- (_Bool)syncgetHasAuthorizedClients;	// IMP=0x00000001003058bc
- (struct CLDaemonClient *)syncgetClientByName:(CDUnknownBlockType)arg1 pid:(int)arg2;	// IMP=0x0000000100305584
- (int)syncgetRegistrationResultToAuthorizationStatus:(int)arg1;	// IMP=0x00000001003053bc
- (int)syncgetClientEffectiveRegistrationResult:(CDUnknownBlockType)arg1;	// IMP=0x00000001003052d4
- (int)syncgetClientStaticRegistrationResult:(CDUnknownBlockType)arg1;	// IMP=0x00000001003051ec
- (id)syncgetNonSystemLocationClientKey;	// IMP=0x0000000100304fdc
- (id)syncgetNonSystemLocationClientKeys;	// IMP=0x0000000100304e68
- (id)syncgetLocationClientKeys;	// IMP=0x0000000100304cf4
- (id)syncgetCopyClients;	// IMP=0x0000000100304bb8
- (void)setPurpose:(id)arg1 forClient:(CDUnknownBlockType)arg2;	// IMP=0x0000000100304974
- (void)setClient:(CDUnknownBlockType)arg1;	// IMP=0x000000010030464c
- (void)resetClients;	// IMP=0x0000000100304630
- (void)setLastLocationSettingsEventSource:(id)arg1;	// IMP=0x0000000100304530
- (void)setClientAuthorization:(CDUnknownBlockType)arg1 status:(int)arg2 entity:(id)arg3;	// IMP=0x0000000100304424
- (void)setClientBackgroundIndicator:(CDUnknownBlockType)arg1 enabled:(_Bool)arg2 entity:(id)arg3;	// IMP=0x00000001003040f4
- (void)performMigration;	// IMP=0x00000001003015e4
- (void)wakeUpLaunchdManagedClient:(id)arg1;	// IMP=0x0000000100301540
- (void)deliverAndReleaseNotification:(struct __CFUserNotification *)arg1 withFlags:(unsigned long long)arg2 callbackState:(struct CLCMNotificationStateRecord *)arg3;	// IMP=0x00000001003014c8
- (void)onCapabilityChange;	// IMP=0x00000001003014ac
- (void)markReceivingLocationInformation:(CDUnknownBlockType)arg1;	// IMP=0x0000000100300fb8
- (void)reduceAccuracy:(id)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100300f30
- (void)takeInUseAssertionForClientKey:(id)arg1 reason:(id)arg2 assertionLevel:(int)arg3 withReply:(CDUnknownBlockType)arg4;	// IMP=0x0000000100300d70
- (void)markClientEmergencyEnablementTransition:(_Bool)arg1;	// IMP=0x0000000100300a34
- (void)setClients:(id)arg1 significantLocationVisitTo:(_Bool)arg2;	// IMP=0x0000000100300980
- (void)setClients:(id)arg1 significantLocationChangeTo:(_Bool)arg2;	// IMP=0x0000000100300914
- (void)setClients:(id)arg1 regionOfType:(int)arg2 to:(_Bool)arg3;	// IMP=0x0000000100300864
- (_Bool)syncgetDoSync:(CDUnknownBlockType)arg1;	// IMP=0x0000000100300828
- (void)doAsync:(CDUnknownBlockType)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x00000001003007e4
- (void)doAsync:(CDUnknownBlockType)arg1;	// IMP=0x00000001003007b0
- (struct CLClientManager *)adaptee;	// IMP=0x0000000100300778
- (void)endService;	// IMP=0x0000000100300754
- (void)beginService;	// IMP=0x00000001003004dc
- (id)init;	// IMP=0x0000000100300498

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

