//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CLSilo.h"

@class NSObject, NSOperationQueue;
@protocol OS_dispatch_queue;

@interface CLDispatchSilo : CLSilo
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    NSOperationQueue *_operationQueue;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x000000010085f178
- (id)debugDescription;	// IMP=0x000000010085f124
- (id)operationQueue;	// IMP=0x000000010085f01c
- (id)queue;	// IMP=0x000000010085f00c
- (void)afterInterval:(double)arg1 async:(CDUnknownBlockType)arg2;	// IMP=0x000000010085efa8
- (void)sync:(CDUnknownBlockType)arg1;	// IMP=0x000000010085ef94
- (void)async:(CDUnknownBlockType)arg1;	// IMP=0x000000010085ef80
- (id)newTimer;	// IMP=0x000000010085eefc
- (void)assertOutside;	// IMP=0x000000010085eeec
- (void)assertInside;	// IMP=0x000000010085eedc
- (id)initMain;	// IMP=0x000000010085ee74
- (id)initWithUnderlyingQueue:(id)arg1;	// IMP=0x000000010085edbc
- (id)initWithIdentifier:(id)arg1;	// IMP=0x000000010085e9b4

@end

