//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSMutableArray, NSMutableDictionary;
@protocol CLIntersiloUniverse, OS_dispatch_queue;

@interface CLFallLoggerManager : NSObject
{
    _Bool fLoggingEnabled;	// 8 = 0x8
    NSMutableDictionary *fLoggers;	// 16 = 0x10
    id <CLIntersiloUniverse> fUniverse;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *fQueue;	// 32 = 0x20
    NSMutableArray *fEventTimes;	// 40 = 0x28
    NSDate *fLastEvent;	// 48 = 0x30
    struct CLGizmoOrientation fOrientation;	// 56 = 0x38
}

+ (id)encodeHeartRate:(const struct CLCatherineData *)arg1;	// IMP=0x00000001007589d0
+ (id)encodePressure:(const FilteredPressure_54a5c05a *)arg1;	// IMP=0x0000000100758970
+ (id)encodeBinaryLog:(const struct BinaryData *)arg1;	// IMP=0x00000001007587d4
+ (id)loggerDataTypeString:(unsigned char)arg1;	// IMP=0x0000000100757d84
+ (unsigned char)loggerDataTypeFrom:(unsigned char)arg1;	// IMP=0x0000000100757d68
@property(nonatomic) struct CLGizmoOrientation orientation; // @synthesize orientation=fOrientation;
@property(nonatomic, getter=isLoggingEnabled, setter=setLoggingEnabled:) _Bool loggingEnabled; // @synthesize loggingEnabled=fLoggingEnabled;
- (void)logHeartRate:(const struct CLCatherineData *)arg1;	// IMP=0x0000000100758f54
- (void)logPressure:(const FilteredPressure_54a5c05a *)arg1;	// IMP=0x0000000100758f10
- (void)logSensorType:(unsigned char)arg1 data:(id)arg2 startTime:(double)arg3 timestamp:(unsigned long long)arg4;	// IMP=0x0000000100758dcc
- (void)logFalsePositiveSuppressionFeatures:(const struct FalsePositiveSuppressionFeatures *)arg1;	// IMP=0x0000000100758d50
- (void)logImpactSensorData:(const struct ImpactData *)arg1;	// IMP=0x0000000100758bd0
- (void)logImpactEventState:(const struct ImpactEvent *)arg1;	// IMP=0x0000000100758b4c
- (void)logImpactEvent:(const struct ImpactEvent *)arg1;	// IMP=0x0000000100758ab8
- (void)_forEachLoggerWithType:(unsigned char)arg1 logItem:(const struct BinaryData *)arg2;	// IMP=0x0000000100758a5c
- (void)_forEachLoggerWithType:(unsigned char)arg1 logData:(id)arg2;	// IMP=0x000000010075860c
- (void)flushData:(CDUnknownBlockType)arg1;	// IMP=0x0000000100758360
- (void)clearAllLogs;	// IMP=0x00000001007582f8
- (void)stopLogging;	// IMP=0x00000001007582a8
- (void)_forEachLogger:(CDUnknownBlockType)arg1;	// IMP=0x0000000100758134
- (id)addLogger:(unsigned char)arg1 toDirectory:(id)arg2 prefix:(id)arg3 rotation:(long long)arg4;	// IMP=0x000000010075808c
- (id)addLogger:(unsigned char)arg1;	// IMP=0x0000000100758004
- (void)_addLogger:(id)arg1 type:(unsigned char)arg2;	// IMP=0x0000000100757f38
- (void)dealloc;	// IMP=0x0000000100757eb8
- (id)initInUniverse:(id)arg1;	// IMP=0x0000000100757dc8

@end

