//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CLNotifierServiceAdapter.h"

#import "CLGyroCalibrationDatabaseProtocol-Protocol.h"

@class NSString;

@interface CLGyroCalibrationDatabaseLocationdAdapter : CLNotifierServiceAdapter <CLGyroCalibrationDatabaseProtocol>
{
}

+ (_Bool)isSupported;	// IMP=0x000000010020ac60
+ (id)getSilo;	// IMP=0x000000010020a888
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x000000010020a864
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x000000010020a7e0
- (int)syncgetNumTemperatures;	// IMP=0x000000010020af50
- (_Bool)syncgetWipeDatabase;	// IMP=0x000000010020af2c
- (void)dumpDatabase:(id)arg1 onCompletion:(CDUnknownBlockType)arg2;	// IMP=0x000000010020aee4
- (_Bool)syncgetInsertWithBias:(const CDStruct_869f9c67 *)arg1 variance:(const CDStruct_869f9c67 *)arg2 temperature:(float)arg3 timestamp:(double)arg4;	// IMP=0x000000010020ae90
- (double)syncgetLastMiniCalibration;	// IMP=0x000000010020ae54
- (_Bool)syncgetSupportsMiniCalibration;	// IMP=0x000000010020ae30
- (int)syncgetNonFactoryRoundCount;	// IMP=0x000000010020ae0c
- (_Bool)syncgetBiasFit:(CDStruct_4d1f5584 *)arg1;	// IMP=0x000000010020add8
- (void)startFactoryGYTT;	// IMP=0x000000010020adb4
- (int)syncgetMaxDynamicTemperature;	// IMP=0x000000010020ad90
- (_Bool)syncgetGyroStatsWithBias:(CDStruct_869f9c67 *)arg1 slope:(CDStruct_869f9c67 *)arg2 l2Error:(CDStruct_869f9c67 *)arg3 isDynamic:(_Bool)arg4 deltaBias:(CDStruct_869f9c67 *)arg5 deltaSlope:(CDStruct_869f9c67 *)arg6 deltaError:(CDStruct_869f9c67 *)arg7 isDeltaDynamic:(_Bool)arg8;	// IMP=0x000000010020acc4
- (_Bool)syncgetDoSync:(CDUnknownBlockType)arg1;	// IMP=0x000000010020ac24
- (void)doAsync:(CDUnknownBlockType)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x000000010020abe0
- (void)doAsync:(CDUnknownBlockType)arg1;	// IMP=0x000000010020abac
- (struct CLGyroCalibrationDatabase *)adaptee;	// IMP=0x000000010020ab74
- (void)endService;	// IMP=0x000000010020ab50
- (void)beginService;	// IMP=0x000000010020a94c
- (id)init;	// IMP=0x000000010020a908

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

