//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSFileHandle, NSString;

@interface CLHRequestArchive : NSObject
{
    NSString *_directory;	// 8 = 0x8
    unsigned int _requestCode;	// 16 = 0x10
    double _rotationInterval;	// 24 = 0x18
    double _lastRotationTime;	// 32 = 0x20
    unsigned long long _count;	// 40 = 0x28
    NSString *_secondaryPath;	// 48 = 0x30
    NSFileHandle *_secondaryFileHandle;	// 56 = 0x38
}

@property(retain, nonatomic) NSFileHandle *secondaryFileHandle; // @synthesize secondaryFileHandle=_secondaryFileHandle;
@property(retain, nonatomic) NSString *secondaryPath; // @synthesize secondaryPath=_secondaryPath;
@property(readonly) unsigned int requestCode; // @synthesize requestCode=_requestCode;
@property(nonatomic) double rotationInterval; // @synthesize rotationInterval=_rotationInterval;
- (id)jsonObject;	// IMP=0x00000001007b06d8
- (void)eraseAllData;	// IMP=0x00000001007b05dc
- (id)primaryFileURL;	// IMP=0x00000001007b04a0
- (id)secondaryFileURLs;	// IMP=0x00000001007b0348
- (id)allFileURLs;	// IMP=0x00000001007b01f4
- (id)fileForSecondaryData;	// IMP=0x00000001007b01b0
- (id)fileForPrimaryData;	// IMP=0x00000001007b0190
- (_Bool)combineAllData;	// IMP=0x00000001007b0018
- (_Bool)combineSecondaryData;	// IMP=0x00000001007afe88
- (void)pruneSecondaryDataSince:(double)arg1;	// IMP=0x00000001007afd34
- (id)mappedSecondaryData;	// IMP=0x00000001007afcb0
- (void)writeSecondaryData:(id)arg1 toField:(unsigned int)arg2;	// IMP=0x00000001007afbf4
- (void)writeSecondaryObject:(id)arg1 toField:(unsigned int)arg2;	// IMP=0x00000001007afbb0
- (void)incrementCountBy:(unsigned long long)arg1;	// IMP=0x00000001007af994
- (void)writePrimaryObject:(id)arg1;	// IMP=0x00000001007af958
- (void)writePrimaryData:(id)arg1;	// IMP=0x00000001007af57c
- (id)mappedData;	// IMP=0x00000001007af4e8
- (unsigned int)secondaryDataSize;	// IMP=0x00000001007af38c
@property(readonly) unsigned long long fileCount;
@property(readonly) unsigned long long count;
- (void)rotateSecondaryFile;	// IMP=0x00000001007af1c0
- (void)dealloc;	// IMP=0x00000001007af0cc
- (id)initWithDirectory:(id)arg1 requestCode:(int)arg2;	// IMP=0x00000001007aedfc
- (id)initWithDirectory:(id)arg1;	// IMP=0x00000001007aedec
- (id)init;	// IMP=0x00000001007aedac

@end

