//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CLIntersiloProxy.h"

@interface CLIntersiloProxyToInitiator : CLIntersiloProxy
{
    CLIntersiloProxy *_peer;	// 8 = 0x8
}

@property(readonly, nonatomic) __weak CLIntersiloProxy *peer; // @synthesize peer=_peer;
- (void).cxx_destruct;	// IMP=0x0000000100861ec8
- (id)initWithDelegateObject:(id)arg1 delegateSilo:(id)arg2 uninitializedPeer:(id)arg3;	// IMP=0x0000000100861dec

@end

