//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSNumber;

@protocol CLLocationSmootherServerInterface <NSObject>

@optional
- (void)smoothLocations:(NSArray *)arg1 handler:(void (^)(NSArray *, NSError *))arg2;
- (void)smoothLocations:(NSArray *)arg1 useType:(NSNumber *)arg2;
@end

