//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CLIntersiloService.h"

#import "CLLocationStreamingConnectionManagerServiceProtocol-Protocol.h"
#import "IDSServiceDelegate-Protocol.h"

@class IDSService, NSMutableDictionary, NSMutableSet, NSString;

@interface CLLocationStreamingConnectionManager : CLIntersiloService <IDSServiceDelegate, CLLocationStreamingConnectionManagerServiceProtocol>
{
    _Bool _pairIsNearby;	// 8 = 0x8
    IDSService *_service;	// 16 = 0x10
    NSMutableDictionary *_unacknowledgedMessages;	// 24 = 0x18
    NSMutableSet *_clients;	// 32 = 0x20
}

+ (_Bool)isSupported;	// IMP=0x00000001001aa040
+ (id)getSilo;	// IMP=0x00000001001a9fc0
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x00000001001a9f9c
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x00000001001a9f18
@property(nonatomic) _Bool pairIsNearby; // @synthesize pairIsNearby=_pairIsNearby;
@property(retain, nonatomic) NSMutableSet *clients; // @synthesize clients=_clients;
@property(retain, nonatomic) NSMutableDictionary *unacknowledgedMessages; // @synthesize unacknowledgedMessages=_unacknowledgedMessages;
@property(retain, nonatomic) IDSService *service; // @synthesize service=_service;
- (void)service:(id)arg1 nearbyDevicesChanged:(id)arg2;	// IMP=0x00000001001ab5f4
- (void)service:(id)arg1 account:(id)arg2 identifier:(id)arg3 didSendWithSuccess:(_Bool)arg4 error:(id)arg5;	// IMP=0x00000001001ab0d4
- (void)service:(id)arg1 account:(id)arg2 incomingMessage:(id)arg3 fromID:(id)arg4 context:(id)arg5;	// IMP=0x00000001001aaccc
- (void)withClients:(CDUnknownBlockType)arg1;	// IMP=0x00000001001aaba0
- (void)sendMessage:(id)arg1;	// IMP=0x00000001001aa670
- (void)retireClient:(byref id)arg1;	// IMP=0x00000001001aa620
- (void)addClient:(byref id)arg1;	// IMP=0x00000001001aa5b4
- (void)updateNearbyStatusWithDevices:(id)arg1;	// IMP=0x00000001001aa328
- (_Bool)isRemoteWatchStreamingCompatible;	// IMP=0x00000001001aa2c0
- (void)endService;	// IMP=0x00000001001aa254
- (void)beginService;	// IMP=0x00000001001aa0f8
- (id)init;	// IMP=0x00000001001aa0b4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

