//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CLIntersiloServiceProtocol-Protocol.h"

@class CLLocation, NSDate, NSString;
@protocol CLRoutineMonitorClientProtocol;

@protocol CLRoutineMonitorServiceProtocol <CLIntersiloServiceProtocol>
- (void)stopMonitoringScenarioTriggerOfType:(unsigned long long)arg1 forClient:(byref id <CLRoutineMonitorClientProtocol>)arg2;
- (void)startMonitoringScenarioTriggerOfType:(unsigned long long)arg1 forClient:(byref id <CLRoutineMonitorClientProtocol>)arg2;
- (void)fetchLocationOfInterestAtLocation:(CLLocation *)arg1 withHandler:(void (^)(RTLocationOfInterest *, NSError *))arg2;
- (void)stopLeechingLowConfidenceVisitsForClient:(byref id <CLRoutineMonitorClientProtocol>)arg1;
- (void)startLeechingLowConfidenceVisitsForClient:(byref id <CLRoutineMonitorClientProtocol>)arg1;
- (void)stopLeechingVisitsForClient:(byref id <CLRoutineMonitorClientProtocol>)arg1;
- (void)startLeechingVisitsForClient:(byref id <CLRoutineMonitorClientProtocol>)arg1;
- (void)stopMonitoringVisitsForClient:(byref id <CLRoutineMonitorClientProtocol>)arg1;
- (void)startMonitoringVisitsForClient:(byref id <CLRoutineMonitorClientProtocol>)arg1;
- (void)fetchPredictedLocationsOfInterestBetweenStartDate:(NSDate *)arg1 endDate:(NSDate *)arg2 withReply:(void (^)(NSArray *, NSError *))arg3;
- (void)fetchPredictedLocationsOfInterestOnDate:(NSDate *)arg1 withReply:(void (^)(NSArray *, NSError *))arg2;
- (void)fetchNextPredictedLocationsOfInterestFromLocation:(CLLocation *)arg1 startDate:(NSDate *)arg2 timeInterval:(double)arg3 withReply:(void (^)(NSArray *, NSError *))arg4;
- (void)fetchRecentLocationsOfInterestWithReply:(void (^)(NSArray *, NSError *))arg1;
- (void)fetchLocationsOfInterestOfType:(long long)arg1 withReply:(void (^)(NSArray *, NSError *))arg2;
- (void)fetchLocationsOfInterestWithinDistance:(double)arg1 ofLocation:(CLLocation *)arg2 withReply:(void (^)(NSArray *, NSError *))arg3;
- (void)fetchLocationsOfInterestAssociatedToIdentifier:(NSString *)arg1 withReply:(void (^)(NSArray *, NSError *))arg2;
- (void)fetchRoutineModeFromLocation:(CLLocation *)arg1 withReply:(void (^)(long long, NSError *))arg2;
@end

