//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CLIntersiloService.h"

#import "CLStatusBarIconManagerProtocol-Protocol.h"

@class NSString;

@interface CLStatusBarIconManagerAdapter : CLIntersiloService <CLStatusBarIconManagerProtocol>
{
    struct CLStatusBarIconManager *_manager;	// 8 = 0x8
}

+ (_Bool)isSupported;	// IMP=0x00000001005c8a84
+ (id)getSilo;	// IMP=0x00000001005c8930
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x00000001005c890c
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x00000001005c8888
@property(nonatomic) struct CLStatusBarIconManager *manager; // @synthesize manager=_manager;
- (void)entityClass:(unsigned int)arg1 didUpdateActiveServices:(unsigned int)arg2 dueToDeauthorization:(_Bool)arg3;	// IMP=0x00000001005c9114
- (void)setE911Active:(_Bool)arg1;	// IMP=0x00000001005c9094
- (void)setStatusBarIconForEntityClass:(int)arg1 visible:(_Bool)arg2;	// IMP=0x00000001005c8d34
- (_Bool)syncgetStatusBarIconForEntityClass:(int)arg1;	// IMP=0x00000001005c8cd0
- (int)syncgetIconState;	// IMP=0x00000001005c8a8c
- (void)endService;	// IMP=0x00000001005c8a5c
- (void)beginService;	// IMP=0x00000001005c89f4
- (id)init;	// IMP=0x00000001005c89b0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

