//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CLLocationProviderAdapter.h"

#import "CLRemoteMotionAlarmClientProtocol-Protocol.h"
#import "CLStreamingAwareLocationProviderProtocol-Protocol.h"

@class NSString;

@interface CLStreamingAwareLocationProviderAdapter : CLLocationProviderAdapter <CLRemoteMotionAlarmClientProtocol, CLStreamingAwareLocationProviderProtocol>
{
}

+ (id)getSilo;	// IMP=0x00000001005cc49c
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x00000001005cc478
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x00000001005cc3f4
- (void)remoteDeviceMotionUpdate:(int)arg1 atTime:(double)arg2;	// IMP=0x00000001005ccc58
- (void)releaseAccuracyEnablementAssertionForClient:(byref id)arg1;	// IMP=0x00000001005ccac0
- (void)takeAccuracyEnablementAssertionForClient:(byref id)arg1 withDesiredAccuracy:(double)arg2;	// IMP=0x00000001005cc8e8
- (_Bool)syncgetDoSync:(CDUnknownBlockType)arg1;	// IMP=0x00000001005cc8ac
- (void)doAsync:(CDUnknownBlockType)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x00000001005cc868
- (void)doAsync:(CDUnknownBlockType)arg1;	// IMP=0x00000001005cc834
- (struct CLStreamingAwareLocationProvider *)adaptee;	// IMP=0x00000001005cc7fc
- (void)endService;	// IMP=0x00000001005cc7d8
- (void)beginService;	// IMP=0x00000001005cc560
- (id)init;	// IMP=0x00000001005cc51c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

