//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CLLocationProviderAdapter.h"

#import "CLLocationStreamingConnectionManagerClientProtocol-Protocol.h"
#import "CLStreamedLocationProviderProtocol-Protocol.h"

@class NSString;

@interface CLStreamedLocationProviderAdapter : CLLocationProviderAdapter <CLLocationStreamingConnectionManagerClientProtocol, CLStreamedLocationProviderProtocol>
{
}

+ (_Bool)isSupported;	// IMP=0x000000010013d0c4
+ (id)getSilo;	// IMP=0x000000010013cc78
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x000000010013cc54
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x000000010013cbd0
- (void)pairedDeviceIsNearby:(_Bool)arg1;	// IMP=0x000000010013dd98
- (void)successfullySentMessage:(id)arg1;	// IMP=0x000000010013dd94
- (void)failedToSendMessage:(id)arg1 withError:(id)arg2 isFatal:(_Bool)arg3;	// IMP=0x000000010013dd90
- (void)receivedMessageOfType:(id)arg1 withPayload:(id)arg2;	// IMP=0x000000010013dc7c
- (void)releaseEmergencyEnablementAssertion;	// IMP=0x000000010013d9e0
- (void)takeEmergencyEnablementAssertion;	// IMP=0x000000010013d748
- (void)releaseDisablementAssertion;	// IMP=0x000000010013d43c
- (void)takeDisablementAssertion;	// IMP=0x000000010013d12c
- (_Bool)syncgetDoSync:(CDUnknownBlockType)arg1;	// IMP=0x000000010013d088
- (void)doAsync:(CDUnknownBlockType)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x000000010013d044
- (void)doAsync:(CDUnknownBlockType)arg1;	// IMP=0x000000010013d010
- (struct CLStreamedLocationProvider *)adaptee;	// IMP=0x000000010013cfd8
- (void)endService;	// IMP=0x000000010013cfb4
- (void)beginService;	// IMP=0x000000010013cd3c
- (id)init;	// IMP=0x000000010013ccf8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

