//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CLNotifierServiceAdapter.h"

#import "CLTelephonyServiceProtocol-Protocol.h"

@class NSString;

@interface CLTelephonyServiceAdapter : CLNotifierServiceAdapter <CLTelephonyServiceProtocol>
{
}

+ (id)getSilo;	// IMP=0x00000001001c4770
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x00000001001c474c
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x00000001001c46c8
+ (_Bool)isSupported;	// IMP=0x00000001001caccc
- (void)sendNotificationToClients:(id)arg1 notificationData:(id)arg2;	// IMP=0x00000001001cacc8
- (_Bool)syncgetServingCdmaCell:(struct CdmaCell *)arg1;	// IMP=0x00000001001ca8b4
- (_Bool)syncgetServingGsmCell:(struct Cell *)arg1;	// IMP=0x00000001001ca81c
- (_Bool)syncgetServingCells:(vector_096a3675 *)arg1 addNeighborCells:(_Bool)arg2;	// IMP=0x00000001001c9e04
- (void)dumpLogWithReason:(id)arg1;	// IMP=0x00000001001c9adc
- (void)resetModemWithReason:(id)arg1;	// IMP=0x00000001001c96c0
- (_Bool)syncgetSignalStrength:(int *)arg1;	// IMP=0x00000001001c93d0
- (_Bool)syncgetCopyPhoneNumber:(id *)arg1;	// IMP=0x00000001001c902c
- (_Bool)syncgetCopyIMEI:(id *)arg1;	// IMP=0x00000001001c8af8
- (_Bool)syncgetCopyIMSI:(id *)arg1;	// IMP=0x00000001001c8764
- (_Bool)syncgetCopyServingProviderFromCarrierBundle:(id *)arg1;	// IMP=0x00000001001c83d0
- (_Bool)syncgetCopyServingProvider:(id *)arg1;	// IMP=0x00000001001c8320
- (_Bool)syncgetCopyServingOperatorAbbreviated:(id *)arg1;	// IMP=0x00000001001c8270
- (_Bool)syncgetCopyServingOperator:(id *)arg1;	// IMP=0x00000001001c7edc
- (_Bool)syncgetRefreshCellMonitor;	// IMP=0x00000001001c7ebc
- (_Bool)syncgetActiveEmergencyCall:(_Bool *)arg1;	// IMP=0x00000001001c7adc
- (_Bool)syncgetActiveCall:(_Bool *)arg1;	// IMP=0x00000001001c7a9c
- (_Bool)syncgetLastKnownServingMCC:(int *)arg1;	// IMP=0x00000001001c7a68
- (_Bool)syncgetLastKnownSubscriberMCC:(int *)arg1;	// IMP=0x00000001001c7758
- (int)syncgetCellTransmitStatus;	// IMP=0x00000001001c76f4
- (int)syncgetRegistrationStatus;	// IMP=0x00000001001c75c8
- (int)syncgetRadioAccessTechnology;	// IMP=0x00000001001c7578
- (_Bool)syncgetIsRegisteredOnCell;	// IMP=0x00000001001c7554
- (_Bool)syncgetDetectedCells:(vector_096a3675 *)arg1;	// IMP=0x00000001001c6a44
- (void)queryForCtclNotification:(const struct __CFString *)arg1;	// IMP=0x00000001001c69d4
- (id)syncgetRegistrationInfoDictionary;	// IMP=0x00000001001c6818
- (_Bool)syncgetTrackedCellsCount:(unsigned int *)arg1;	// IMP=0x00000001001c65ec
- (_Bool)syncgetUplinkFrequency:(float *)arg1 andBandwidth:(float *)arg2;	// IMP=0x00000001001c65ac
- (void)disableWakeOnCellChange;	// IMP=0x00000001001c645c
- (void)enableWakeOnCellChange;	// IMP=0x00000001001c62fc
- (_Bool)syncgetCellTrackingLimit:(unsigned int *)arg1;	// IMP=0x00000001001c618c
- (_Bool)syncgetCellTrackingStatus:(_Bool *)arg1;	// IMP=0x00000001001c614c
- (_Bool)syncgetStopTrackingCells:(vector_096a3675 *)arg1;	// IMP=0x00000001001c611c
- (_Bool)syncgetStartTrackingCells:(vector_096a3675 *)arg1;	// IMP=0x00000001001c60ec
- (_Bool)syncgetTrackedCells:(vector_096a3675 *)arg1;	// IMP=0x00000001001c5c58
- (_Bool)syncgetIsCellTrackingSupported;	// IMP=0x00000001001c5c30
- (_Bool)syncgetIsCellTrackingEnabled;	// IMP=0x00000001001c59fc
- (void)assertCommCenter:(int)arg1 with:(int)arg2;	// IMP=0x00000001001c5880
- (void)disableCellTracking;	// IMP=0x00000001001c5668
- (void)enableCellTracking;	// IMP=0x00000001001c5450
- (_Bool)syncgetCampOnlyState;	// IMP=0x00000001001c50c0
- (void)requestCamping:(_Bool)arg1;	// IMP=0x00000001001c4f1c
- (void)fetchActiveOrHeldWithReply:(CDUnknownBlockType)arg1;	// IMP=0x00000001001c4bfc
- (void)fetchIsCellAvailableWithReply:(CDUnknownBlockType)arg1;	// IMP=0x00000001001c4bbc
- (_Bool)syncgetDoSync:(CDUnknownBlockType)arg1;	// IMP=0x00000001001c4b80
- (void)doAsync:(CDUnknownBlockType)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x00000001001c4b3c
- (void)doAsync:(CDUnknownBlockType)arg1;	// IMP=0x00000001001c4b08
- (struct CLTelephonyService *)adaptee;	// IMP=0x00000001001c4ad0
- (void)endService;	// IMP=0x00000001001c4aac
- (void)beginService;	// IMP=0x00000001001c4834
- (id)init;	// IMP=0x00000001001c47f0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

