//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class CLTimer;

@protocol CLTimerScheduler
@property(nonatomic) __weak CLTimer *timer;
- (void)reflectNextFireTime:(double)arg1 fireInterval:(double)arg2;
@end

