//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class CLSilo;
@protocol CLTimerScheduler;

@interface CLTimer : NSObject
{
    CLSilo *_silo;	// 8 = 0x8
    id <CLTimerScheduler> _scheduler;	// 16 = 0x10
    CDUnknownBlockType _handler;	// 24 = 0x18
    double _nextFireTime;	// 32 = 0x20
    double _fireInterval;	// 40 = 0x28
}

@property(nonatomic) double fireInterval; // @synthesize fireInterval=_fireInterval;
@property(nonatomic) double nextFireTime; // @synthesize nextFireTime=_nextFireTime;
@property(copy, nonatomic) CDUnknownBlockType handler; // @synthesize handler=_handler;
- (void).cxx_destruct;	// IMP=0x00000001001a737c
- (void)shouldFire;	// IMP=0x00000001001a70fc
- (void)invalidate;	// IMP=0x00000001001a7090
- (void)setNextFireTime:(double)arg1 interval:(double)arg2;	// IMP=0x00000001001a7010
- (void)setNextFireAfterDelay:(double)arg1 interval:(double)arg2;	// IMP=0x00000001001a6f80
- (void)setNextFireAfterDelay:(double)arg1;	// IMP=0x00000001001a6e4c
- (id)initInSilo:(id)arg1 withScheduler:(id)arg2;	// IMP=0x00000001001a6d34
- (void)updateScheduler;	// IMP=0x00000001001a6d00

@end

