//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSData, NSNumber, NSString, NSUUID;

@interface CLWPZone : NSObject <NSCopying>
{
    NSUUID *_proximityUUID;	// 8 = 0x8
    NSNumber *_major;	// 16 = 0x10
    NSNumber *_minor;	// 24 = 0x18
    NSString *_identifier;	// 32 = 0x20
    NSData *_advertisementData;	// 40 = 0x28
}

@property(readonly, retain) NSData *advertisementData; // @synthesize advertisementData=_advertisementData;
@property(readonly, copy) NSString *identifier; // @synthesize identifier=_identifier;
@property(readonly, copy) NSNumber *minor; // @synthesize minor=_minor;
@property(readonly, copy) NSNumber *major; // @synthesize major=_major;
@property(readonly, copy) NSUUID *proximityUUID; // @synthesize proximityUUID=_proximityUUID;
- (_Bool)isEqual:(id)arg1;	// IMP=0x00000001007e842c
- (unsigned long long)hash;	// IMP=0x00000001007e8414
- (id)description;	// IMP=0x00000001007e8404
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001007e83f8
- (void)dealloc;	// IMP=0x00000001007e8330
- (id)initWithProximityUUID:(id)arg1 major:(id)arg2 minor:(id)arg3 identifier:(id)arg4;	// IMP=0x00000001007e815c

@end

