//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface CMStrideCalibrationStepCountBuffer : NSObject
{
    struct queue<std::__1::pair<double, unsigned int>, std::__1::deque<std::__1::pair<double, unsigned int>, std::__1::allocator<std::__1::pair<double, unsigned int>>>> fStepWindow;	// 8 = 0x8
}

- (id).cxx_construct;	// IMP=0x00000001001710ac
- (void).cxx_destruct;	// IMP=0x000000010017109c
- (void)feedStepCountUpdate:(const union NotificationData *)arg1;	// IMP=0x0000000100171014
- (unsigned int)stepsInWindow;	// IMP=0x0000000100170fb8
- (void)ageOutStepArray;	// IMP=0x0000000100170f34

@end

