//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class CalTrackFinder;
@protocol CMStrideCalLocationFSMDelegate;

@interface CMStrideCalLocationFSM : NSObject
{
    int fLocationState;	// 8 = 0x8
    CalTrackFinder *fTrackFinder;	// 16 = 0x10
    int fSource;	// 24 = 0x18
    id <CMStrideCalLocationFSMDelegate> _delegate;	// 32 = 0x20
}

@property(nonatomic) id <CMStrideCalLocationFSMDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) int locationState; // @synthesize locationState=fLocationState;
- (void)feedPedometerData:(const union NotificationData *)arg1;	// IMP=0x000000010053f908
- (void)feedGpsOdometerData:(const union NotificationData *)arg1;	// IMP=0x000000010053f890
- (void)feedLocationData:(const struct NotificationData *)arg1;	// IMP=0x000000010053f6dc
- (int)originDeviceToGpsSource:(int)arg1 locationType:(int)arg2;	// IMP=0x000000010053f640
- (void)requestTransitionToLocationState:(int)arg1;	// IMP=0x000000010053f378
- (void)dealloc;	// IMP=0x000000010053f310

@end

