//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@interface TRANSITPbLocationFingerprint : PBCodable <NSCopying>
{
    struct {
        unsigned long long *list;
        unsigned long long count;
        unsigned long long size;
    } _macs;	// 8 = 0x8
    struct {
        double *list;
        unsigned long long count;
        unsigned long long size;
    } _modes;	// 32 = 0x20
    double _latitude;	// 56 = 0x38
    unsigned long long _locationId;	// 64 = 0x40
    double _longitude;	// 72 = 0x48
    struct {
        unsigned int latitude:1;
        unsigned int locationId:1;
        unsigned int longitude:1;
    } _has;	// 80 = 0x50
}

@property(nonatomic) double longitude; // @synthesize longitude=_longitude;
@property(nonatomic) double latitude; // @synthesize latitude=_latitude;
@property(nonatomic) unsigned long long locationId; // @synthesize locationId=_locationId;
- (void)mergeFrom:(id)arg1;	// IMP=0x000000010045cdec
- (unsigned long long)hash;	// IMP=0x000000010045ccb8
- (_Bool)isEqual:(id)arg1;	// IMP=0x000000010045cbb4
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010045cabc
- (void)copyTo:(id)arg1;	// IMP=0x000000010045c918
- (void)writeTo:(id)arg1;	// IMP=0x000000010045c804
- (_Bool)readFrom:(id)arg1;	// IMP=0x000000010045c7fc
- (id)dictionaryRepresentation;	// IMP=0x000000010045c0d0
- (id)description;	// IMP=0x000000010045c050
- (void)setModes:(double *)arg1 count:(unsigned long long)arg2;	// IMP=0x000000010045c038
- (double)modesAtIndex:(unsigned long long)arg1;	// IMP=0x000000010045bf90
- (void)addModes:(double)arg1;	// IMP=0x000000010045bf80
- (void)clearModes;	// IMP=0x000000010045bf70
@property(readonly, nonatomic) double *modes;
@property(readonly, nonatomic) unsigned long long modesCount;
- (void)setMacs:(unsigned long long *)arg1 count:(unsigned long long)arg2;	// IMP=0x000000010045bf34
- (unsigned long long)macsAtIndex:(unsigned long long)arg1;	// IMP=0x000000010045be8c
- (void)addMacs:(unsigned long long)arg1;	// IMP=0x000000010045be78
- (void)clearMacs;	// IMP=0x000000010045be68
@property(readonly, nonatomic) unsigned long long *macs;
@property(readonly, nonatomic) unsigned long long macsCount;
@property(nonatomic) _Bool hasLongitude;
@property(nonatomic) _Bool hasLatitude;
@property(nonatomic) _Bool hasLocationId;
- (void)dealloc;	// IMP=0x000000010045bce8

@end

