//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSString, NSURL;

@interface TVIUserDefaults : NSObject
{
}

+ (id)sharedInstance;	// IMP=0x0000000100010f98
@property(readonly, nonatomic) NSString *initialPlaybackAssetIdentifier;
@property(readonly, nonatomic) NSURL *customerMetadataURL;
@property(readonly, nonatomic) NSNumber *refreshTimeInterval;
@property(readonly, nonatomic) _Bool shouldFadeToBlackOnPause;
@property(readonly, nonatomic) _Bool isInteractionEnabled;

@end

