//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVPURLMediaItem.h"

@class NSDictionary;

@interface TVPURLMediaItem (TVIMediaItemMetadata)
@property(retain, nonatomic) NSDictionary *filmingLocations;
@property(retain, nonatomic) NSDictionary *pointsOfInterest;
@property(readonly, nonatomic) _Bool hasLocationData;
@end

