//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBSDisplayMode.h"

@interface PBSDisplayMode (TVSettingsDisplayModeFacade)
- (_Bool)tvs_isEqualResolutionAndRefreshRate:(id)arg1;	// IMP=0x0000000100095ec8
- (_Bool)tvs_isCommonResolutionByShowing4KModes:(_Bool)arg1;	// IMP=0x0000000100095df8
@end

