//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CastleRequest.h"

@interface QuotaInfoRequest : CastleRequest
{
}

+ (Class)responseClass;	// IMP=0x000000010008af00
- (id)urlRequest;	// IMP=0x000000010008b140
- (id)initWithAccount:(id)arg1;	// IMP=0x000000010008af14

@end

