//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, TVSPreferences;

@interface TVSettingsPreferenceFacade : NSObject
{
    TVSPreferences *_prefs;	// 8 = 0x8
    NSString *_domain;	// 16 = 0x10
    NSString *_containerPath;	// 24 = 0x18
}

@property(readonly, copy, nonatomic) NSString *containerPath; // @synthesize containerPath=_containerPath;
@property(readonly, copy, nonatomic) NSString *domain; // @synthesize domain=_domain;
- (void).cxx_destruct;	// IMP=0x000000010001854c
- (id)valueForUndefinedKey:(id)arg1;	// IMP=0x00000001000184d0
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;	// IMP=0x0000000100018388
- (id)_initWithDomain:(id)arg1 containerPath:(id)arg2 notifyChanges:(_Bool)arg3;	// IMP=0x0000000100018234
- (id)initWithDomain:(id)arg1 notifyChanges:(_Bool)arg2;	// IMP=0x0000000100018220
- (id)initWithDomain:(id)arg1 containerPath:(id)arg2;	// IMP=0x00000001000181c0

@end

