//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TSKViewController.h"

#import "TVSettingsPhotoCollectionViewControllerSelectionDelegate.h"

@class NSString, TVPhotoCollectionGroup, TVSettingsPhotoCollectionPreviewViewController, UIVisualEffectView;

@interface TVSettingsPhotoCollectionGroupViewController : TSKViewController <TVSettingsPhotoCollectionViewControllerSelectionDelegate>
{
    UIVisualEffectView *_backdropView;	// 8 = 0x8
    id <TVSettingsPhotoCollectionGroupViewControllerDelegate> _delegate;	// 16 = 0x10
    TVPhotoCollectionGroup *_photoCollectionGroup;	// 24 = 0x18
    TVSettingsPhotoCollectionPreviewViewController *_photoPreviewController;	// 32 = 0x20
}

@property(retain, nonatomic) TVSettingsPhotoCollectionPreviewViewController *photoPreviewController; // @synthesize photoPreviewController=_photoPreviewController;
@property(retain, nonatomic) TVPhotoCollectionGroup *photoCollectionGroup; // @synthesize photoCollectionGroup=_photoCollectionGroup;
@property(nonatomic) __weak id <TVSettingsPhotoCollectionGroupViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x00000001000c6400
- (void)_updatePhotoCollectionWithIndexPath:(id)arg1;	// IMP=0x00000001000c626c
- (id)_localizedTitleForPhotoCollection:(id)arg1;	// IMP=0x00000001000c6120
- (void)controller:(id)arg1 didSelectAsset:(id)arg2;	// IMP=0x00000001000c6024
- (_Bool)hasFullscreenPreview;	// IMP=0x00000001000c601c
- (id)previewForItemAtIndexPath:(id)arg1;	// IMP=0x00000001000c5fe8
- (id)title;	// IMP=0x00000001000c5fe0
- (id)loadSettingGroups;	// IMP=0x00000001000c5c70
- (void)viewDidLoad;	// IMP=0x00000001000c54dc
- (id)initWithPhotoCollectionGroup:(id)arg1;	// IMP=0x00000001000c53e8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

