//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewHeaderFooterView.h"

@class UIActivityIndicatorView;

@interface TVSettingsChooseNetworkHeaderView : UITableViewHeaderFooterView
{
    _Bool _animating;	// 8 = 0x8
    UIActivityIndicatorView *_spinnerView;	// 16 = 0x10
}

@property(retain, nonatomic) UIActivityIndicatorView *spinnerView; // @synthesize spinnerView=_spinnerView;
@property(readonly, nonatomic, getter=isAnimating) _Bool animating; // @synthesize animating=_animating;
- (void).cxx_destruct;	// IMP=0x000000010009e1d0

@end

