//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TSKViewController.h"

@interface TVSettingsScreenSaverViewController : TSKViewController
{
}

- (void)_updateStartDelayItem:(id)arg1 value:(id)arg2;	// IMP=0x000000010001dad0
- (void)_showPreview:(id)arg1;	// IMP=0x000000010001da88
- (void)_selectStyleAndShowTransitionsMenu:(id)arg1;	// IMP=0x000000010001d94c
- (void)_selectStyle:(id)arg1;	// IMP=0x000000010001d8dc
- (void)_playButtonPressed:(id)arg1;	// IMP=0x000000010001d830
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000010001d76c
- (id)loadSettingGroups;	// IMP=0x000000010001c9cc
- (void)dealloc;	// IMP=0x000000010001c918
- (id)initWithStyle:(long long)arg1;	// IMP=0x000000010001c854

@end

