//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class TVSettingsImageView;

@interface TVSettingsRegulatoryViewController : UIViewController
{
    TVSettingsImageView *_imageView;	// 8 = 0x8
}

@property(retain, nonatomic) TVSettingsImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;	// IMP=0x0000000100053bd8
- (id)_regulatoryImageForUserInterfaceStyle:(long long)arg1;	// IMP=0x0000000100053a74
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x0000000100053968
- (void)viewDidLayoutSubviews;	// IMP=0x0000000100053818
- (void)viewDidLoad;	// IMP=0x00000001000536b0

@end

