//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TSKViewController.h"

@interface TVSettingsScreenSaverTransitionsViewController : TSKViewController
{
}

+ (id)transitionTypeFormatter;	// IMP=0x000000010005d048
- (id)loadSettingGroups;	// IMP=0x000000010005cbcc

@end

