//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, NSTimer, UIImageView, _TVSettingsImageLoaderQueue;

@interface TVSettingsLegacyImageCrossfadeView : UIView
{
    NSArray *_imageProxies;	// 8 = 0x8
    double _crossfadePeriod;	// 16 = 0x10
    double _crossfadeDuration;	// 24 = 0x18
    double _rotationAngleDegrees;	// 32 = 0x20
    _TVSettingsImageLoaderQueue *_loaderQueue;	// 40 = 0x28
    UIImageView *_imageView;	// 48 = 0x30
    NSTimer *_crossfadeTimer;	// 56 = 0x38
}

@property(retain, nonatomic) NSTimer *crossfadeTimer; // @synthesize crossfadeTimer=_crossfadeTimer;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) _TVSettingsImageLoaderQueue *loaderQueue; // @synthesize loaderQueue=_loaderQueue;
@property(nonatomic) double rotationAngleDegrees; // @synthesize rotationAngleDegrees=_rotationAngleDegrees;
@property(nonatomic) double crossfadeDuration; // @synthesize crossfadeDuration=_crossfadeDuration;
@property(nonatomic) double crossfadePeriod; // @synthesize crossfadePeriod=_crossfadePeriod;
@property(copy, nonatomic) NSArray *imageProxies; // @synthesize imageProxies=_imageProxies;
- (void).cxx_destruct;	// IMP=0x0000000100019234
- (void)_crossfadeToImage:(id)arg1;	// IMP=0x0000000100018f64
- (void)_loadNextImage:(id)arg1;	// IMP=0x0000000100018ebc
- (void)_startTimer;	// IMP=0x0000000100018e04
- (struct CGSize)_maximumImageSize;	// IMP=0x0000000100018dbc
- (void)layoutSubviews;	// IMP=0x0000000100018764
- (void)didMoveToSuperview;	// IMP=0x00000001000186fc
- (void)dealloc;	// IMP=0x00000001000186a4
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000185a0

@end

