//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TSKViewController.h"

#import "TSKOpenViaURLViewControllerProtocol.h"

@class NSString, TSKPreviewViewController, TSKSettingItem, TVSettingsUsageFacade;

@interface TVSettingsLocalStorageViewController : TSKViewController <TSKOpenViaURLViewControllerProtocol>
{
    _Bool _displayQuotaExceededIfNeeded;	// 8 = 0x8
    TSKSettingItem *_lastFocusedItem;	// 16 = 0x10
    TSKPreviewViewController *_appIconPreviewViewController;	// 24 = 0x18
    TVSettingsUsageFacade *_usageFacade;	// 32 = 0x20
    NSString *_quotaMessage;	// 40 = 0x28
}

@property(nonatomic) _Bool displayQuotaExceededIfNeeded; // @synthesize displayQuotaExceededIfNeeded=_displayQuotaExceededIfNeeded;
@property(retain, nonatomic) NSString *quotaMessage; // @synthesize quotaMessage=_quotaMessage;
@property(retain, nonatomic) TVSettingsUsageFacade *usageFacade; // @synthesize usageFacade=_usageFacade;
@property(retain, nonatomic) TSKPreviewViewController *appIconPreviewViewController; // @synthesize appIconPreviewViewController=_appIconPreviewViewController;
@property(retain, nonatomic) TSKSettingItem *lastFocusedItem; // @synthesize lastFocusedItem=_lastFocusedItem;
- (void).cxx_destruct;	// IMP=0x0000000100063d5c
- (id)_byteCountFormatter;	// IMP=0x0000000100063c7c
- (void)_updateQuotaMessage;	// IMP=0x0000000100063900
- (void)_showDeleteConfirmationForItem:(id)arg1;	// IMP=0x00000001000633f0
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x0000000100063338
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;	// IMP=0x00000001000630e4
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;	// IMP=0x00000001000630dc
- (id)previewForItemAtIndexPath:(id)arg1;	// IMP=0x0000000100062dec
- (id)title;	// IMP=0x0000000100062d7c
- (id)loadSettingGroups;	// IMP=0x0000000100062998
- (void)dealloc;	// IMP=0x000000010006292c
- (void)viewDidLoad;	// IMP=0x0000000100062858
- (void)displayTriggeredByURL:(id)arg1;	// IMP=0x0000000100062830
- (id)initWithStyle:(long long)arg1;	// IMP=0x00000001000625fc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

