//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface TVSettingsDiagnosticLogsFacade : NSObject
{
    NSArray *_logFilePaths;	// 8 = 0x8
}

+ (id)textForTableName:(id)arg1 inPowerLog:(id)arg2;	// IMP=0x000000010008e274
+ (id)tableNamesForPowerLog:(id)arg1;	// IMP=0x000000010008e1c0
+ (_Bool)filePathIsSysdiagnose:(id)arg1;	// IMP=0x000000010008e168
+ (_Bool)filePathIsPowerLog:(id)arg1;	// IMP=0x000000010008e150
+ (id)textForContentsOfLog:(id)arg1;	// IMP=0x000000010008defc
+ (id)listedExtensions;	// IMP=0x000000010008de34
- (void).cxx_destruct;	// IMP=0x000000010008f228
- (void)_loadLogs;	// IMP=0x000000010008e8b8
- (void)_triggerLogCopy;	// IMP=0x000000010008e5a4
- (_Bool)deleteLogFileAtPath:(id)arg1;	// IMP=0x000000010008e3b4
@property(readonly, copy, nonatomic) NSArray *logFilePaths; // @synthesize logFilePaths=_logFilePaths;
- (id)init;	// IMP=0x000000010008e31c

@end

