//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BBSettingsGateway, NSArray, NSObject<OS_dispatch_queue>;

@interface TVSettingsNotificationsFacade : NSObject
{
    NSArray *_notificationSettings;	// 8 = 0x8
    BBSettingsGateway *_gateway;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_gatewayQueue;	// 24 = 0x18
}

+ (id)sharedInstance;	// IMP=0x0000000100004cb0
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *gatewayQueue; // @synthesize gatewayQueue=_gatewayQueue;
@property(readonly, nonatomic) BBSettingsGateway *gateway; // @synthesize gateway=_gateway;
@property(copy, nonatomic) NSArray *notificationSettings; // @synthesize notificationSettings=_notificationSettings;
- (void).cxx_destruct;	// IMP=0x0000000100005b64
- (void)_updateBulletinSettingsSynchronously:(_Bool)arg1;	// IMP=0x00000001000053a0
- (void)_updateSettings:(id)arg1;	// IMP=0x0000000100005124
- (void)didBecomeActive:(id)arg1;	// IMP=0x0000000100005114
- (id)notificationSettingForIdentifier:(id)arg1;	// IMP=0x0000000100004f7c
- (void)dealloc;	// IMP=0x0000000100004ea8
- (id)init;	// IMP=0x0000000100004d30

@end

