//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class BKDigitizerTouchStreamAggregate, NSMapTable;

@interface BKDigitizerArbiterInfoPerDisplay : NSObject
{
    NSMapTable *_digitizerServiceToInfoMapping;	// 8 = 0x8
    BKDigitizerTouchStreamAggregate *_touchStreams;	// 16 = 0x10
}

@property(retain, nonatomic) BKDigitizerTouchStreamAggregate *touchStreams; // @synthesize touchStreams=_touchStreams;
@property(retain, nonatomic) NSMapTable *digitizerServiceToInfoMapping; // @synthesize digitizerServiceToInfoMapping=_digitizerServiceToInfoMapping;
- (void)dealloc;	// IMP=0x0000000100068fe8
- (void)removeDigitizerInfoForService:(id)arg1;	// IMP=0x0000000100068eb8
- (struct OpaqueBKDigitizerInfo *)digitizerInfoForService:(id)arg1;	// IMP=0x0000000100068ea0

@end

