//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun  9 2020 17:35:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "BKDisplayRenderOverlay.h"

@class CAContext, CALayer;

@interface BKDisplayRenderOverlayPinkForTesting : BKDisplayRenderOverlay
{
    CAContext *_context;
    CALayer *_layer;
}

+ (void)doItHide;
+ (void)doItShow;
+ (void)doItShowKernel;
+ (id)overlayWithLevel:(float)arg1 display:(id)arg2;
- (void).cxx_destruct;
- (_Bool)_applyProgressIndicatorPropertiesToKernelIfNecessary;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (void)_dismissWithAnimationSettings:(id)arg1;
- (void)_freeze;
- (_Bool)_presentWithAnimationSettings:(id)arg1;
- (_Bool)disablesDisplayUpdates;
- (void)dealloc;
- (id)initWithOverlayDescriptor:(id)arg1 level:(float)arg2;

@end

