//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun  9 2020 17:35:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "BKIOHIDServiceDisappearanceObserver-Protocol.h"
#import "BKIOHIDServiceMatchObserver-Protocol.h"

@class BKDigitizerArbiterInfo, BKIOHIDService, BKIOHIDServiceMatcher, NSString;
@protocol OS_dispatch_group, OS_dispatch_queue;

@interface BKDigitizerArbiterAccess : NSObject <BKIOHIDServiceMatchObserver, BKIOHIDServiceDisappearanceObserver>
{
    NSObject<OS_dispatch_queue> *_queue;
    BKDigitizerArbiterInfo *_arbiterInfo;
    NSObject<OS_dispatch_group> *_waitForMainDisplayGroup;
    BKIOHIDServiceMatcher *_digitizerMatcher;
    BKIOHIDService *_mainDisplayDigitizerService;
}

@property(retain) BKIOHIDService *mainDisplayDigitizerService; // @synthesize mainDisplayDigitizerService=_mainDisplayDigitizerService;
- (void)digitizerServiceDidDetach:(id)arg1;
- (void)accessAsynchronously:(CDUnknownBlockType)arg1;
- (void)accessSynchronously:(CDUnknownBlockType)arg1;
- (void)waitForMainDisplayDigitizerService;
- (void)serviceDidDisappear:(id)arg1;
- (void)matcher:(id)arg1 servicesDidMatch:(id)arg2;
- (void)dealloc;
- (id)initWithScheduler:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

