//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "BKDisplayBootUIRenderOverlay.h"

@class BKImageSequence, CAKeyframeAnimation;

@interface BKDisplayRenderOverlaySpinny : BKDisplayBootUIRenderOverlay
{
    unsigned long long _background;	// 8 = 0x8
    BKImageSequence *_imageSequence;	// 16 = 0x10
    CAKeyframeAnimation *_animation;	// 24 = 0x18
}

+ (id)overlayWithLevel:(float)arg1 display:(id)arg2;	// IMP=0x000000010000350c
@property(nonatomic) unsigned long long background; // @synthesize background=_background;
- (void).cxx_destruct;	// IMP=0x0000000100003d4c
- (id)_assetPrefix;	// IMP=0x0000000100003cf8
- (_Bool)_useLightBackground;	// IMP=0x0000000100003c90
- (void)_unloadSpinnyImageSequence;	// IMP=0x0000000100003bd4
- (id)_spinnyImageSequence;	// IMP=0x0000000100003a4c
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;	// IMP=0x00000001000039d4
- (void)_setScale:(double)arg1;	// IMP=0x0000000100003914
- (void)_cleanUpContentLayer;	// IMP=0x00000001000038c0
- (id)_prepareContentLayerForPresentation:(id)arg1;	// IMP=0x00000001000037b8
- (void)_stopAnimating;	// IMP=0x00000001000037b4
- (void)_startAnimating;	// IMP=0x0000000100003664
- (id)initWithOverlayDescriptor:(id)arg1 level:(float)arg2;	// IMP=0x00000001000035fc

@end

