//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun  9 2020 17:35:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "BKHIDEventProcessor-Protocol.h"

@class NSMutableDictionary, NSString;

@interface BKGenericGestureHIDEventProcessor : NSObject <BKHIDEventProcessor>
{
    NSMutableDictionary *_pendingDestinationsPerSenderID;
}

@property(retain, nonatomic) NSMutableDictionary *pendingDestinationsPerSenderID; // @synthesize pendingDestinationsPerSenderID=_pendingDestinationsPerSenderID;
- (void).cxx_destruct;
- (long long)processEvent:(struct __IOHIDEvent *)arg1 sender:(id)arg2 dispatcher:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

