//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun  9 2020 17:35:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSBundle, NSPointerArray, NSString;

@interface BKImageSequence : NSObject
{
    long long _maximumImageCount;
    double _scale;
    NSPointerArray *_images;
    NSBundle *_bundle;
    NSString *_basename;
    NSString *_idiomSuffix;
}

@property(retain, nonatomic) NSString *idiomSuffix; // @synthesize idiomSuffix=_idiomSuffix;
@property(copy, nonatomic) NSString *basename; // @synthesize basename=_basename;
@property(retain, nonatomic) NSBundle *bundle; // @synthesize bundle=_bundle;
@property(retain, nonatomic) NSPointerArray *images; // @synthesize images=_images;
@property(readonly, nonatomic) double scale; // @synthesize scale=_scale;
@property(readonly, nonatomic) long long maximumImageCount; // @synthesize maximumImageCount=_maximumImageCount;
- (void).cxx_destruct;
- (void)_loadAllImages;
- (struct CGImage *)_imageAtIndex:(long long)arg1;
- (id)_idiomSuffix;
- (struct CGImage *)_createImageForIndex:(unsigned long long)arg1 basename:(id)arg2 scale:(double)arg3 idiom:(id)arg4 bundle:(id)arg5;
- (id)allImages;
- (struct CGImage *)imageAtIndex:(long long)arg1;
- (id)initWithBasename:(id)arg1 bundle:(id)arg2 imageCount:(long long)arg3 scale:(double)arg4;

@end

