//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun  9 2020 17:35:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;
@protocol OS_dispatch_queue;

@interface BKPluginManager : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    NSMutableArray *_plugins;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)loadPostMigrationPluginsWithCompletion:(CDUnknownBlockType)arg1;
- (id)init;

@end

