//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun  9 2020 17:35:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "BKGestureRecognizerDelegate-Protocol.h"

@class NSMutableSet, NSString;

@interface BKStackshotter : NSObject <BKGestureRecognizerDelegate>
{
    NSMutableSet *_gestureRecognizers;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)gestureRecognizer:(id)arg1 didChangeState:(long long)arg2;
- (void)_takeStackshotForReason:(id)arg1;
- (id)_defaultCombos;
- (void)_clearButtonCombos;
- (void)takeStackshotForReason:(id)arg1;
- (void)resetButtonCombos:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

