//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun  9 2020 17:35:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class BSTimer;
@protocol OS_dispatch_queue;

@interface BKTouchDeliveryStatisticsLoggingObserver : NSObject
{
    long long _touchUpCount;
    long long _tapToWakeCount;
    long long _stylusTouchCount;
    long long _detachedTouchCount;
    unsigned int _lastTouchID;
    double _startCoalescingTime;
    BSTimer *_timer;
    NSObject<OS_dispatch_queue> *_workQueue;
}

- (void).cxx_destruct;
- (void)_workQueue_resetStatistics;
- (void)workQueue_logStatisticsForTouchUp:(unsigned int)arg1 detached:(_Bool)arg2 tapToWake:(_Bool)arg3 transducerType:(unsigned int)arg4 context:(unsigned int)arg5 pid:(int)arg6;
- (id)initWithWorkQueue:(id)arg1;

@end

