//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "BKIOHIDServiceDisappearanceObserver-Protocol.h"
#import "BKIOHIDServiceMatchObserver-Protocol.h"

@class BKIOHIDServiceMatcher, NSMutableDictionary, NSString;
@protocol OS_dispatch_queue;

@interface BKTouchPadManager : NSObject <BKIOHIDServiceMatchObserver, BKIOHIDServiceDisappearanceObserver>
{
    NSObject<OS_dispatch_queue> *_touchPadQueue;	// 8 = 0x8
    NSMutableDictionary *_queue_currentTouchPads;	// 16 = 0x10
    BKIOHIDServiceMatcher *_touchPadMatcher;	// 24 = 0x18
}

+ (id)sharedInstance;	// IMP=0x000000010000e030
- (void)_queue_sendCancelEventForTouchPad:(id)arg1;	// IMP=0x000000010000f148
- (void)_queue_handleEvent:(struct __IOHIDEvent *)arg1 fromTouchPad:(id)arg2;	// IMP=0x000000010000ee80
- (void)_queue_sendEvent:(struct __IOHIDEvent *)arg1 fromTouchPad:(id)arg2 toDestination:(id)arg3;	// IMP=0x000000010000ecdc
- (void)_queue_touchPadsDetected:(id)arg1;	// IMP=0x000000010000ea98
- (void)matcher:(id)arg1 servicesDidMatch:(id)arg2;	// IMP=0x000000010000e9f8
- (void)_queue_touchPadRemoved:(id)arg1;	// IMP=0x000000010000e8bc
- (void)serviceDidDisappear:(id)arg1;	// IMP=0x000000010000e87c
- (void)sendCancelEventForAllDisplays;	// IMP=0x000000010000e788
- (void)sendCancelEventForDisplay:(id)arg1;	// IMP=0x000000010000e644
- (_Bool)filterEvent:(struct __IOHIDEvent *)arg1 fromSender:(id)arg2;	// IMP=0x000000010000e35c
- (void)dealloc;	// IMP=0x000000010000e2c8
- (id)init;	// IMP=0x000000010000e0a8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

