//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun  9 2020 17:35:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "BKHIDEvent.h"

@interface BKVendorDefinedEvent : BKHIDEvent
{
    struct __IOHIDEvent *_event;
}

- (void)_fillWithHIDEvent:(struct __IOHIDEvent *)arg1 descriptor:(id)arg2 senderInfo:(id)arg3;
@property(readonly, nonatomic) unsigned long long dataLength;
@property(readonly, nonatomic) char *data;
- (id)description;
- (void)dealloc;
- (id)initWithHIDEventVendorDefinedDescriptor:(id)arg1 senderInfo:(id)arg2;

@end

