//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@interface _PBImageProcessingOperation : NSOperation
{
    long long _targetUserInterfaceStyle;	// 24 = 0x18
    _Bool _shouldPerformASAP;	// 32 = 0x20
}

@property(readonly, nonatomic) _Bool shouldPerformASAP; // @synthesize shouldPerformASAP=_shouldPerformASAP;
@property(readonly, nonatomic) long long targetUserInterfaceStyle; // @synthesize targetUserInterfaceStyle=_targetUserInterfaceStyle;

@end

