//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBSBulletinServiceInterface.h"

@class NSMapTable, NSMutableDictionary, NSString, PBSystemServiceConnection;

@interface PBBulletinService : NSObject <PBSBulletinServiceInterface>
{
    PBSystemServiceConnection *_remoteConnection;	// 8 = 0x8
    NSMapTable *_viewControllersByBulletin;	// 16 = 0x10
    NSMutableDictionary *_pendingBulletinsByRequestID;	// 24 = 0x18
    id <PBSBulletinServiceDelegate> _delegateProxy;	// 32 = 0x20
}

+ (void)_setBulletinService:(id)arg1 forViewController:(id)arg2;	// IMP=0x000000010005d8c8
+ (id)_bulletinServiceForViewController:(id)arg1;	// IMP=0x000000010005d800
+ (void)applicationTerminateBulletinViewController:(id)arg1;	// IMP=0x000000010005b3d4
+ (void)applicationRetireBulletinViewController:(id)arg1;	// IMP=0x000000010005b2cc
+ (void)applicationDismissBulletinViewController:(id)arg1;	// IMP=0x000000010005b1c4
+ (void)applicationActivateBulletinViewController:(id)arg1;	// IMP=0x000000010005b0bc
+ (_Bool)applicationShouldActivateBulletinViewController:(id)arg1 forAction:(unsigned long long)arg2;	// IMP=0x000000010005aedc
+ (void)windowManagerWillPresentBulletinViewController:(id)arg1;	// IMP=0x000000010005add8
+ (id)_bulletinServicesByViewController;	// IMP=0x000000010005a6ec
@property(retain, nonatomic) id <PBSBulletinServiceDelegate> delegateProxy; // @synthesize delegateProxy=_delegateProxy;
@property(readonly, nonatomic) NSMutableDictionary *pendingBulletinsByRequestID; // @synthesize pendingBulletinsByRequestID=_pendingBulletinsByRequestID;
@property(readonly, nonatomic) NSMapTable *viewControllersByBulletin; // @synthesize viewControllersByBulletin=_viewControllersByBulletin;
@property(readonly, nonatomic) PBSystemServiceConnection *remoteConnection; // @synthesize remoteConnection=_remoteConnection;
- (void).cxx_destruct;	// IMP=0x000000010005db14
- (void)_setViewController:(id)arg1 forBulletin:(id)arg2;	// IMP=0x000000010005d630
- (id)_viewControllerForBulletin:(id)arg1;	// IMP=0x000000010005d568
- (id)_bulletinForViewController:(id)arg1;	// IMP=0x000000010005d36c
- (_Bool)_bulletinIsPending:(id)arg1;	// IMP=0x000000010005d284
- (void)_updateRequestForBulletin:(id)arg1 withBulletin:(id)arg2;	// IMP=0x000000010005d050
- (id)_bulletinForRequestID:(unsigned long long)arg1;	// IMP=0x000000010005cf68
- (void)_setBulletin:(id)arg1 forRequestID:(unsigned long long)arg2;	// IMP=0x000000010005ce24
- (void)_prepareToPresentViewController:(id)arg1;	// IMP=0x000000010005cdb4
- (void)_handleApplicationDismissalForViewController:(id)arg1 withReason:(unsigned long long)arg2;	// IMP=0x000000010005c9e4
- (void)_completeWithBulletin:(id)arg1 success:(_Bool)arg2 error:(id)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x000000010005c7d8
- (id)_reserveTableSpaceForBulletin:(id)arg1 error:(id *)arg2;	// IMP=0x000000010005c66c
- (void)setDelegate:(id)arg1;	// IMP=0x000000010005c650
- (void)dismissBulletin:(id)arg1;	// IMP=0x000000010005c3b0
- (id)updateBulletin:(id)arg1 withMessage:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;	// IMP=0x000000010005bfc4
- (void)xpcUpdateBulletin:(id)arg1 withMessage:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;	// IMP=0x000000010005bc70
- (void)presentBulletin:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x000000010005b4dc
- (void)invalidate;	// IMP=0x000000010005a890
- (id)initWithRemoteConnection:(id)arg1;	// IMP=0x000000010005a794
- (id)init;	// IMP=0x000000010005a77c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

