//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBSOSUpdateServiceInterface.h"

@class NSString, PBSOSUpdateManagerClient, PBSystemServiceConnection;

@interface PBOSUpdateService : NSObject <PBSOSUpdateServiceInterface>
{
    id <PBSOSUpdateServiceDelegate> _delegate;	// 8 = 0x8
    PBSOSUpdateManagerClient *_managerClientDelegate;	// 16 = 0x10
    PBSystemServiceConnection *_remoteConnection;	// 24 = 0x18
}

+ (void)_obliterateDataPreservingPaths:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x000000010006808c
@property(readonly, nonatomic) PBSystemServiceConnection *remoteConnection; // @synthesize remoteConnection=_remoteConnection;
- (void).cxx_destruct;	// IMP=0x0000000100069b68
- (void)didFinishApplyWithData:(id)arg1;	// IMP=0x0000000100069ae8
- (void)didEncounterSlowUpdateWithData:(id)arg1;	// IMP=0x0000000100069a78
- (void)didUpdateApplyProgressWithData:(id)arg1;	// IMP=0x0000000100069a08
- (void)didStartApplyWithData:(id)arg1;	// IMP=0x0000000100069998
- (void)didStartRedownloadWithData:(id)arg1;	// IMP=0x0000000100069928
- (void)didFinishDownloadWithData:(id)arg1;	// IMP=0x00000001000698b8
- (void)didUpdateDownloadProgressWithData:(id)arg1;	// IMP=0x0000000100069848
- (void)didStartDownloadWithData:(id)arg1;	// IMP=0x00000001000697d8
- (void)didFinishCheckWithData:(id)arg1;	// IMP=0x0000000100069768
- (void)didStartCheckWithData:(id)arg1;	// IMP=0x00000001000696f8
- (void)obliterateDataPreservingPaths:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100069680
- (void)purgeAssetsWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010006956c
- (void)purgeableAssetSpaceWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0000000100069458
- (void)cancelUpdate;	// IMP=0x0000000100069394
- (void)isUpdateRunningWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0000000100069280
- (void)restore;	// IMP=0x00000001000691bc
- (void)installUpdate:(id)arg1 withOptions:(id)arg2 withResult:(CDUnknownBlockType)arg3;	// IMP=0x0000000100069044
- (void)isUpdate:(id)arg1 readyForInstallation:(CDUnknownBlockType)arg2;	// IMP=0x0000000100068efc
- (void)isDownloading:(CDUnknownBlockType)arg1;	// IMP=0x0000000100068de8
- (void)setAssetDownloadIsDiscretionary:(_Bool)arg1;	// IMP=0x0000000100068cfc
- (void)currentDownload:(CDUnknownBlockType)arg1;	// IMP=0x0000000100068be8
- (void)purgeDownload:(CDUnknownBlockType)arg1;	// IMP=0x0000000100068ad4
- (void)cancelDownload:(CDUnknownBlockType)arg1;	// IMP=0x00000001000689c0
- (void)startDownload:(CDUnknownBlockType)arg1;	// IMP=0x00000001000688ac
- (void)isCheckingForUpdates:(CDUnknownBlockType)arg1;	// IMP=0x0000000100068798
- (void)checkForUpdatesWithOptions:(id)arg1 response:(CDUnknownBlockType)arg2;	// IMP=0x0000000100068650
- (void)checkForUpdateViaMDM;	// IMP=0x000000010006858c
- (void)checkForUpdate;	// IMP=0x00000001000684c8
- (void)setManagerClientDelegate:(id)arg1;	// IMP=0x00000001000684b4
- (void)setDelegate:(id)arg1;	// IMP=0x00000001000684a0
- (void)invalidate;	// IMP=0x000000010006849c
- (id)initWithRemoteConnection:(id)arg1;	// IMP=0x000000010006841c
- (id)init;	// IMP=0x0000000100068404

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

