//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PBUnavailableBundleListLoader : NSObject
{
}

- (id)_numberArrayFromStringArray:(id)arg1;	// IMP=0x000000010007dc44
- (id)_documentLoaderWithRequest:(id)arg1;	// IMP=0x000000010007db08
- (id)_computeRequestWithEndpoint:(id)arg1 error:(id *)arg2;	// IMP=0x000000010007d940
- (id)_santizeProgrammingInfo:(id)arg1 error:(id *)arg2;	// IMP=0x000000010007d728
- (id)_loadProgrammingInfoWithError:(id *)arg1;	// IMP=0x000000010007d39c
- (id)_santizeMappingInfo:(id)arg1 error:(id *)arg2;	// IMP=0x000000010007d0bc
- (id)_loadMappingInfoWithError:(id *)arg1;	// IMP=0x000000010007cd08
- (id)loadIdentifierMappingInfoWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010007ca8c
- (id)loadProgrammingInfoWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010007c810

@end

