//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TVSBackgroundTask, UIViewController;

@interface PBWhatsNewService : NSObject
{
    _Bool _monitoringStarted;	// 8 = 0x8
    _Bool _shouldRetryShowingWhatsNew;	// 9 = 0x9
    _Bool _presentingWhatsNew;	// 10 = 0xa
    TVSBackgroundTask *_whatsNewCheckTask;	// 16 = 0x10
    double _checkTimeInterval;	// 24 = 0x18
    double _currentCheckTimeInterval;	// 32 = 0x20
    int _whatsNewNotifyToken;	// 40 = 0x28
    UIViewController *_presentedWNViewController;	// 48 = 0x30
}

+ (id)sharedInstance;	// IMP=0x00000001000477c8
- (void).cxx_destruct;	// IMP=0x00000001000483a0
- (void)_presentWhatsNewDialog;	// IMP=0x0000000100047fb0
- (void)_scheduleWhatsNewCheckTaskWithInterval:(double)arg1;	// IMP=0x0000000100047ca8
- (_Bool)_isHeadBoardAppFocused;	// IMP=0x0000000100047c54
@property(nonatomic) double checkTimeInterval;
- (void)noteGoodTimeToShowWhatsNew;	// IMP=0x0000000100047a7c
- (void)startWhatsNewMonitoring;	// IMP=0x00000001000478a8
- (void)dealloc;	// IMP=0x000000010004784c

@end

