//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "RPSubDaemonable-Protocol.h"

@class CUCoalescer, CUSystemMonitor, NSArray, NSString, RPIdentity;
@protocol OS_dispatch_queue;

@interface RPIdentityDaemon : NSObject <RPSubDaemonable>
{
    int _homeViewChangeToken;	// 8 = 0x8
    CUCoalescer *_identitiesChangedCoalescer;	// 16 = 0x10
    _Bool _invalidateCalled;	// 24 = 0x18
    _Bool _invalidateDone;	// 25 = 0x19
    NSArray *_pairedDeviceIdentities;	// 32 = 0x20
    int _pairedDevicesNotifier;	// 40 = 0x28
    _Bool _prefFamilyResolve;	// 44 = 0x2c
    _Bool _prefFriendResolve;	// 45 = 0x2d
    _Bool _prefOwnerResolve;	// 46 = 0x2e
    _Bool _prefPairedResolve;	// 47 = 0x2f
    _Bool _prefSharedHomeResolve;	// 48 = 0x30
    NSArray *_sameAccountDeviceIdentities;	// 56 = 0x38
    RPIdentity *_selfIdentityCache;	// 64 = 0x40
    NSArray *_sharedHomeDeviceIdentities;	// 72 = 0x48
    CUSystemMonitor *_systemMonitor;	// 80 = 0x50
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 88 = 0x58
    RPIdentity *_homeKitIdentity;	// 96 = 0x60
}

+ (id)sharedIdentityDaemon;	// IMP=0x00000001000331e4
@property(retain, nonatomic) RPIdentity *homeKitIdentity; // @synthesize homeKitIdentity=_homeKitIdentity;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *dispatchQueue; // @synthesize dispatchQueue=_dispatchQueue;
- (void).cxx_destruct;	// IMP=0x000000010003aaa8
- (unsigned int)_updateSelfIdentityPublic:(id)arg1 privateIdentity:(id)arg2;	// IMP=0x000000010003a3e0
- (unsigned int)_updateSelfIdentityPrivate:(id)arg1 create:(_Bool)arg2;	// IMP=0x0000000100039f98
- (void)_saveSelfIdentityPublicWithPrivateIdentity:(id)arg1 force:(_Bool)arg2;	// IMP=0x0000000100039920
- (void)_saveSelfIdentityPrivate:(id)arg1;	// IMP=0x0000000100039674
- (void)_loadSelfIdentity:(_Bool)arg1;	// IMP=0x00000001000391e4
- (void)_updateSameAccountIdentities;	// IMP=0x0000000100038ab4
- (void)_updatePairedDeviceIdentities;	// IMP=0x0000000100038508
- (void)_postIdentitiesChangedNotification;	// IMP=0x00000001000383c8
- (void)_ensureStopped;	// IMP=0x00000001000382a0
- (void)_ensureStarted;	// IMP=0x0000000100037f30
- (_Bool)saveIdentityWithIDSDeviceID:(id)arg1 message:(id)arg2 error:(id *)arg3;	// IMP=0x0000000100037730
- (_Bool)saveIdentity:(id)arg1 error:(id *)arg2;	// IMP=0x00000001000373cc
- (void)addSelfIdentityInfoToMessage:(id)arg1;	// IMP=0x0000000100037118
- (id)identityOfSelfAndReturnError:(id *)arg1;	// IMP=0x0000000100036fc0
- (id)_identitiesOfType:(int)arg1 error:(id *)arg2;	// IMP=0x0000000100036538
- (id)identitiesOfType:(int)arg1 error:(id *)arg2;	// IMP=0x0000000100036478
- (unsigned int)resolveIdentityTypesForSignature:(id)arg1 data:(id)arg2 typeFlags:(unsigned int)arg3;	// IMP=0x0000000100036094
- (id)resolveIdentityForSignature:(id)arg1 data:(id)arg2 typeFlags:(unsigned int)arg3 error:(id *)arg4;	// IMP=0x0000000100035b68
- (id)resolveIdentityForBonjourDevice:(id)arg1 typeFlags:(unsigned int)arg2;	// IMP=0x0000000100035158
- (void)resolvableAccessoriesUpdated:(id)arg1;	// IMP=0x0000000100034a80
- (_Bool)removeXPCMatchingToken:(unsigned long long)arg1;	// IMP=0x0000000100034a30
- (_Bool)addXPCMatchingToken:(unsigned long long)arg1 event:(id)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x0000000100034a28
- (void)_update;	// IMP=0x0000000100034a1c
- (void)prefsChanged;	// IMP=0x0000000100034648
- (_Bool)diagnosticCommand:(id)arg1 params:(id)arg2;	// IMP=0x0000000100034438
- (void)daemonInfoChanged:(unsigned long long)arg1;	// IMP=0x00000001000342a4
- (void)_invalidated;	// IMP=0x0000000100034200
- (void)_invalidate;	// IMP=0x0000000100034138
- (void)invalidate;	// IMP=0x00000001000340c8
- (void)_activate;	// IMP=0x0000000100033f48
- (void)activate;	// IMP=0x0000000100033ed8
- (id)descriptionWithLevel:(int)arg1;	// IMP=0x00000001000332f0
- (id)init;	// IMP=0x0000000100033264

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

