//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MSDContentInstaller : NSObject
{
}

+ (id)sharedInstance;	// IMP=0x0000000100002248
- (id)originalPathFor:(id)arg1;	// IMP=0x0000000100002e9c
- (_Bool)removeXattr:(id)arg1;	// IMP=0x0000000100002df4
- (_Bool)hasXattr:(id)arg1 path:(id)arg2;	// IMP=0x0000000100002c10
- (_Bool)isContentRootToRemove:(id)arg1;	// IMP=0x0000000100002bf8
- (_Bool)isContentRoot:(id)arg1;	// IMP=0x0000000100002b74
- (_Bool)isNotExtracted:(id)arg1;	// IMP=0x0000000100002b5c
- (_Bool)adjustContentUnder:(id)arg1;	// IMP=0x00000001000024d0
- (_Bool)finishInstallContent;	// IMP=0x00000001000023a8
- (id)init;	// IMP=0x00000001000022c8

@end

