//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class BKProcess;

@protocol BKProcessDelegate <NSObject>
- (void)process:(BKProcess *)arg1 updateAssertionNeedsForReason:(unsigned int)arg2;
- (void)process:(BKProcess *)arg1 didChangeVisibility:(long long)arg2;
- (void)process:(BKProcess *)arg1 didChangeTaskState:(long long)arg2;
- (void)process:(BKProcess *)arg1 didChangeIsDebugging:(_Bool)arg2;
- (void)processNoteAssertionExpirationImminent:(BKProcess *)arg1;
@end

