//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SATVActivityIndicatorViewController.h"

@interface _SATVWifiActivityIndicatorViewController : SATVActivityIndicatorViewController
{
}

- (void)_didSelectMenu;	// IMP=0x000000010001074c
- (void)loadView;	// IMP=0x00000001000105f8

@end

