//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIApplication.h"

#import "UIApplicationDelegate.h"

@class NSString, UIWindow;

@interface Application : UIApplication <UIApplicationDelegate>
{
}

- (unsigned long long)application:(id)arg1 supportedInterfaceOrientationsForWindow:(id)arg2;	// IMP=0x0000000100006af0
- (void)applicationDidEnterBackground:(id)arg1;	// IMP=0x0000000100006aa8
- (void)applicationDidBecomeActive:(id)arg1;	// IMP=0x0000000100006a60
- (void)applicationWillResignActive:(id)arg1;	// IMP=0x0000000100006a18
- (void)applicationDidFinishLaunching:(id)arg1;	// IMP=0x0000000100006994
- (void)applicationWillTerminate:(id)arg1;	// IMP=0x0000000100006990

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) UIWindow *window;

@end

