//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SATVTableViewController.h"

@class UIActivityIndicatorView;

@interface SATVAirplay2LoadingViewController : SATVTableViewController
{
    UIActivityIndicatorView *_activityIndicatorView;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0000000100039e60
@property(readonly, nonatomic, getter=_activityIndicatorView) UIActivityIndicatorView *activityIndicatorView; // @synthesize activityIndicatorView=_activityIndicatorView;
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100039d8c
- (void)viewDidLoad;	// IMP=0x0000000100039cf0

@end

