//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "DMDTaskOperation.h"

@interface DMDAppOperation : DMDTaskOperation
{
}

+ (_Bool)validateRequest:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100024488
- (void)runWithRequest:(id)arg1 bundleIdentifier:(id)arg2;	// IMP=0x00000001000247b4
- (void)runWithRequest:(id)arg1;	// IMP=0x0000000100024684

@end

