//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "DMDDeclarationPayloadMetadata.h"

@class NSDictionary;

@interface DMDActivationPayloadMetadata : DMDDeclarationPayloadMetadata
{
}

+ (id)fetchRequestForActivationsFromOrganizationWithIdentifier:(id)arg1;	// IMP=0x00000001000103dc
- (void)updateStateDictionaryIfNeeded;	// IMP=0x000000010000fb28

// Remaining properties
@property(retain, nonatomic) NSDictionary *predicatePayloadMetadata; // @dynamic predicatePayloadMetadata;

@end

