//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class CATStateMachine, NSOperationQueue, NSPointerArray, NSProgress, NSString;

@interface DMDAppLifeCycle : NSObject
{
    NSString *_bundleIdentifier;	// 8 = 0x8
    NSProgress *_progress;	// 16 = 0x10
    NSPointerArray *_observers;	// 24 = 0x18
    NSOperationQueue *_queue;	// 32 = 0x20
    CATStateMachine *_stateMachine;	// 40 = 0x28
}

+ (id)_lifeCycleByBundleIdentifier;	// IMP=0x000000010001f134
+ (void)_removeLifeCycleForBundleIdentifier:(id)arg1;	// IMP=0x000000010001f090
+ (id)lifeCycleForBundleIdentifier:(id)arg1;	// IMP=0x000000010001ef88
@property(retain, nonatomic) CATStateMachine *stateMachine; // @synthesize stateMachine=_stateMachine;
@property(retain, nonatomic) NSOperationQueue *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSPointerArray *observers; // @synthesize observers=_observers;
@property(readonly, nonatomic) NSProgress *progress; // @synthesize progress=_progress;
@property(readonly, copy, nonatomic) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
- (void).cxx_destruct;	// IMP=0x0000000100023164
- (void)cancelAndWaitUntilAllOperationsAreFinished;	// IMP=0x0000000100023088
- (void)didChangeUpdatingProgress;	// IMP=0x0000000100022eb0
- (void)didChangeInstallingProgress;	// IMP=0x0000000100022cd8
- (void)removeObserver:(id)arg1;	// IMP=0x0000000100022b04
- (void)addObserver:(id)arg1;	// IMP=0x00000001000229f8
- (void)didFinishUninstalling;	// IMP=0x0000000100022790
- (void)didFailUninstalling;	// IMP=0x0000000100022528
- (void)willStartUninstalling;	// IMP=0x00000001000222c0
- (void)didFinishUpdating;	// IMP=0x0000000100022058
- (void)didFailUpdating;	// IMP=0x0000000100021df0
- (void)didCancelUpdating;	// IMP=0x0000000100021b88
- (void)didResumeUpdating;	// IMP=0x0000000100021920
- (void)didPauseUpdating;	// IMP=0x00000001000216b8
- (void)didStartUpdating;	// IMP=0x0000000100021450
- (void)willStartUpdating;	// IMP=0x00000001000211e8
- (void)didFinishInstalling;	// IMP=0x0000000100020f80
- (void)didFailInstalling;	// IMP=0x0000000100020d18
- (void)didCancelInstalling;	// IMP=0x0000000100020ab0
- (void)didResumeInstalling;	// IMP=0x0000000100020848
- (void)didPauseInstalling;	// IMP=0x00000001000205e0
- (void)didStartInstalling;	// IMP=0x0000000100020378
- (void)willStartInstalling;	// IMP=0x0000000100020110
@property(readonly, nonatomic) unsigned long long currentState;
- (id)initWithBundleIdentifier:(id)arg1 currentState:(unsigned long long)arg2;	// IMP=0x000000010001f1c0
- (id)initWithBundleIdentifier:(id)arg1;	// IMP=0x000000010001f1a8

@end

