//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "DMDTaskOperation.h"

@class NSObject;
@protocol OS_os_transaction;

@interface DMDActivityTransactionOperation : DMDTaskOperation
{
    NSObject<OS_os_transaction> *_transaction;	// 24 = 0x18
}

+ (id)requiredEntitlements;	// IMP=0x00000001000133a0
+ (id)whitelistedClassesForRequest;	// IMP=0x000000010001335c
+ (_Bool)validateRequest:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100013224
@property(retain, nonatomic) NSObject<OS_os_transaction> *transaction; // @synthesize transaction=_transaction;
- (void).cxx_destruct;	// IMP=0x0000000100013558
- (void)runWithRequest:(id)arg1;	// IMP=0x00000001000134bc
- (void)endOperationIfNeeded;	// IMP=0x0000000100013474
- (void)cancel;	// IMP=0x0000000100013414
- (_Bool)runOnMainThread;	// IMP=0x000000010001340c
- (_Bool)runConcurrently;	// IMP=0x000000010001321c

@end

