//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "DMDPayloadMetadata.h"

@interface DMDCommandPayloadMetadata : DMDPayloadMetadata
{
}

+ (id)fetchRequestForCommandsPendingDeleteFromOrganizationWithIdentifier:(id)arg1;	// IMP=0x0000000100027e54
+ (id)fetchRequestForCommandsPendingRemovalFromOrganizationWithIdentifier:(id)arg1;	// IMP=0x0000000100027c70
+ (id)fetchRequestForCommandsPendingExecutionFromOrganizationWithIdentifier:(id)arg1;	// IMP=0x0000000100027a8c
+ (id)fetchRequestForCommandsFromOrganizationWithIdentifier:(id)arg1;	// IMP=0x0000000100027a7c
+ (id)fetchRequestForCommandsFromOrganizationWithIdentifier:(id)arg1 matchingPredicate:(id)arg2;	// IMP=0x0000000100027930
+ (id)commandsWithPayloadDictionaries:(id)arg1 organizationIdentifier:(id)arg2 context:(id)arg3 error:(id *)arg4;	// IMP=0x0000000100027584

@end

