//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface DMDConfigurationCapabilities : NSObject
{
}

+ (id)supportedMessageTypes;	// IMP=0x0000000100028bc8
+ (id)supportedPredicateTypes;	// IMP=0x0000000100028ab0
+ (id)supportedActivationTypes;	// IMP=0x0000000100028a04
+ (id)supportedEventTypes;	// IMP=0x000000010002893c
+ (id)supportedConfigurationTypes;	// IMP=0x00000001000286b0
+ (id)supportedAssetTypes;	// IMP=0x0000000100028604
+ (id)supportedDeclarationTypes;	// IMP=0x0000000100028478
+ (id)supportedCommandTypes;	// IMP=0x000000010002837c

@end

