//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "DMDPayloadActionOperation.h"

@interface DMDDeclarationActionOperation : DMDPayloadActionOperation
{
}

- (void)endOperationMarkingPayloadMetadata:(id)arg1 failedWithError:(id)arg2;	// IMP=0x0000000100039fd0

@end

