//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "DMDEngineDatabaseOperation.h"

@class DMFDeactivateConfigurationOrganizationRequest;

@interface DMDEngineDeactivateConfigurationOrganizationOperation : DMDEngineDatabaseOperation
{
    DMFDeactivateConfigurationOrganizationRequest *_request;	// 24 = 0x18
}

@property(retain, nonatomic) DMFDeactivateConfigurationOrganizationRequest *request; // @synthesize request=_request;
- (void).cxx_destruct;	// IMP=0x00000001000455a4
- (void)performDatabaseModificationOperationWithManagedObjectContext:(id)arg1;	// IMP=0x0000000100045210

@end

