//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "DMDTaskOperation.h"

@interface DMDInstallProfileOperation : DMDTaskOperation
{
}

+ (_Bool)validateRequest:(id)arg1 error:(id *)arg2;	// IMP=0x00000001000526d0
+ (id)requiredEntitlements;	// IMP=0x0000000100052664
+ (id)whitelistedClassesForRequest;	// IMP=0x0000000100052620
- (void)_installInteractiveProfile:(id)arg1;	// IMP=0x0000000100052d64
- (void)_installSilentProfileData:(id)arg1 managingProfileIdentifier:(id)arg2;	// IMP=0x00000001000529fc
- (void)runWithRequest:(id)arg1;	// IMP=0x00000001000528b0

@end

