//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "DMDAppOperation.h"

@interface DMDStopManagingAppOperation : DMDAppOperation
{
}

+ (id)requiredEntitlements;	// IMP=0x00000001000679f4
+ (id)whitelistedClassesForRequest;	// IMP=0x00000001000679b0
- (void)runWithRequest:(id)arg1 bundleIdentifier:(id)arg2;	// IMP=0x0000000100067a60

@end

