//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "DMDSUManagerInstallTask.h"

#import "PBSOSUpdateManagerClientDelegate-Protocol.h"

@class NSString, PBSOSUpdateDownload, PBSOSUpdateManagerClient;

@interface DMDSUManagerInstallTask_tvOS : DMDSUManagerInstallTask <PBSOSUpdateManagerClientDelegate>
{
    PBSOSUpdateManagerClient *client;	// 8 = 0x8
    PBSOSUpdateDownload *lastDownload;	// 16 = 0x10
}

+ (id)_dmfInstallErrorFromSUInstallError:(id)arg1;	// IMP=0x0000000100069fb4
+ (id)_dmfDownloadErrorFromSUDownloadError:(id)arg1;	// IMP=0x0000000100069cc0
+ (id)_dmfStatusErrorFromSUStatusError:(id)arg1;	// IMP=0x0000000100069bdc
+ (id)defaultProductKey;	// IMP=0x0000000100068510
@property(retain, nonatomic) PBSOSUpdateDownload *lastDownload; // @synthesize lastDownload;
@property(retain, nonatomic) PBSOSUpdateManagerClient *client; // @synthesize client;
- (void).cxx_destruct;	// IMP=0x000000010006a318
- (void)client:(id)arg1 downloadDidFinish:(id)arg2;	// IMP=0x0000000100069bcc
- (_Bool)removeUpdateWithError:(id *)arg1;	// IMP=0x00000001000697dc
- (_Bool)startInstallWithError:(id *)arg1;	// IMP=0x00000001000694e0
- (_Bool)startDownloadWithError:(id *)arg1;	// IMP=0x000000010006928c
- (id)currentStatusWithError:(id *)arg1;	// IMP=0x0000000100068e5c
- (id)availableUpdateWithVersion:(id)arg1 useDelay:(_Bool)arg2 error:(id *)arg3;	// IMP=0x00000001000685c8
- (id)init;	// IMP=0x000000010006853c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

