//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface RMECacheDeleter : NSObject
{
    NSString *_archivesDirectory;	// 8 = 0x8
}

+ (void)registerCallbacks;	// IMP=0x00000001000054ac
@property(copy, nonatomic) NSString *archivesDirectory; // @synthesize archivesDirectory=_archivesDirectory;
- (void).cxx_destruct;	// IMP=0x000000010000567c
- (struct __CFDictionary *)allocCacheDeletePurgeWithUrgency:(int)arg1 info:(struct __CFDictionary *)arg2;	// IMP=0x00000001000052cc
- (struct __CFDictionary *)allocCacheDeletePurgeableWithUrgency:(int)arg1 info:(struct __CFDictionary *)arg2;	// IMP=0x0000000100005228
- (struct __CFDictionary *)allocCacheDeletePeriodicWithInfo:(struct __CFDictionary *)arg1;	// IMP=0x0000000100004d74
- (struct __CFDictionary *)allocCacheDeleteDictionaryWithVolume:(id)arg1 amount:(unsigned long long)arg2;	// IMP=0x0000000100004c8c
- (id)purgeableLogPathsWithVolume:(id)arg1 urgency:(int)arg2 amount:(unsigned long long *)arg3;	// IMP=0x0000000100004854
- (id)initWithArchivesDirectory:(id)arg1;	// IMP=0x00000001000047c4
- (id)init;	// IMP=0x000000010000473c

@end

