//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SVSStarkGatekeeperHeaderView.h"

@class UIButton;

@interface SVSStarkCancelButtonGatekeeperHeaderView : SVSStarkGatekeeperHeaderView
{
    UIButton *_cancelButton;	// 32 = 0x20
}

@property(readonly, nonatomic, getter=_cancelButton) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
- (void).cxx_destruct;	// IMP=0x0000000100038d50
- (id)preferredFocusEnvironments;	// IMP=0x0000000100038cb8
- (void)_cancelButtonTapped:(id)arg1;	// IMP=0x0000000100038cac
- (void)layoutSubviews;	// IMP=0x0000000100038b04
- (id)initWithAceObject:(id)arg1 currentTurnContext:(id)arg2;	// IMP=0x0000000100038a80
- (id)initWithRequestOptions:(id)arg1 currentTurnContext:(id)arg2;	// IMP=0x00000001000389fc
- (void)_initialize;	// IMP=0x00000001000388a8

@end

