//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "AVCaptureAudioDataOutputSampleBufferDelegate-Protocol.h"
#import "AVCaptureVideoDataOutputSampleBufferDelegate-Protocol.h"

@class AVCaptureAudioDataOutput, AVCaptureDeviceInput, AVCaptureSession, AVCaptureVideoDataOutput, AVCaptureVideoPreviewLayer, NSDate, NSString;
@protocol OS_dispatch_queue;

@interface RPCaptureManager : NSObject <AVCaptureVideoDataOutputSampleBufferDelegate, AVCaptureAudioDataOutputSampleBufferDelegate>
{
    _Bool _recordingMicrophone;	// 8 = 0x8
    _Bool _recordingCamera;	// 9 = 0x9
    _Bool _recordingAppAudio;	// 10 = 0xa
    _Bool _sessionInProgress;	// 11 = 0xb
    _Bool _micInterrupted;	// 12 = 0xc
    _Bool _resumed;	// 13 = 0xd
    AVCaptureVideoPreviewLayer *_avPreviewLayer;	// 16 = 0x10
    CDUnknownBlockType _microphoneOutputHandler;	// 24 = 0x18
    CDUnknownBlockType _cameraOutputHandler;	// 32 = 0x20
    CDUnknownBlockType _appAudioOutputHandler;	// 40 = 0x28
    long long _cameraPosition;	// 48 = 0x30
    NSObject<OS_dispatch_queue> *_sessionSampleBufferQueue;	// 56 = 0x38
    AVCaptureSession *_captureSession;	// 64 = 0x40
    AVCaptureDeviceInput *_captureDeviceVideoInput;	// 72 = 0x48
    AVCaptureDeviceInput *_captureDeviceAudioInput;	// 80 = 0x50
    AVCaptureVideoDataOutput *_captureSessionVideoDataOutput;	// 88 = 0x58
    AVCaptureAudioDataOutput *_captureSessionAudioDataOutput;	// 96 = 0x60
    CDStruct_ad6583bf *_audioRecorderQueue;	// 104 = 0x68
    NSDate *_lastMicAudioDate;	// 112 = 0x70
    NSDate *_lastAudioDate;	// 120 = 0x78
    CDUnknownBlockType _micDidStartHandler;	// 128 = 0x80
    CDUnknownBlockType _appTapDidStartHandler;	// 136 = 0x88
    CDStruct_1b6d18a9 _captureStartTime;	// 144 = 0x90
    CDStruct_1b6d18a9 _micInterruptionPresentationTimeStamp;	// 168 = 0xa8
    struct AudioStreamBasicDescription _audioBasicDescription;	// 192 = 0xc0
    struct AudioTimeStamp _initialTimestamp;	// 232 = 0xe8
}

+ (id)audioDispatchQueue;	// IMP=0x0000000100023f10
+ (_Bool)hasAudioCaptureDevice;	// IMP=0x0000000100022b88
+ (id)sharedManager;	// IMP=0x0000000100022a98
@property(nonatomic) struct AudioTimeStamp initialTimestamp; // @synthesize initialTimestamp=_initialTimestamp;
@property(copy, nonatomic) CDUnknownBlockType appTapDidStartHandler; // @synthesize appTapDidStartHandler=_appTapDidStartHandler;
@property(copy, nonatomic) CDUnknownBlockType micDidStartHandler; // @synthesize micDidStartHandler=_micDidStartHandler;
@property(nonatomic) _Bool resumed; // @synthesize resumed=_resumed;
@property(retain, nonatomic) NSDate *lastAudioDate; // @synthesize lastAudioDate=_lastAudioDate;
@property(nonatomic) _Bool micInterrupted; // @synthesize micInterrupted=_micInterrupted;
@property(nonatomic) CDStruct_1b6d18a9 micInterruptionPresentationTimeStamp; // @synthesize micInterruptionPresentationTimeStamp=_micInterruptionPresentationTimeStamp;
@property(retain, nonatomic) NSDate *lastMicAudioDate; // @synthesize lastMicAudioDate=_lastMicAudioDate;
@property(nonatomic) struct AudioStreamBasicDescription audioBasicDescription; // @synthesize audioBasicDescription=_audioBasicDescription;
@property(nonatomic) CDStruct_ad6583bf *audioRecorderQueue; // @synthesize audioRecorderQueue=_audioRecorderQueue;
@property _Bool sessionInProgress; // @synthesize sessionInProgress=_sessionInProgress;
@property(nonatomic, getter=isRecordingAppAudio) _Bool recordingAppAudio; // @synthesize recordingAppAudio=_recordingAppAudio;
@property(nonatomic, getter=isRecordingCamera) _Bool recordingCamera; // @synthesize recordingCamera=_recordingCamera;
@property(nonatomic, getter=isRecordingMicrophone) _Bool recordingMicrophone; // @synthesize recordingMicrophone=_recordingMicrophone;
@property(retain, nonatomic) AVCaptureAudioDataOutput *captureSessionAudioDataOutput; // @synthesize captureSessionAudioDataOutput=_captureSessionAudioDataOutput;
@property(retain, nonatomic) AVCaptureVideoDataOutput *captureSessionVideoDataOutput; // @synthesize captureSessionVideoDataOutput=_captureSessionVideoDataOutput;
@property(retain, nonatomic) AVCaptureDeviceInput *captureDeviceAudioInput; // @synthesize captureDeviceAudioInput=_captureDeviceAudioInput;
@property(retain, nonatomic) AVCaptureDeviceInput *captureDeviceVideoInput; // @synthesize captureDeviceVideoInput=_captureDeviceVideoInput;
@property(retain, nonatomic) AVCaptureSession *captureSession; // @synthesize captureSession=_captureSession;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *sessionSampleBufferQueue; // @synthesize sessionSampleBufferQueue=_sessionSampleBufferQueue;
@property(nonatomic) CDStruct_1b6d18a9 captureStartTime; // @synthesize captureStartTime=_captureStartTime;
@property(nonatomic) long long cameraPosition; // @synthesize cameraPosition=_cameraPosition;
@property(copy, nonatomic) CDUnknownBlockType appAudioOutputHandler; // @synthesize appAudioOutputHandler=_appAudioOutputHandler;
@property(copy, nonatomic) CDUnknownBlockType cameraOutputHandler; // @synthesize cameraOutputHandler=_cameraOutputHandler;
@property(copy, nonatomic) CDUnknownBlockType microphoneOutputHandler; // @synthesize microphoneOutputHandler=_microphoneOutputHandler;
@property(retain, nonatomic) AVCaptureVideoPreviewLayer *avPreviewLayer; // @synthesize avPreviewLayer=_avPreviewLayer;
- (void).cxx_destruct;	// IMP=0x0000000100024ee8
- (void)stopAppAudioCapture;	// IMP=0x00000001000246bc
- (void)startAppAudioCaptureForProcessID:(int)arg1 outputHandler:(CDUnknownBlockType)arg2 didStartHandler:(CDUnknownBlockType)arg3;	// IMP=0x0000000100024070
- (void)resumeAppAudioCaptureForProcessID:(int)arg1 outputHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100024004
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;	// IMP=0x0000000100023d14
- (void)checkAndHandleMicInterruption;	// IMP=0x0000000100023a20
- (void)stopMicrophoneCapture;	// IMP=0x00000001000237dc
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x00000001000236c0
- (void)startMicrophoneCaptureWithOutput:(CDUnknownBlockType)arg1 didStartHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100023100
- (void)stopAllCapture;	// IMP=0x0000000100023020
- (void)stopCaptureSession;	// IMP=0x0000000100022f1c
- (void)startCaptureSession;	// IMP=0x0000000100022e60
- (void)dealloc;	// IMP=0x0000000100022dd8
- (id)init;	// IMP=0x0000000100022cac
- (void)handleAudioSessionInterruption:(id)arg1;	// IMP=0x0000000100022b90

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

