//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSExtensionContext.h>

#import "RPExtensionHostProtocol-Protocol.h"

@class NSString;

@interface RPExtensionHostContext : NSExtensionContext <RPExtensionHostProtocol>
{
}

+ (id)_extensionAuxiliaryVendorProtocol;	// IMP=0x000000010001b588
+ (id)_extensionAuxiliaryHostProtocol;	// IMP=0x000000010001b56c
- (void)didConnectToVendor:(id)arg1;	// IMP=0x000000010001b5a4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

