//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Accounts/ACAccount.h>

@interface ACAccount (GameCenter)
- (void)_gkSetProperty:(id)arg1 forKey:(id)arg2 environment:(long long)arg3;	// IMP=0x00000001000cb190
- (id)_gkPropertyForKey:(id)arg1 environment:(long long)arg2;	// IMP=0x00000001000cb13c
- (id)_gkModifiedDateForProperty:(id)arg1 environment:(long long)arg2;	// IMP=0x00000001000cb0e8
- (id)_gkCredentialForEnvironment:(long long)arg1;	// IMP=0x00000001000cafa8
- (id)_gkCredentialsForEnvironment:(long long)arg1;	// IMP=0x00000001000ca46c
- (id)_gkCredentials;	// IMP=0x00000001000ca45c
- (void)_gkSetPlayerInternal:(id)arg1;	// IMP=0x00000001000ca3b4
- (id)_gkPlayerInternal;	// IMP=0x00000001000ca0c0
- (id)_gkPerEnvironmentTokens;	// IMP=0x00000001000c9ff0
- (void)_gkSetToken:(id)arg1 forEnvironment:(long long)arg2;	// IMP=0x00000001000c9cf8
- (id)_gkTokenForEnvironment:(long long)arg1;	// IMP=0x00000001000c9c2c
- (_Bool)_gkIsPrimaryForEnvironment:(long long)arg1;	// IMP=0x00000001000c9bc4
@end

