//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface GKAppStoreManager : NSObject
{
}

+ (id)sharedManager;	// IMP=0x00000001000a42e4
- (void)loadTellAFriendMessageForGameWithAdamID:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001000a4ac8
- (void)lookupStoreItemsForAdamIDs:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001000a4434
- (_Bool)accountIsLoggedIntoAStore;	// IMP=0x00000001000a43fc
- (void)stopObservingStoreFrontChangesFor:(id)arg1;	// IMP=0x00000001000a43b0
- (void)beginObservingStoreFrontChangesFor:(id)arg1 withSelector:(SEL)arg2;	// IMP=0x00000001000a435c

@end

