//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GKBulletinController.h"

#import "PBSBulletinServiceDelegate-Protocol.h"

@class NSString;
@protocol PBSBulletinServiceInterface;

@interface GKBulletinControllerATV : GKBulletinController <PBSBulletinServiceDelegate>
{
    id <PBSBulletinServiceInterface> _bulletinServiceProxy;	// 32 = 0x20
}

@property(retain, nonatomic) id <PBSBulletinServiceInterface> bulletinServiceProxy; // @synthesize bulletinServiceProxy=_bulletinServiceProxy;
- (void)bulletinService:(id)arg1 didDismissBulletin:(id)arg2 withReason:(unsigned long long)arg3;	// IMP=0x0000000100025dd0
- (id)callAction:(id)arg1 forBulletinDictionary:(id)arg2;	// IMP=0x000000010002569c
- (void)launchBulletin:(id)arg1;	// IMP=0x0000000100024d50
- (void)clearBulletin:(id)arg1;	// IMP=0x0000000100024a88
- (void)removeAllBulletins;	// IMP=0x0000000100024648
- (void)expireBulletin:(id)arg1;	// IMP=0x0000000100024380
- (void)withdrawBulletin:(id)arg1;	// IMP=0x00000001000240b8
- (void)presentBulletin:(id)arg1;	// IMP=0x0000000100023694
- (void)dealloc;	// IMP=0x0000000100023628
- (id)init;	// IMP=0x0000000100023364
- (id)bulletinFromGKBulletin:(id)arg1;	// IMP=0x0000000100022ff0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

