//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GKInternalRepresentation.h"

@class GKPlayerInternal, NSString;

@interface GKConcernInternal : GKInternalRepresentation
{
    GKPlayerInternal *_player;	// 8 = 0x8
    NSString *_message;	// 16 = 0x10
    unsigned int _concernID;	// 24 = 0x18
}

+ (id)secureCodedPropertyKeys;	// IMP=0x00000001001074cc
+ (_Bool)supportsSecureCoding;	// IMP=0x0000000100107454
@property(nonatomic) unsigned int concernID; // @synthesize concernID=_concernID;
@property(copy, nonatomic) NSString *message; // @synthesize message=_message;
@property(retain, nonatomic) GKPlayerInternal *player; // @synthesize player=_player;
- (unsigned long long)hash;	// IMP=0x00000001001076a4
- (_Bool)isEqual:(id)arg1;	// IMP=0x00000001001075f4
- (void)dealloc;	// IMP=0x000000010010745c

@end

