//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "APSConnectionDelegate-Protocol.h"
#import "GKLockStatusObserver-Protocol.h"
#import "GKNATObserverDelegate-Protocol.h"
#import "GKPreferencesDelegate-Protocol.h"
#import "NSXPCListenerDelegate-Protocol.h"

@class APSConnection, GKApplicationStateMonitor, GKNATObserver, GKReachability, NSData, NSDate, NSString, NSXPCListener;
@protocol OS_dispatch_queue, OS_dispatch_semaphore;

@interface GKDataRequestManager : NSObject <NSXPCListenerDelegate, APSConnectionDelegate, GKNATObserverDelegate, GKPreferencesDelegate, GKLockStatusObserver>
{
    NSXPCListener *_publicListener;	// 8 = 0x8
    long long _currentEnvironment;	// 16 = 0x10
    int _natType;	// 24 = 0x18
    GKNATObserver *_natObserver;	// 32 = 0x20
    NSObject<OS_dispatch_semaphore> *_natSemaphore;	// 40 = 0x28
    NSObject<OS_dispatch_queue> *_natQueue;	// 48 = 0x30
    NSData *_pushToken;	// 56 = 0x38
    _Bool _receivesMemoryWarnings;	// 64 = 0x40
    long long _activePushEnvironment;	// 72 = 0x48
    NSDate *_nearbyQueryLastCheckDate;	// 80 = 0x50
    double _nearbyQueryAllowance;	// 88 = 0x58
    APSConnection *_apsConnection;	// 96 = 0x60
    APSConnection *_pushConnectionProd;	// 104 = 0x68
    APSConnection *_pushConnectionDev;	// 112 = 0x70
    GKApplicationStateMonitor *_applicationStateMonitor;	// 120 = 0x78
    NSString *_authenticatingWithSettingsBundleID;	// 128 = 0x80
    GKReachability *_reachability;	// 136 = 0x88
}

+ (id)ratingsQueue;	// IMP=0x0000000100052318
+ (id)statsQueue;	// IMP=0x00000001000522b0
+ (_Bool)allowSelfSignedCertForEnvironment:(long long)arg1;	// IMP=0x000000010004a97c
+ (id)syncQueue;	// IMP=0x0000000100046e8c
+ (id)pushQueue;	// IMP=0x0000000100046e24
+ (id)clientQueue;	// IMP=0x0000000100046e18
+ (id)sharedManager;	// IMP=0x0000000100046e0c
@property(retain, nonatomic) GKReachability *reachability; // @synthesize reachability=_reachability;
@property(retain) NSString *authenticatingWithSettingsBundleID; // @synthesize authenticatingWithSettingsBundleID=_authenticatingWithSettingsBundleID;
@property(retain, nonatomic) GKApplicationStateMonitor *applicationStateMonitor; // @synthesize applicationStateMonitor=_applicationStateMonitor;
@property(retain, nonatomic) APSConnection *pushConnectionDev; // @synthesize pushConnectionDev=_pushConnectionDev;
@property(retain, nonatomic) APSConnection *pushConnectionProd; // @synthesize pushConnectionProd=_pushConnectionProd;
@property(retain, nonatomic) APSConnection *apsConnection; // @synthesize apsConnection=_apsConnection;
@property double nearbyQueryAllowance; // @synthesize nearbyQueryAllowance=_nearbyQueryAllowance;
@property(retain) NSDate *nearbyQueryLastCheckDate; // @synthesize nearbyQueryLastCheckDate=_nearbyQueryLastCheckDate;
@property(nonatomic) _Bool receivesMemoryWarnings; // @synthesize receivesMemoryWarnings=_receivesMemoryWarnings;
@property(readonly) long long currentEnvironment; // @synthesize currentEnvironment=_currentEnvironment;
- (id)storeBag;	// IMP=0x0000000100052380
- (void)storeFrontChanged:(id)arg1;	// IMP=0x00000001000520c0
- (void)getStoreFront:(CDUnknownBlockType)arg1;	// IMP=0x0000000100051be8
- (void)terminate;	// IMP=0x000000010005186c
- (void)beginTransaction:(id)arg1;	// IMP=0x0000000100051690
- (void)endTransaction:(id)arg1;	// IMP=0x00000001000514b4
- (void)processIncomingMessage:(id)arg1;	// IMP=0x00000001000512c4
- (void)connection:(id)arg1 didReceiveIncomingMessage:(id)arg2;	// IMP=0x0000000100050634
- (void)connection:(id)arg1 didReceivePublicToken:(id)arg2;	// IMP=0x0000000100050184
- (void)processIncomingiMessageInvite:(id)arg1;	// IMP=0x000000010004f800
- (void)didReceiveIncomingIDSMessage:(id)arg1;	// IMP=0x000000010004f7f4
- (void)gameCenterDidBecomeRestricted;	// IMP=0x000000010004f608
- (void)loadLocalizedGameNameForBundleID:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x000000010004f320
- (void)appStateChanged:(id)arg1;	// IMP=0x000000010004edf8
- (void)terminateClient:(id)arg1;	// IMP=0x000000010004ec9c
- (void)synchronizeBagWithPreferences;	// IMP=0x000000010004ea78
- (void)sendPushTokenForClient:(id)arg1;	// IMP=0x000000010004de18
- (void)loadConnectivitySettingsAndStartNATObserver;	// IMP=0x000000010004d914
- (void)_resetNATObserverWithSettings:(id)arg1;	// IMP=0x000000010004d674
- (void)updateActivePushEnvironment;	// IMP=0x000000010004d200
- (void)_updatePushEnvironmentWithStoreBag:(id)arg1;	// IMP=0x000000010004ce00
@property(retain) NSData *pushToken; // @synthesize pushToken=_pushToken;
- (void)_setPushToken:(id)arg1;	// IMP=0x000000010004caf8
@property long long activePushEnvironment; // @synthesize activePushEnvironment=_activePushEnvironment;
- (void)_setActivePushEnvironment:(long long)arg1;	// IMP=0x000000010004c4d4
- (void)getValidNATTypeWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x000000010004c050
- (void)NATTypeDidChange:(int)arg1;	// IMP=0x000000010004be48
@property int natType; // @synthesize natType=_natType;
- (void)_waitForValidNATType;	// IMP=0x000000010004bbec
- (void)_setConnectivitySettings:(id)arg1;	// IMP=0x000000010004b9e4
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x000000010004ac10
- (void)resetEnvironment;	// IMP=0x000000010004a9a0
@property(readonly, nonatomic) long long preferredEnvironment;
- (void)dealloc;	// IMP=0x000000010004a7b4
- (void)clearPushEnvironment;	// IMP=0x000000010004a6cc
- (void)_clearPushConnections;	// IMP=0x000000010004a294
- (void)updateNotificationTopics;	// IMP=0x000000010004a22c
- (void)setUpCloudKitNotificationTopics;	// IMP=0x000000010004a108
- (void)_updateNotificationTopics;	// IMP=0x0000000100049608
@property(readonly, nonatomic) APSConnection *activePushConnection; // @dynamic activePushConnection;
- (id)pushConnectionForEnvironment:(long long)arg1;	// IMP=0x00000001000495ac
- (void)storeBagChanged:(id)arg1;	// IMP=0x0000000100049148
- (void)finishStartup;	// IMP=0x0000000100047290
- (void)clientProxy:(id)arg1 didRefreshContentsForDataType:(unsigned int)arg2 userInfo:(id)arg3;	// IMP=0x000000010004728c
- (void)reachabilityDidChange:(id)arg1;	// IMP=0x000000010004722c
- (void)iCloudAccountAvailabilityChanged:(id)arg1;	// IMP=0x0000000100047214
- (id)init;	// IMP=0x0000000100047070
- (void)lockStatusDidChange;	// IMP=0x000000010004706c
- (void)performAsync:(CDUnknownBlockType)arg1;	// IMP=0x0000000100047034
- (void)performSync:(CDUnknownBlockType)arg1;	// IMP=0x0000000100046ef4
- (void)clearAllNearbyInvites;	// IMP=0x000000010008eb64
- (void)handleNearbyInviteResponse:(id)arg1;	// IMP=0x000000010008e394
- (void)nearbyInviteWasCancelled:(id)arg1;	// IMP=0x000000010008df90
- (void)presentNearbyInvite:(id)arg1;	// IMP=0x000000010008d0a8
- (id)updateRequestWithPushToken:(id)arg1;	// IMP=0x00000001001741e0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

