//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class GKEventEmitter, NSString;
@protocol GKLockStatusObserver;

@interface GKDevice : NSObject
{
    NSString *_udid;	// 8 = 0x8
    NSString *_deviceName;	// 16 = 0x10
    NSString *_osVersion;	// 24 = 0x18
    NSString *_buildVersion;	// 32 = 0x20
    NSString *_gameKitVersion;	// 40 = 0x28
    _Bool _gameKitAvailable;	// 48 = 0x30
    GKEventEmitter<GKLockStatusObserver> *_emitter;	// 56 = 0x38
}

+ (id)currentDevice;	// IMP=0x00000001000672d0
@property(retain, nonatomic) GKEventEmitter<GKLockStatusObserver> *emitter; // @synthesize emitter=_emitter;
@property(readonly, nonatomic, getter=isGameKitAvailable) _Bool gameKitAvailable; // @synthesize gameKitAvailable=_gameKitAvailable;
@property(readonly, nonatomic) NSString *gameKitVersion; // @synthesize gameKitVersion=_gameKitVersion;
@property(readonly, nonatomic) NSString *buildVersion; // @synthesize buildVersion=_buildVersion;
@property(readonly, nonatomic) NSString *osVersion; // @synthesize osVersion=_osVersion;
@property(retain, nonatomic) NSString *deviceName; // @synthesize deviceName=_deviceName;
- (void)removeLockStatusObserver:(id)arg1;	// IMP=0x0000000100067bec
- (void)addLockStatusObserver:(id)arg1;	// IMP=0x0000000100067bd4
- (void)stopObservingKeyBagStatus;	// IMP=0x0000000100067ba4
- (void)beginObservingKeyBagStatusWithCallback:(CDUnknownFunctionPointerType)arg1;	// IMP=0x0000000100067b68
- (id)buildVersionHeader;	// IMP=0x0000000100067a94
- (id)protocolVersionHeader;	// IMP=0x0000000100067a64
- (id)storeUserAgent;	// IMP=0x0000000100067924
- (id)processNameHeader;	// IMP=0x0000000100067890
- (id)userAgentWithProcessName:(id)arg1 protocolVersion:(id)arg2;	// IMP=0x00000001000676c4
- (id)userAgent;	// IMP=0x00000001000676b0
- (void)dealloc;	// IMP=0x00000001000675e0
@property(readonly, nonatomic) NSString *udid;
- (id)init;	// IMP=0x0000000100067378
- (_Bool)isProductType:(unsigned int)arg1;	// IMP=0x00000001000aac78
- (_Bool)isFocusDevice;	// IMP=0x00000001000aac08
- (_Bool)isDevelopmentDevice;	// IMP=0x00000001000aab70
- (id)_platformUDID;	// IMP=0x00000001000aaaf0
- (void)_initPlatform;	// IMP=0x00000001000aa7a4

@end

