//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GKFriendService.h"

#import "GKFriendServicePrivate-Protocol.h"

@class NSString;

@interface GKFriendServicePrivate : GKFriendService <GKFriendServicePrivate>
{
}

+ (unsigned long long)requiredEntitlements;	// IMP=0x0000000100095650
+ (Class)interfaceClass;	// IMP=0x000000010009563c
- (oneway void)requestGKPlayerIDforiCloudIDs:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100096b3c
- (oneway void)reportConcern:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100096824
- (oneway void)getConcernsForPlayer:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x000000010009636c
- (oneway void)removeAllFriendsWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100095d04
- (oneway void)removeFriendWithPlayer:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x000000010009566c
- (oneway void)getCommonFriendsForPlayer:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100095658

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

