//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GKPlayerOwnedListCacheObject.h"

@interface GKFriendListCacheObject : GKPlayerOwnedListCacheObject
{
}

+ (id)cacheFriendList:(id)arg1 withTimeToLive:(double)arg2 forProfile:(id)arg3 managedObjectContext:(id)arg4 commonFriends:(_Bool)arg5;	// IMP=0x0000000100038814
+ (id)entityName;	// IMP=0x00000001000386d4
+ (Class)entryClass;	// IMP=0x00000001000386c0
- (id)internalRepresentation;	// IMP=0x0000000100039bb4
- (void)populateFriendNamesFromServerRepresentationDictionary:(id)arg1;	// IMP=0x000000010003919c
- (id)playerIDs;	// IMP=0x00000001000386e0

// Remaining properties
@property(nonatomic) _Bool common; // @dynamic common;

@end

