//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GKPlayerOwnedListCacheObject.h"

@interface GKGameRecommendationListCacheObject : GKPlayerOwnedListCacheObject
{
}

+ (Class)entryClass;	// IMP=0x000000010003e8b0
+ (id)entityName;	// IMP=0x000000010003e8a4
- (id)internalRepresentation;	// IMP=0x000000010003eba8
- (void)updateWithServerRepresentation:(id)arg1 expirationDate:(id)arg2;	// IMP=0x000000010003e8c4

@end

