//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GKCacheObject.h"

@class GKGameCacheObject, NSDate, NSString;

@interface GKInviteCacheObject : GKCacheObject
{
}

+ (id)fetchSortDescriptors;	// IMP=0x00000001000433dc
+ (id)entityName;	// IMP=0x0000000100043354
- (void)awakeFromInsert;	// IMP=0x0000000100043360

// Remaining properties
@property(retain, nonatomic) GKGameCacheObject *game; // @dynamic game;
@property(retain, nonatomic) NSString *inviteID; // @dynamic inviteID;
@property(retain, nonatomic) NSDate *timeStamp; // @dynamic timeStamp;
@property(nonatomic) int type; // @dynamic type;

@end

