//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GKInternalRepresentation.h"

@class NSArray, NSData, NSDictionary, NSString;

@interface GKMatchRequestInternal : GKInternalRepresentation
{
    unsigned long long _matchType;	// 8 = 0x8
    NSArray *_recipients;	// 16 = 0x10
    NSArray *_recipientPlayerIDs;	// 24 = 0x18
    NSString *_inviteMessage;	// 32 = 0x20
    NSDictionary *_localizableInviteMessage;	// 40 = 0x28
    NSData *_sessionToken;	// 48 = 0x30
    NSString *_rid;	// 56 = 0x38
    unsigned int _version;	// 64 = 0x40
    _Bool _preloadedMatch;	// 68 = 0x44
    int _playerGroup;	// 72 = 0x48
    unsigned int _playerAttributes;	// 76 = 0x4c
    unsigned char _minPlayers;	// 80 = 0x50
    unsigned char _maxPlayers;	// 81 = 0x51
    unsigned char _defaultNumberOfPlayers;	// 82 = 0x52
}

+ (id)secureCodedPropertyKeys;	// IMP=0x000000010011422c
@property(nonatomic) unsigned char defaultNumberOfPlayers; // @synthesize defaultNumberOfPlayers=_defaultNumberOfPlayers;
@property(nonatomic, getter=isPreloadedMatch) _Bool preloadedMatch; // @synthesize preloadedMatch=_preloadedMatch;
@property(nonatomic) unsigned int version; // @synthesize version=_version;
@property(retain, nonatomic) NSString *rid; // @synthesize rid=_rid;
@property(retain, nonatomic) NSData *sessionToken; // @synthesize sessionToken=_sessionToken;
@property(nonatomic) unsigned long long matchType; // @synthesize matchType=_matchType;
@property(retain, nonatomic) NSDictionary *localizableInviteMessage; // @synthesize localizableInviteMessage=_localizableInviteMessage;
@property(copy, nonatomic) NSString *inviteMessage; // @synthesize inviteMessage=_inviteMessage;
@property(retain, nonatomic) NSArray *recipientPlayerIDs; // @synthesize recipientPlayerIDs=_recipientPlayerIDs;
@property(retain, nonatomic) NSArray *recipients; // @synthesize recipients=_recipients;
@property(nonatomic) unsigned int playerAttributes; // @synthesize playerAttributes=_playerAttributes;
@property(nonatomic) int playerGroup; // @synthesize playerGroup=_playerGroup;
@property(nonatomic) unsigned char maxPlayers; // @synthesize maxPlayers=_maxPlayers;
@property(nonatomic) unsigned char minPlayers; // @synthesize minPlayers=_minPlayers;
- (_Bool)hasGuestPlayers;	// IMP=0x0000000100114578
- (unsigned long long)hash;	// IMP=0x00000001001141b8
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000100113e14
- (void)dealloc;	// IMP=0x0000000100113d54
- (id)init;	// IMP=0x0000000100113cd4

@end

