//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GKCacheObject.h"

@class GKTurnBasedExchangeCacheObject, NSData, NSDate;

@interface GKTurnBasedExchangeReplyCacheObject : GKCacheObject
{
}

+ (id)entityName;	// IMP=0x0000000100042600
- (id)internalRepresentation;	// IMP=0x0000000100042848
- (void)updateWithServerRepresentation:(id)arg1;	// IMP=0x000000010004260c

// Remaining properties
@property(retain, nonatomic) NSData *data; // @dynamic data;
@property(retain, nonatomic) GKTurnBasedExchangeCacheObject *exchange; // @dynamic exchange;
@property(retain, nonatomic) NSData *localizableMessage; // @dynamic localizableMessage;
@property(nonatomic) int recipientIndex; // @dynamic recipientIndex;
@property(retain, nonatomic) NSDate *replyDate; // @dynamic replyDate;

@end

