//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GKSpecialPlayerInternal.h"

@interface GKUnknownPlayerInternal : GKSpecialPlayerInternal
{
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0000000100107018
- (_Bool)isUnknownPlayer;	// IMP=0x0000000100107044
- (id)teamPlayerID;	// IMP=0x0000000100107038
- (id)gamePlayerID;	// IMP=0x000000010010702c
- (id)playerID;	// IMP=0x0000000100107020

@end

