//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSDictionary.h>

@interface NSDictionary (GKCollectionUtils)
+ (id)_gkDictionaryWithFormEncodedString:(id)arg1;	// IMP=0x00000001000a0904
- (id)_gkValuesForKeys:(id)arg1;	// IMP=0x00000001000a0970
- (id)_gkSubDictionaryWithKeys:(id)arg1 mappedToNewKeys:(id)arg2;	// IMP=0x00000001000a06f4
- (id)_gkSubDictionaryWithKeys:(id)arg1;	// IMP=0x00000001000a0584
- (id)_gkDictionaryByRemovingObjectForKey:(id)arg1;	// IMP=0x00000001000a053c
- (id)_gkDictionaryByRemovingObjectsForKeys:(id)arg1;	// IMP=0x00000001000a04f4
@end

