//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSDictionary.h>

@interface NSDictionary (GKImageAdditions)
+ (id)_gkClientImageDictionaryForServerImageURLs:(id)arg1;	// IMP=0x000000010007ed38
+ (id)_gkImageCacheKeyPathsByKey;	// IMP=0x000000010007ec00
- (id)_gkImageURLForSize:(long long)arg1 scale:(double)arg2;	// IMP=0x000000010007ee18
- (id)_gkImageURLForSize:(long long)arg1 scale:(double)arg2 foundSize:(out unsigned long long *)arg3;	// IMP=0x000000010007e928
@end

