//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSError.h>

@interface NSError (GameKitErrors)
+ (id)_gkUnauthenticatedError;	// IMP=0x0000000100074108
+ (id)serverErrorForCode:(long long)arg1 withReason:(id)arg2;	// IMP=0x0000000100074074
+ (id)serverErrorForCode:(long long)arg1 withUserInfo:(id)arg2;	// IMP=0x0000000100074050
+ (id)userErrorForServerCode:(long long)arg1 reason:(id)arg2 userInfo:(id)arg3;	// IMP=0x0000000100074010
+ (id)userErrorForServerCode:(long long)arg1 reason:(id)arg2;	// IMP=0x0000000100073fd8
+ (id)userErrorForServerError:(id)arg1 userInfo:(id)arg2;	// IMP=0x0000000100073c80
+ (id)userErrorForServerError:(id)arg1;	// IMP=0x0000000100073c40
+ (id)userErrorForCode:(long long)arg1 underlyingError:(id)arg2;	// IMP=0x0000000100073b9c
+ (id)userErrorForCode:(long long)arg1 userInfo:(id)arg2;	// IMP=0x0000000100073928
- (_Bool)_gkIsUnauthenticatedError;	// IMP=0x000000010007411c
@end

