//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSData, NSDictionary, NSString;

@protocol RDServer <NSObject>
- (void)reengageUserQuotaForPID:(int)arg1 completionHandler:(void (^)(NSError *))arg2;
- (void)suspendUserQuotaForPID:(int)arg1 completionHandler:(void (^)(NSError *))arg2;
- (void)removeUserSyncTask:(NSDictionary *)arg1 forPID:(int)arg2 completionHandler:(void (^)(NSError *))arg3;
- (void)addUserSyncTask:(NSDictionary *)arg1 forPID:(int)arg2 completionHandler:(void (^)(NSError *))arg3;
- (void)removeUserSyncTask:(NSDictionary *)arg1 forPID:(int)arg2;
- (void)addUserSyncTask:(NSDictionary *)arg1 forPID:(int)arg2;
- (void)fetchUserSwitchBlockingTaskListWithCompletionHandler:(void (^)(NSArray *))arg1;
- (void)removeUserSwitchBlockingTask:(NSDictionary *)arg1 forPID:(int)arg2 completionHandler:(void (^)(NSError *))arg3;
- (void)addUserSwitchBlockingTask:(NSDictionary *)arg1 forPID:(int)arg2 completionHandler:(void (^)(NSError *))arg3;
- (void)removeUserSwitchBlockingTask:(NSDictionary *)arg1 forPID:(int)arg2;
- (void)addUserSwitchBlockingTask:(NSDictionary *)arg1 forPID:(int)arg2;
- (void)resumeSyncBubbleForPID:(int)arg1 completionHandler:(void (^)(NSError *))arg2;
- (void)terminateSyncBubbleForPID:(int)arg1 completionHandler:(void (^)(NSError *))arg2;
- (void)loginUICheckinForPID:(int)arg1 completionHandler:(void (^)(NSError *))arg2;
- (void)loginComplete;
- (void)directSwitchToUser:(NSDictionary *)arg1 passcodeData:(NSData *)arg2 context:(NSData *)arg3 preferences:(NSDictionary *)arg4 pid:(int)arg5 completionHandler:(void (^)(NSError *))arg6;
- (void)logoutToLoginSessionWithPID:(int)arg1 completionHandler:(void (^)(NSError *))arg2;
- (void)switchToLoginUserWithPID:(int)arg1 completionHandler:(void (^)(NSError *))arg2;
- (void)switchToUser:(NSDictionary *)arg1 passcodeData:(NSData *)arg2 context:(NSData *)arg3 preferences:(NSDictionary *)arg4 pid:(int)arg5 completionHandler:(void (^)(NSError *))arg6;
- (void)switchToUser:(NSDictionary *)arg1 passcodeData:(NSData *)arg2 context:(NSData *)arg3 pid:(int)arg4 completionHandler:(void (^)(NSError *))arg5;
- (void)unregisterStakeholderForPID:(int)arg1 status:(unsigned long long)arg2 reason:(NSString *)arg3 completionHandler:(void (^)(NSError *))arg4;
- (void)registerUserSyncStakeholderForPID:(int)arg1 machServiceName:(NSString *)arg2 completionHandler:(void (^)(NSError *))arg3;
- (void)registerBubblePopStakeholderForPID:(int)arg1 completionHandler:(void (^)(NSError *))arg2;
- (void)registerCriticalUserSwitchStakeholderForPID:(int)arg1 completionHandler:(void (^)(NSError *))arg2;
- (void)registerUserSwitchStakeholderForPID:(int)arg1 completionHandler:(void (^)(NSError *))arg2;
@end

