//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "ASDownloadDelegate-Protocol.h"
#import "SSDownloadManagerObserver-Protocol.h"

@class NSDictionary, NSString;
@protocol ASDownload, OS_dispatch_queue;

@interface ASStoreServicesDownloadDelegate : NSObject <ASDownloadDelegate, SSDownloadManagerObserver>
{
    long long _downloadPersistentIdentifier;	// 8 = 0x8
    NSDictionary *_downloadOptions;	// 16 = 0x10
    id <ASDownload> _download;	// 24 = 0x18
    _Bool _isObserving;	// 32 = 0x20
    _Bool _downloadDidEnd;	// 33 = 0x21
    NSObject<OS_dispatch_queue> *_observationQueue;	// 40 = 0x28
}

@property(nonatomic) _Bool downloadDidEnd; // @synthesize downloadDidEnd=_downloadDidEnd;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *observationQueue; // @synthesize observationQueue=_observationQueue;
@property(nonatomic) _Bool isObserving; // @synthesize isObserving=_isObserving;
@property(retain, nonatomic) NSDictionary *downloadOptions; // @synthesize downloadOptions=_downloadOptions;
@property(nonatomic) __weak id <ASDownload> download; // @synthesize download=_download;
@property(readonly, nonatomic, getter=isStalled) _Bool stalled;
- (_Bool)downloadIsStalled:(id)arg1;	// IMP=0x000000010002c410
- (_Bool)downloadIsInFlight:(id)arg1;	// IMP=0x000000010002c31c
- (void)cancelAndFinishDownload:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010002c30c
- (void)cancelAndFinishDownload:(id)arg1 completion:(CDUnknownBlockType)arg2 attempts:(int)arg3;	// IMP=0x000000010002c058
- (id)findDownloadInManager;	// IMP=0x000000010002bedc
- (long long)downloadPersistentIdentifierFoundOnDownload:(id *)arg1;	// IMP=0x000000010002bae0
- (id)errorForDownloadError:(id)arg1;	// IMP=0x000000010002b7a0
- (void)updateOptionsForDownload:(id)arg1 options:(id)arg2;	// IMP=0x000000010002b6b8
- (void)moveDownloadToFrontOfQueue:(id)arg1;	// IMP=0x000000010002b564
- (void)cancelDownload:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010002b138
- (void)resumeDownload:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010002afac
- (void)pauseDownload:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010002ae30
- (_Bool)insertDownloadWithOptions:(id)arg1 error:(id *)arg2;	// IMP=0x000000010002aa80
- (void)applyDownloadOptions:(id)arg1 toDownload:(id)arg2 moveToFront:(_Bool *)arg3;	// IMP=0x000000010002a668
- (id)buildSSDownload:(_Bool *)arg1 withOptions:(id)arg2 error:(id *)arg3;	// IMP=0x000000010002a448
- (_Bool)_addDownloadURL:(id)arg1 withSize:(id)arg2 useStreamingZip:(_Bool)arg3 toDownload:(id)arg4 isLocalCacheServer:(_Bool)arg5 error:(id *)arg6;	// IMP=0x0000000100029fdc
- (void)startDownload:(id)arg1 withOptions:(id)arg2 inState:(id)arg3;	// IMP=0x0000000100029abc
- (void)downloadManager:(id)arg1 downloadStatesDidChange:(id)arg2;	// IMP=0x00000001000298d8
- (void)reportProgressOnDownload:(id)arg1;	// IMP=0x00000001000291c4
- (void)stopProgressAndFailDownload:(id)arg1 withError:(id)arg2;	// IMP=0x0000000100029058
- (long long)readDownloadPersistentIdentifierFromRepository:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100028e08
- (_Bool)writeDownloadPersistentIdentifier:(long long)arg1 intoAssetRepository:(id)arg2 error:(id *)arg3;	// IMP=0x0000000100028c48
- (id)downloadManager;	// IMP=0x0000000100028a64
- (void)stopObservingDownloadManager;	// IMP=0x0000000100028974
- (void)beginObservingDownloadManager;	// IMP=0x0000000100028884
- (void)dealloc;	// IMP=0x000000010002881c
- (id)init;	// IMP=0x00000001000287a8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

