//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

@interface MAAsset : NSObject
{
    NSDictionary *_attributes;	// 8 = 0x8
    NSString *_assetType;	// 16 = 0x10
    NSString *_assetId;	// 24 = 0x18
    long long _state;	// 32 = 0x20
}

+ (void)startCatalogDownload:(id)arg1 options:(id)arg2 then:(CDUnknownBlockType)arg3;	// IMP=0x00000001000052ac
+ (void)startCatalogDownload:(id)arg1 then:(CDUnknownBlockType)arg2;	// IMP=0x0000000100005290
@property(readonly, nonatomic) long long state; // @synthesize state=_state;
@property(readonly, nonatomic) NSString *assetId; // @synthesize assetId=_assetId;
@property(readonly, nonatomic) NSString *assetType; // @synthesize assetType=_assetType;
@property(readonly, nonatomic) NSDictionary *attributes; // @synthesize attributes=_attributes;
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000100006030
- (_Bool)refreshState;	// IMP=0x0000000100005e58
- (_Bool)spaceCheck:(long long *)arg1;	// IMP=0x0000000100005c88
- (long long)configDownloadSync:(id)arg1;	// IMP=0x0000000100005ae0
- (void)configDownload:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000059b4
- (long long)cancelDownloadSync;	// IMP=0x000000010000582c
- (void)cancelDownload:(CDUnknownBlockType)arg1;	// IMP=0x00000001000056e0
- (long long)purgeSync;	// IMP=0x0000000100005558
- (void)purge:(CDUnknownBlockType)arg1;	// IMP=0x000000010000540c
- (void)commonAssetDownload:(id)arg1 options:(id)arg2 then:(CDUnknownBlockType)arg3;	// IMP=0x0000000100004e8c
- (long long)calculateTimeout;	// IMP=0x0000000100004ddc
- (void)startDownload:(id)arg1 then:(CDUnknownBlockType)arg2;	// IMP=0x0000000100004d4c
- (void)startDownload:(CDUnknownBlockType)arg1;	// IMP=0x0000000100004d00
- (id)createExtractor;	// IMP=0x0000000100004b5c
- (id)hashToString:(id)arg1;	// IMP=0x0000000100004a94
- (void)startDownloadWithExtractor:(CDUnknownBlockType)arg1 options:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0000000100004960
- (void)startDownloadWithExtractor:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010000494c
- (void)logAsset;	// IMP=0x00000001000048c4
- (id)assetProperty:(id)arg1;	// IMP=0x00000001000048ac
- (id)getLocalUrl;	// IMP=0x0000000100004848
- (id)getLocalFileUrl;	// IMP=0x00000001000047fc
- (void)attachProgressCallBack:(CDUnknownBlockType)arg1;	// IMP=0x000000010000472c
- (id)assetServerUrl;	// IMP=0x000000010000468c
- (void)dealloc;	// IMP=0x0000000100004608
- (id)initWithAttributes:(id)arg1;	// IMP=0x00000001000044e4

@end

