//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SignpostSupport/SignpostSupportObject.h>

@interface SignpostSupportObject (CoreAnalyticsReporting)
- (_Bool)canGenerateCoreAnalyticsPayload;	// IMP=0x0000000100009c6c
- (id)coreAnalyticsPayload;	// IMP=0x0000000100009c64
@end

