//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@class NSSet, NSString;

__attribute__((visibility("hidden")))
@interface SecCDKeychainManagedAccessControlEntity : NSManagedObject
{
}

+ (id)fetchRequest;	// IMP=0x000000010005a534

// Remaining properties
@property(retain, nonatomic) NSSet *accessedItems; // @dynamic accessedItems;
@property(retain, nonatomic) NSSet *ownedItems; // @dynamic ownedItems;
@property(copy, nonatomic) NSString *stringRepresentation; // @dynamic stringRepresentation;
@property(nonatomic) int type; // @dynamic type;

@end

