//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString, SecDbKeychainMetadata, SecDbKeychainSecretData;

__attribute__((visibility("hidden")))
@interface SecDbKeychainItemV7 : NSObject
{
    SecDbKeychainSecretData *_encryptedSecretData;	// 8 = 0x8
    SecDbKeychainMetadata *_encryptedMetadata;	// 16 = 0x10
    NSDictionary *_secretAttributes;	// 24 = 0x18
    NSDictionary *_metadataAttributes;	// 32 = 0x20
    NSString *_tamperCheck;	// 40 = 0x28
    int _keyclass;	// 48 = 0x30
    int _keybag;	// 52 = 0x34
}

+ (id)decryptionOperation;	// IMP=0x000000010003a160
+ (id)encryptionOperation;	// IMP=0x000000010003a0ec
+ (id)keySpecifier;	// IMP=0x000000010003a0ac
+ (_Bool)aksDecryptWithKeybag:(int)arg1 keyclass:(int)arg2 wrappedKeyData:(id)arg3 outKeyclass:(int *)arg4 unwrappedKey:(id)arg5 error:(id *)arg6;	// IMP=0x0000000100039f98
+ (_Bool)aksEncryptWithKeybag:(int)arg1 keyclass:(int)arg2 keyData:(id)arg3 outKeyclass:(int *)arg4 wrappedKey:(id)arg5 error:(id *)arg6;	// IMP=0x0000000100039e84
@property(readonly, nonatomic) int keyclass; // @synthesize keyclass=_keyclass;
- (void).cxx_destruct;	// IMP=0x0000000100039d90
- (id)unwrapFromAKS:(id)arg1 accessControl:(struct __SecAccessControl *)arg2 acmContext:(id)arg3 callerAccessGroups:(id)arg4 delete:(_Bool)arg5 error:(id *)arg6;	// IMP=0x00000001000395fc
- (id)wrapToAKS:(id)arg1 withKeybag:(int)arg2 accessControl:(struct __SecAccessControl *)arg3 acmContext:(id)arg4 error:(id *)arg5;	// IMP=0x0000000100039078
- (id)metadataClassKeyWithKeybag:(int)arg1 createKeyIfMissing:(_Bool)arg2 overwriteCorruptKey:(_Bool)arg3 error:(id *)arg4;	// IMP=0x0000000100038fa4
- (_Bool)encryptSecretDataWithKeybag:(int)arg1 accessControl:(struct __SecAccessControl *)arg2 acmContext:(id)arg3 error:(id *)arg4;	// IMP=0x0000000100038cdc
- (_Bool)encryptMetadataWithKeybag:(int)arg1 error:(id *)arg2;	// IMP=0x0000000100038a50
- (id)encryptedSecretDataBlob;	// IMP=0x0000000100038a38
- (id)encryptedMetadataBlob;	// IMP=0x0000000100038a20
- (id)encryptedBlobWithKeybag:(int)arg1 accessControl:(struct __SecAccessControl *)arg2 acmContext:(id)arg3 error:(id *)arg4;	// IMP=0x0000000100038814
- (_Bool)deleteWithAcmContext:(id)arg1 accessControl:(struct __SecAccessControl *)arg2 callerAccessGroups:(id)arg3 error:(id *)arg4;	// IMP=0x00000001000386b0
- (id)secretAttributesWithAcmContext:(id)arg1 accessControl:(struct __SecAccessControl *)arg2 callerAccessGroups:(id)arg3 error:(id *)arg4;	// IMP=0x0000000100038280
- (id)metadataAttributesWithError:(id *)arg1;	// IMP=0x0000000100037cf4
- (id)initWithSecretAttributes:(id)arg1 metadataAttributes:(id)arg2 tamperCheck:(id)arg3 keyclass:(int)arg4;	// IMP=0x0000000100037a78
- (id)initWithData:(id)arg1 decryptionKeybag:(int)arg2 error:(id *)arg3;	// IMP=0x00000001000377b4

@end

