//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSArray, NSString, _SFAccessPolicy, _SFCredential;

@protocol SFKeychainServerProtocol
- (void)rpcReplaceOldCredential:(_SFCredential *)arg1 withNewCredential:(_SFCredential *)arg2 reply:(void (^)(NSString *, NSError *))arg3;
- (void)rpcRemoveCredentialWithPersistentIdentifier:(NSString *)arg1 reply:(void (^)(_Bool, NSError *))arg2;
- (void)rpcLookupCredentialsForServiceIdentifiers:(NSArray *)arg1 reply:(void (^)(NSArray *, NSError *))arg2;
- (void)rpcFetchPasswordCredentialForPersistentIdentifier:(NSString *)arg1 reply:(void (^)(_SFPasswordCredential *, NSString *, NSError *))arg2;
- (void)rpcAddCredential:(_SFCredential *)arg1 withAccessPolicy:(_SFAccessPolicy *)arg2 reply:(void (^)(NSString *, NSError *))arg3;
@end

