//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Jun 10 2020 10:03:13).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SOSControlProtocol-Protocol.h"

@class NSString, NSXPCConnection, SOSAccount;

__attribute__((visibility("hidden")))
@interface SOSClient : NSObject <SOSControlProtocol>
{
    SOSAccount *_account;	// 8 = 0x8
    NSXPCConnection *_connection;	// 16 = 0x10
}

@property __weak NSXPCConnection *connection; // @synthesize connection=_connection;
@property(retain) SOSAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;	// IMP=0x00000001000a8f58
- (void)setWatchdogParmeters:(id)arg1 complete:(CDUnknownBlockType)arg2;	// IMP=0x00000001000a8ed4
- (void)getWatchdogParameters:(CDUnknownBlockType)arg1;	// IMP=0x00000001000a8e6c
- (void)triggerSync:(id)arg1 complete:(CDUnknownBlockType)arg2;	// IMP=0x00000001000a8d88
- (void)importInitialSyncCredentials:(id)arg1 complete:(CDUnknownBlockType)arg2;	// IMP=0x00000001000a8ca4
- (void)initialSyncCredentials:(unsigned int)arg1 complete:(CDUnknownBlockType)arg2;	// IMP=0x00000001000a8bc8
- (void)joinCircleWithBlob:(id)arg1 version:(int)arg2 complete:(CDUnknownBlockType)arg3;	// IMP=0x00000001000a8b34
- (void)circleJoiningBlob:(id)arg1 complete:(CDUnknownBlockType)arg2;	// IMP=0x00000001000a8ab0
- (void)myPeerInfo:(CDUnknownBlockType)arg1;	// IMP=0x00000001000a8a48
- (void)stashAccountCredential:(id)arg1 complete:(CDUnknownBlockType)arg2;	// IMP=0x00000001000a89c4
- (void)validatedStashedAccountCredential:(CDUnknownBlockType)arg1;	// IMP=0x00000001000a895c
- (void)assertStashedAccountCredential:(CDUnknownBlockType)arg1;	// IMP=0x00000001000a88f4
- (void)stashedCredentialPublicKey:(CDUnknownBlockType)arg1;	// IMP=0x00000001000a888c
- (void)rateLimitingPerformanceCounters:(CDUnknownBlockType)arg1;	// IMP=0x00000001000a8824
- (void)kvsPerformanceCounters:(CDUnknownBlockType)arg1;	// IMP=0x00000001000a87bc
- (void)userPublicKey:(CDUnknownBlockType)arg1;	// IMP=0x00000001000a8754
- (_Bool)checkEntitlement:(id)arg1;	// IMP=0x00000001000a85e8
- (id)initWithConnection:(id)arg1 account:(id)arg2;	// IMP=0x00000001000a8540

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

