//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVPSharedPSAlbumDescriptionView.h"

@class NSMutableDictionary, UIImage;

@interface TVPFolderCell : TVPSharedPSAlbumDescriptionView
{
    UIImage *_backgroundImage;	// 8 = 0x8
    NSMutableDictionary *__photoCells;	// 16 = 0x10
}

@property(readonly, nonatomic) NSMutableDictionary *_photoCells; // @synthesize _photoCells=__photoCells;
@property(retain, nonatomic) UIImage *backgroundImage; // @synthesize backgroundImage=_backgroundImage;
- (void).cxx_destruct;	// IMP=0x0000000100058bd0
- (id)_drawImage;	// IMP=0x000000010005894c
- (struct CGRect)_squareCropForImage:(id)arg1;	// IMP=0x00000001000588a8
- (void)updateFolderImage;	// IMP=0x00000001000586f4
- (void)setImage:(id)arg1 forQuadrant:(long long)arg2;	// IMP=0x000000010005865c
- (void)layoutSubviews;	// IMP=0x0000000100058628
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000585a8

@end

