//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSURL;

@interface TVPMediaURLCacheRecord : NSObject
{
    NSURL *_url;	// 8 = 0x8
    NSDate *_expiration;	// 16 = 0x10
}

@property(retain, nonatomic) NSDate *expiration; // @synthesize expiration=_expiration;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
- (void).cxx_destruct;	// IMP=0x0000000100020ee0

@end

