//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIPresentationController.h"

@class UIVisualEffectView;

@interface TVPModalPresentationController : UIPresentationController
{
    UIVisualEffectView *_visualEffectView;	// 8 = 0x8
    long long _blurStyle;	// 16 = 0x10
}

@property(readonly, nonatomic) long long blurStyle; // @synthesize blurStyle=_blurStyle;
@property(readonly, nonatomic) UIVisualEffectView *visualEffectView; // @synthesize visualEffectView=_visualEffectView;
- (void).cxx_destruct;	// IMP=0x0000000100035708
- (void)_animateWithCoordinator:(id)arg1 isPresenting:(_Bool)arg2;	// IMP=0x00000001000353d4
- (void)_configureSubviews;	// IMP=0x000000010003530c
- (void)dismissalTransitionWillBegin;	// IMP=0x0000000100035284
- (void)presentationTransitionWillBegin;	// IMP=0x00000001000351fc
- (id)initWithPresentedViewController:(id)arg1 presentingViewController:(id)arg2;	// IMP=0x000000010003519c
- (id)initWithPresentedViewController:(id)arg1 presentingViewController:(id)arg2 blurStyle:(long long)arg3;	// IMP=0x0000000100035118

@end

