//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIApplication.h"

@interface MTApplication : UIApplication
{
    id <UIApplicationDelegate> _strongDelegate;	// 8 = 0x8
}

+ (_Bool)handleTextViewURL:(id)arg1 interaction:(long long)arg2;	// IMP=0x00000001000461e8
+ (id)appController;	// IMP=0x000000010004616c
+ (id)sharedApplication;	// IMP=0x0000000100046138
@property(retain, nonatomic) id <UIApplicationDelegate> strongDelegate; // @synthesize strongDelegate=_strongDelegate;
- (void).cxx_destruct;	// IMP=0x00000001000465c4
- (void)openURL:(id)arg1 options:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0000000100046450
- (_Bool)openURL:(id)arg1;	// IMP=0x000000010004639c
- (_Bool)isRunningInStoreDemoMode;	// IMP=0x0000000100046328
- (void)setDelegate:(id)arg1;	// IMP=0x00000001000462b0
- (id)delegate;	// IMP=0x000000010004627c

@end

