//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@class NSString;

@interface MTArtworkView : UIImageView
{
    _Bool _observingArtworkChangeNotifications;	// 8 = 0x8
    _Bool _enabled;	// 9 = 0x9
    NSString *_artworkKey;	// 16 = 0x10
}

@property(nonatomic, getter=isEnabled) _Bool enabled; // @synthesize enabled=_enabled;
- (void).cxx_destruct;	// IMP=0x00000001000ab5b0
- (void)_reloadArtwork;	// IMP=0x00000001000ab280
- (void)_stopObservingArtworkChangeNotifications;	// IMP=0x00000001000ab210
- (void)_startObservingArtworkChangeNotifications;	// IMP=0x00000001000ab194
- (void)_artworkDidChange:(id)arg1;	// IMP=0x00000001000ab108
- (void)_artworkKeyDidChange;	// IMP=0x00000001000ab094
- (void)_artworkSizeDidChange;	// IMP=0x00000001000ab088
- (void)setBounds:(struct CGRect)arg1;	// IMP=0x00000001000aafd0
- (void)setFrame:(struct CGRect)arg1;	// IMP=0x00000001000aaf18
@property(readonly, nonatomic, getter=isPlaceholder) _Bool placeholder;
@property(retain, nonatomic) NSString *artworkKey; // @synthesize artworkKey=_artworkKey;
- (void)dealloc;	// IMP=0x00000001000aad78
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000aabc4

@end

