//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSMutableCopying.h"

@class NSArray, NSString;

@interface MTAssistantRemoteControlDestination : NSObject <NSMutableCopying>
{
    NSString *_appBundleID;	// 8 = 0x8
    NSString *_playerID;	// 16 = 0x10
    void *_origin;	// 24 = 0x18
    NSArray *_outputDeviceUIDs;	// 32 = 0x20
    void *_outputGroup;	// 40 = 0x28
}

+ (id)watchRadioApplicationDestination;	// IMP=0x00000001000d20b8
+ (id)systemPodcastsApplicationDestination;	// IMP=0x00000001000d206c
+ (id)systemMediaApplicationDestination;	// IMP=0x00000001000d2020
@property(readonly, nonatomic) void *outputGroup; // @synthesize outputGroup=_outputGroup;
@property(readonly, nonatomic) NSArray *outputDeviceUIDs; // @synthesize outputDeviceUIDs=_outputDeviceUIDs;
@property(readonly, nonatomic) void *origin; // @synthesize origin=_origin;
@property(readonly, nonatomic) NSString *playerID; // @synthesize playerID=_playerID;
@property(readonly, nonatomic) NSString *appBundleID; // @synthesize appBundleID=_appBundleID;
- (void).cxx_destruct;	// IMP=0x00000001000d256c
- (id)_copyWithZone:(struct _NSZone *)arg1 usingConcreteClass:(Class)arg2;	// IMP=0x00000001000d2448
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001000d2400
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001000d23c0
- (void *)createPlayerPath;	// IMP=0x00000001000d233c
- (id)description;	// IMP=0x00000001000d2270
- (void)dealloc;	// IMP=0x00000001000d221c
- (id)init;	// IMP=0x00000001000d2204
- (id)initWithAppBundleID:(id)arg1;	// IMP=0x00000001000d21f0
- (id)initWithAppBundleID:(id)arg1 playerID:(id)arg2 origin:(void *)arg3;	// IMP=0x00000001000d20f4

@end

