//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTResultsController.h"

@class MTPlayerItem, NSArray;

@interface MTChapterResultsController : MTResultsController
{
    MTPlayerItem *_currentItem;	// 8 = 0x8
    NSArray *_chapters;	// 16 = 0x10
}

@property(retain, nonatomic) NSArray *chapters; // @synthesize chapters=_chapters;
@property(retain, nonatomic) MTPlayerItem *currentItem; // @synthesize currentItem=_currentItem;
- (void).cxx_destruct;	// IMP=0x000000010011f3b8
- (void)didLoadChapters;	// IMP=0x000000010011efd4
- (id)allObjects;	// IMP=0x000000010011efc8
- (unsigned long long)numberOfObjectsInSection:(unsigned long long)arg1;	// IMP=0x000000010011ef7c
- (id)indexPathForObject:(id)arg1;	// IMP=0x000000010011eeec
- (id)objectAtIndexPath:(id)arg1;	// IMP=0x000000010011ee50
- (void)reloadData;	// IMP=0x000000010011ec40
- (void)dealloc;	// IMP=0x000000010011ebc8
- (id)init;	// IMP=0x000000010011ea50

@end

