//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MTCollectionViewCell;

@protocol MTCollectionViewCellDelegate <NSObject>
- (void)cellDidPressDelete:(MTCollectionViewCell *)arg1;

@optional
- (void)cellDidPressMore:(MTCollectionViewCell *)arg1;
@end

