//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MTEpisodeCell;

@protocol MTEpisodeCellDelegate <NSObject>
- (void)cellDidChangeSize:(MTEpisodeCell *)arg1;
- (void)cell:(MTEpisodeCell *)arg1 moreButtonTapped:(id)arg2;
@end

