//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTPodcastIdentifier.h"

@class NSNumber, NSString;

@protocol MTEpisodeIdentifier <MTPodcastIdentifier>
@property(readonly, nonatomic) NSNumber *episodeSerpentID;
@property(readonly, nonatomic) NSNumber *episodeAdamID;
@property(readonly, nonatomic) NSString *episodeGUID;
@property(readonly, nonatomic) NSString *episodeUUID;
@end

