//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MTEpisodeIdentifier.h"
#import "MTPodcastIdentifier.h"

@class NSNumber, NSString;

@interface MTEpisodeIdentifier : NSObject <MTEpisodeIdentifier, MTPodcastIdentifier>
{
    NSString *_episodeUUID;	// 8 = 0x8
    NSString *_episodeGUID;	// 16 = 0x10
    NSNumber *_episodeAdamID;	// 24 = 0x18
    NSNumber *_episodeSerpentID;	// 32 = 0x20
    NSString *_podcastUUID;	// 40 = 0x28
    NSNumber *_podcastAdamID;	// 48 = 0x30
    NSString *_currentPodcastFeedURL;	// 56 = 0x38
    NSString *_originalPodcastFeedURL;	// 64 = 0x40
}

+ (id)identifierWithPlayerItem:(id)arg1;	// IMP=0x00000001000243a8
+ (id)identifierWithEpisode:(id)arg1;	// IMP=0x0000000100024338
@property(copy, nonatomic) NSString *originalPodcastFeedURL; // @synthesize originalPodcastFeedURL=_originalPodcastFeedURL;
@property(copy, nonatomic) NSString *currentPodcastFeedURL; // @synthesize currentPodcastFeedURL=_currentPodcastFeedURL;
@property(retain, nonatomic) NSNumber *podcastAdamID; // @synthesize podcastAdamID=_podcastAdamID;
@property(copy, nonatomic) NSString *podcastUUID; // @synthesize podcastUUID=_podcastUUID;
@property(retain, nonatomic) NSNumber *episodeSerpentID; // @synthesize episodeSerpentID=_episodeSerpentID;
@property(retain, nonatomic) NSNumber *episodeAdamID; // @synthesize episodeAdamID=_episodeAdamID;
@property(copy, nonatomic) NSString *episodeGUID; // @synthesize episodeGUID=_episodeGUID;
@property(copy, nonatomic) NSString *episodeUUID; // @synthesize episodeUUID=_episodeUUID;
- (void).cxx_destruct;	// IMP=0x0000000100024be0
- (_Bool)_hasFeedURL:(id)arg1;	// IMP=0x0000000100024a28
- (void)_updateWithPodcast:(id)arg1;	// IMP=0x00000001000248c8
- (id)initWithPlayerItem:(id)arg1;	// IMP=0x0000000100024614
- (id)initWithEpisode:(id)arg1;	// IMP=0x0000000100024418

@end

