//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "NSFetchedResultsControllerDelegate.h"

@class NSArray, NSFetchedResultsController, NSPredicate, NSString, UIBarButtonItem;

@interface MTFetchedTableViewController : UITableViewController <NSFetchedResultsControllerDelegate>
{
    long long _userDrivenCounter;	// 8 = 0x8
    UIBarButtonItem *_editButtonItem_localIvar;	// 16 = 0x10
    _Bool _inSwipeToDeleteMode;	// 24 = 0x18
    NSString *_fetchEntityName;	// 32 = 0x20
    NSPredicate *_fetchPredicate;	// 40 = 0x28
    NSArray *_sortDescriptors;	// 48 = 0x30
    NSString *_sectionName;	// 56 = 0x38
    long long _rowAnimation;	// 64 = 0x40
    NSFetchedResultsController *_frc;	// 72 = 0x48
    NSString *_sectionNameKeyPath;	// 80 = 0x50
}

@property(retain, nonatomic) NSString *sectionNameKeyPath; // @synthesize sectionNameKeyPath=_sectionNameKeyPath;
@property(nonatomic) _Bool inSwipeToDeleteMode; // @synthesize inSwipeToDeleteMode=_inSwipeToDeleteMode;
@property(retain, nonatomic) NSFetchedResultsController *frc; // @synthesize frc=_frc;
@property(nonatomic) long long rowAnimation; // @synthesize rowAnimation=_rowAnimation;
@property(retain, nonatomic) NSString *sectionName; // @synthesize sectionName=_sectionName;
@property(retain, nonatomic) NSArray *sortDescriptors; // @synthesize sortDescriptors=_sortDescriptors;
@property(retain, nonatomic) NSPredicate *fetchPredicate; // @synthesize fetchPredicate=_fetchPredicate;
@property(retain, nonatomic) NSString *fetchEntityName; // @synthesize fetchEntityName=_fetchEntityName;
- (void).cxx_destruct;	// IMP=0x0000000100013de8
- (void)decodeRestorableStateWithCoder:(id)arg1;	// IMP=0x0000000100013c90
- (void)encodeRestorableStateWithCoder:(id)arg1;	// IMP=0x0000000100013c5c
- (void)reloadVisibleCellsWithAnimation:(long long)arg1;	// IMP=0x0000000100013bbc
- (void)_updateTableAnimated:(_Bool)arg1;	// IMP=0x0000000100013358
- (_Bool)hasSectionNameKeyPathChanged;	// IMP=0x0000000100013274
- (id)fetchRequestInManagedObjectContext:(id)arg1;	// IMP=0x00000001000130c0
- (void)controller:(id)arg1 didChangeSection:(id)arg2 atIndex:(unsigned long long)arg3 forChangeType:(unsigned long long)arg4;	// IMP=0x0000000100012fe0
- (void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned long long)arg4 newIndexPath:(id)arg5;	// IMP=0x0000000100012de4
- (void)setRefreshControl:(id)arg1;	// IMP=0x0000000100012ce4
- (void)controllerDidChangeContent:(id)arg1;	// IMP=0x0000000100012c80
- (void)controllerWillChangeContent:(id)arg1;	// IMP=0x0000000100012c1c
- (id)newCellInstanceWithReuseIdentifier:(id)arg1;	// IMP=0x0000000100012bb0
- (void)configureCell:(id)arg1 withObject:(id)arg2 atIndexPath:(id)arg3;	// IMP=0x0000000100012bac
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x0000000100012a74
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x00000001000129d4
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x0000000100012960
- (void)tableView:(id)arg1 didEndEditingRowAtIndexPath:(id)arg2;	// IMP=0x0000000100012924
- (void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;	// IMP=0x0000000100012900
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;	// IMP=0x0000000100012828
- (id)reuseIdentifierForRow:(id)arg1;	// IMP=0x000000010001280c
- (void)refetchWithPredicate:(id)arg1 sortDescriptors:(id)arg2 animated:(_Bool)arg3;	// IMP=0x00000001000126e4
- (void)refetchWithPredicate:(id)arg1;	// IMP=0x0000000100012630
- (void)refetchWithSortDescriptors:(id)arg1 animated:(_Bool)arg2;	// IMP=0x0000000100012570
- (void)viewDidLoad;	// IMP=0x00000001000124cc
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x0000000100012498
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100012444
@property(nonatomic) _Bool changeIsUserDriven; // @dynamic changeIsUserDriven;
- (void)initializeFrc;	// IMP=0x000000010001228c
- (void)didReceiveMemoryWarning;	// IMP=0x0000000100012258
- (void)dealloc;	// IMP=0x00000001000121fc
- (id)initWithEntityName:(id)arg1;	// IMP=0x00000001000121e8
- (id)initWithEntityName:(id)arg1 predicate:(id)arg2 sortDescriptors:(id)arg3;	// IMP=0x00000001000120bc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

