//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTTableViewCell.h"

@class UILabel;

@interface MTInformativeTableViewCell : MTTableViewCell
{
    UILabel *_messageLabel;	// 24 = 0x18
}

@property(retain, nonatomic) UILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
- (void).cxx_destruct;	// IMP=0x000000010017f41c
- (struct CGSize)fittingSize;	// IMP=0x000000010017f3b8
- (void)layoutSubviews;	// IMP=0x000000010017f2cc
- (void)setupCell;	// IMP=0x000000010017ec54

@end

