//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTListResultsController.h"

@interface MTPlayHistoryResultsController : MTListResultsController
{
    unsigned long long _newCount;	// 8 = 0x8
    unsigned long long _previousCount;	// 16 = 0x10
}

+ (id)fetchRequestForHistory;	// IMP=0x00000001001092d8
+ (id)predicateForHistory;	// IMP=0x00000001001090d8
+ (id)invertIndexPath:(id)arg1 withCount:(unsigned long long)arg2;	// IMP=0x0000000100109018
+ (unsigned long long)invertIndex:(unsigned long long)arg1 withCount:(unsigned long long)arg2;	// IMP=0x000000010010900c
@property(nonatomic) unsigned long long previousCount; // @synthesize previousCount=_previousCount;
@property(nonatomic) unsigned long long newCount; // @synthesize newCount=_newCount;
- (void)reloadData;	// IMP=0x0000000100108eb0
- (void)generator:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned long long)arg4 newIndexPath:(id)arg5;	// IMP=0x0000000100108d3c
- (void)setObjects:(id)arg1;	// IMP=0x0000000100108c64
- (id)indexPathForObject:(id)arg1;	// IMP=0x0000000100108bbc
- (id)objectAtIndexPath:(id)arg1;	// IMP=0x0000000100108af8
- (void)currentItemDidChange;	// IMP=0x0000000100108a90
- (id)init;	// IMP=0x0000000100108914

@end

