//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MTPlaybackQueueFactory : NSObject
{
}

+ (id)_uuidForEpisode:(id)arg1;	// IMP=0x00000001001a886c
+ (id)_latestOrOldestEpisodeForPodcastUuid:(id)arg1 restrictToUserEpisodes:(_Bool)arg2 excludeExplicit:(long long)arg3 latest:(_Bool)arg4 ctx:(id)arg5;	// IMP=0x00000001001a85d0
+ (id)_oldestEpisodeForPodcastUuid:(id)arg1 restrictToUserEpisodes:(_Bool)arg2 excludeExplicit:(long long)arg3 ctx:(id)arg4;	// IMP=0x00000001001a8550
+ (id)_latestEpisodeForPodcastUuid:(id)arg1 restrictToUserEpisodes:(_Bool)arg2 excludeExplicit:(long long)arg3 ctx:(id)arg4;	// IMP=0x00000001001a84d0
+ (id)_episodeToPlayForPodcastUuid:(id)arg1 playbackOrder:(long long)arg2 excludeExplicit:(long long)arg3 ctx:(id)arg4;	// IMP=0x00000001001a82a4
+ (id)episodeUuidsForPlayStationUuid:(id)arg1 limit:(long long)arg2;	// IMP=0x00000001001a7e24
+ (id)episodeUuidsForPlayPodcastUuid:(id)arg1 order:(long long)arg2 limit:(long long)arg3 error:(long long *)arg4;	// IMP=0x00000001001a7794
+ (_Bool)_isContinuousPlaybackEnabledForLimit:(long long)arg1;	// IMP=0x00000001001a7710
+ (id)_manifestForPlayMyOldestPodcasts;	// IMP=0x00000001001a76c0
+ (id)_manifestForPlayMyLatestPodcasts;	// IMP=0x00000001001a7670
+ (id)_manifestForPlayMyPodcasts;	// IMP=0x00000001001a75dc
+ (id)playEpisodeUuid:(id)arg1 context:(long long)arg2 sortType:(long long)arg3 limit:(long long)arg4;	// IMP=0x00000001001a71f4
+ (id)playEpisodeUuid:(id)arg1 context:(long long)arg2 limit:(long long)arg3;	// IMP=0x00000001001a71e0
+ (id)playEpisodeUuid:(id)arg1 limit:(long long)arg2;	// IMP=0x00000001001a71cc
+ (id)playEpisodeUuid:(id)arg1 context:(long long)arg2;	// IMP=0x00000001001a71bc
+ (id)playEpisodeUuid:(id)arg1;	// IMP=0x00000001001a71ac
+ (id)playStationUuid:(id)arg1 episodeUuid:(id)arg2 limit:(long long)arg3;	// IMP=0x00000001001a6e9c
+ (id)playStationUuid:(id)arg1 limit:(long long)arg2;	// IMP=0x00000001001a6e88
+ (id)playStationUuid:(id)arg1 episodeUuid:(id)arg2;	// IMP=0x00000001001a6e20
+ (id)playStationUuid:(id)arg1;	// IMP=0x00000001001a6e10
+ (id)playPodcastUuid:(id)arg1 order:(long long)arg2 limit:(long long)arg3;	// IMP=0x00000001001a6e00
+ (id)playPodcastUuid:(id)arg1 order:(long long)arg2 limit:(long long)arg3 error:(long long *)arg4;	// IMP=0x00000001001a6b08
+ (id)playPodcastUuid:(id)arg1 limit:(long long)arg2;	// IMP=0x00000001001a6af4
+ (id)playPodcastUuid:(id)arg1 order:(long long)arg2;	// IMP=0x00000001001a6ae4
+ (id)playPodcastUuid:(id)arg1;	// IMP=0x00000001001a6ad4
+ (id)playMyPodcastsWithOrder:(long long)arg1;	// IMP=0x00000001001a6a78
+ (id)playListenNow;	// IMP=0x00000001001a67d0

@end

