//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSObject<NSCopying>;

@interface MTResultsChangeWrapper : NSObject <NSCopying>
{
    NSObject<NSCopying> *_object;	// 8 = 0x8
}

@property(retain, nonatomic) NSObject<NSCopying> *object; // @synthesize object=_object;
- (void).cxx_destruct;	// IMP=0x000000010017a114
- (unsigned long long)hash;	// IMP=0x000000010017a0a4
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000100179fb8
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100179f44
- (id)initWithObject:(id)arg1;	// IMP=0x0000000100179ed0

@end

