//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MTShowSettings : NSObject
{
    _Bool _episodeOrderAscending;	// 8 = 0x8
    int _downloadEpisodes;	// 12 = 0xc
    long long _deletePlayedEpisodes;	// 16 = 0x10
    long long _episodeLimit;	// 24 = 0x18
    long long _updateInterval;	// 32 = 0x20
}

@property(nonatomic) long long updateInterval; // @synthesize updateInterval=_updateInterval;
@property(nonatomic) long long episodeLimit; // @synthesize episodeLimit=_episodeLimit;
@property(nonatomic) long long deletePlayedEpisodes; // @synthesize deletePlayedEpisodes=_deletePlayedEpisodes;
@property(nonatomic) int downloadEpisodes; // @synthesize downloadEpisodes=_downloadEpisodes;
@property(nonatomic) _Bool episodeOrderAscending; // @synthesize episodeOrderAscending=_episodeOrderAscending;

@end

