//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MTSubscribeUtil : NSObject
{
}

+ (id)identifierForDictionary:(id)arg1;	// IMP=0x0000000100017ba0
+ (_Bool)isSubscribedToPodcastWithStorePlatformDictionary:(id)arg1;	// IMP=0x0000000100017934
+ (void)unsubscribeToPodcastWithStorePlatformDictionary:(id)arg1;	// IMP=0x00000001000176f4
+ (void)subscribeToPodcastWithStorePlatformDictionary:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100017028

@end

