//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTLibraryQuery.h"

@interface MTTextQuery : MTLibraryQuery
{
}

- (id)titleForPodcastUuid:(id)arg1;	// IMP=0x000000010003fdac
- (void)runQueryWithText:(id)arg1;	// IMP=0x000000010003f6b4

@end

