//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class NSTimer;

@interface MTTimedOperation : NSOperation
{
    NSTimer *_optimer;	// 24 = 0x18
    CDUnknownBlockType _mainBlock;	// 32 = 0x20
    _Bool _executing;	// 40 = 0x28
    _Bool _finished;	// 41 = 0x29
    int _operationType;	// 44 = 0x2c
    double _timeout;	// 48 = 0x30
}

@property(nonatomic) int operationType; // @synthesize operationType=_operationType;
@property(nonatomic) double timeout; // @synthesize timeout=_timeout;
@property(readonly, nonatomic) _Bool isFinished; // @synthesize isFinished=_finished;
@property(readonly, nonatomic) _Bool isExecuting; // @synthesize isExecuting=_executing;
- (void).cxx_destruct;	// IMP=0x00000001000b88bc
- (void)setMainBlock:(CDUnknownBlockType)arg1;	// IMP=0x00000001000b8824
- (void)cancel;	// IMP=0x00000001000b87cc
- (void)main;	// IMP=0x00000001000b87c0
- (void)scheduleTimer;	// IMP=0x00000001000b86f8
- (void)performMain:(id)arg1;	// IMP=0x00000001000b8654
- (void)start;	// IMP=0x00000001000b85ac
- (void)finish;	// IMP=0x00000001000b84b4
- (_Bool)isConcurrent;	// IMP=0x00000001000b84ac
- (id)init;	// IMP=0x00000001000b844c

@end

