//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@interface MTTVSettingsTableViewCell : UITableViewCell
{
}

+ (id)reuseIdentifier;	// IMP=0x0000000100005664
+ (double)height;	// IMP=0x0000000100005658
- (void)updateColors;	// IMP=0x0000000100005d80
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x0000000100005d08
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x0000000100005c40
- (void)layoutSubviews;	// IMP=0x00000001000059b0
- (void)prepareForReuse;	// IMP=0x00000001000058d8
- (void)configureSubviews;	// IMP=0x0000000100005720
- (id)init;	// IMP=0x0000000100005690

@end

