//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TVImageLoader.h"

@class NSString;

@interface MTTVMusicMPArtworkCatalogLoader : NSObject <TVImageLoader>
{
}

+ (id)sharedInstance;	// IMP=0x00000001001a2128
- (id)_identifierForMPModelObject:(id)arg1;	// IMP=0x00000001001a3068
- (void)cancelLoad:(id)arg1;	// IMP=0x00000001001a3064
- (id)_loadArtworkForMPObject:(id)arg1 scaleToSize:(struct CGSize)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x00000001001a2c98
- (id)loadImageForObject:(id)arg1 scaleToSize:(struct CGSize)arg2 cropToFit:(_Bool)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x00000001001a2360
- (id)imageKeyForObject:(id)arg1;	// IMP=0x00000001001a21a8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

