//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTSpecialIndexPathTableViewController.h"

@class NSMutableSet, NSString;

@interface MTTVStationSelectPodcastsListViewController : MTSpecialIndexPathTableViewController
{
    _Bool _allPodcastsSelected;	// 8 = 0x8
    NSString *_playlistName;	// 16 = 0x10
    NSMutableSet *_podcastUuids;	// 24 = 0x18
    NSString *_playlistUuid;	// 32 = 0x20
    id <MTPlaylistSelectPodcastListViewControllerSaveDelegate> _saveDelegate;	// 40 = 0x28
}

@property(nonatomic) __weak id <MTPlaylistSelectPodcastListViewControllerSaveDelegate> saveDelegate; // @synthesize saveDelegate=_saveDelegate;
@property(retain, nonatomic) NSString *playlistUuid; // @synthesize playlistUuid=_playlistUuid;
@property(nonatomic) _Bool allPodcastsSelected; // @synthesize allPodcastsSelected=_allPodcastsSelected;
@property(retain, nonatomic) NSMutableSet *podcastUuids; // @synthesize podcastUuids=_podcastUuids;
@property(retain, nonatomic) NSString *playlistName; // @synthesize playlistName=_playlistName;
- (void).cxx_destruct;	// IMP=0x000000010005ac84
- (void)main_tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x000000010005aa78
- (_Bool)main_tableView:(id)arg1 canFocusRowAtIndexPath:(id)arg2;	// IMP=0x000000010005aa58
- (double)main_tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;	// IMP=0x000000010005aa4c
- (void)main_configureCell:(id)arg1 forRowAtIndexPath:(id)arg2;	// IMP=0x000000010005a8d8
- (id)main_tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x000000010005a87c
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;	// IMP=0x000000010005a874
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;	// IMP=0x000000010005a804
- (void)save;	// IMP=0x000000010005a600
- (_Bool)toggleUuid:(id)arg1;	// IMP=0x000000010005a4cc
- (void)toggleAllPodcastsSelected;	// IMP=0x000000010005a464
- (void)setupIncludeAllCell;	// IMP=0x000000010005a0bc
- (void)setupFRC;	// IMP=0x0000000100059edc
- (void)viewWillLayoutSubviews;	// IMP=0x0000000100059c24
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x0000000100059bd4
- (void)viewDidLoad;	// IMP=0x0000000100059ae4

@end

