//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class MTTVContentUnavailableView, NSString, UIImage;

@interface MTTVContentUnavailableViewController : UIViewController
{
    UIImage *_image;	// 8 = 0x8
    NSString *_primaryText;	// 16 = 0x10
    NSString *_secondaryText;	// 24 = 0x18
    NSString *_buttonTitle;	// 32 = 0x20
    MTTVContentUnavailableView *_emptyOverlay;	// 40 = 0x28
}

@property(retain, nonatomic) MTTVContentUnavailableView *emptyOverlay; // @synthesize emptyOverlay=_emptyOverlay;
@property(retain, nonatomic) NSString *buttonTitle; // @synthesize buttonTitle=_buttonTitle;
@property(retain, nonatomic) NSString *secondaryText; // @synthesize secondaryText=_secondaryText;
@property(retain, nonatomic) NSString *primaryText; // @synthesize primaryText=_primaryText;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
- (void).cxx_destruct;	// IMP=0x0000000100026730
- (void)buttonPressed:(id)arg1;	// IMP=0x0000000100026568
- (void)viewDidLayoutSubviews;	// IMP=0x00000001000261dc
- (void)viewDidLoad;	// IMP=0x0000000100026140

@end

