//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class MTPodcast, MTTVPodcastDetailsSectionControl, UILabel;

@interface MTTVPodcastHeaderView : UIView
{
    UILabel *_titleLabel;	// 8 = 0x8
    MTTVPodcastDetailsSectionControl *_sectionControl;	// 16 = 0x10
    MTPodcast *_podcast;	// 24 = 0x18
    id <MTTVPodcastHeaderViewDelegate> _delegate;	// 32 = 0x20
}

@property(nonatomic) __weak id <MTTVPodcastHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) MTPodcast *podcast; // @synthesize podcast=_podcast;
- (void).cxx_destruct;	// IMP=0x0000000100109ff0
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x0000000100109ee4
- (id)preferredFocusedView;	// IMP=0x0000000100109ed4
- (_Bool)canBecomeFocused;	// IMP=0x0000000100109e88
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x0000000100109d24
- (void)layoutSubviews;	// IMP=0x0000000100109aac
- (void)updateTextColors;	// IMP=0x00000001001098e0
- (void)sectionControlDidChange:(id)arg1;	// IMP=0x0000000100109874
@property(nonatomic) unsigned long long selectedTab; // @dynamic selectedTab;
- (void)configureSubviews;	// IMP=0x0000000100109584
- (id)initWithPodcast:(id)arg1 delegate:(id)arg2;	// IMP=0x00000001001094c8
- (id)init;	// IMP=0x00000001001094b4

@end

