//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTPredicateManifest.h"

@interface MTUnplayedManifest : MTPredicateManifest
{
}

+ (id)activityTypeSuffix;	// IMP=0x00000001000fd9dc
+ (id)createManifestForActivity:(id)arg1;	// IMP=0x00000001000fd960
- (id)initWithInitialEpisodeUuid:(id)arg1 newestToOldest:(_Bool)arg2;	// IMP=0x00000001000fd5c4
- (id)initWithInitialEpisodeUuid:(id)arg1;	// IMP=0x00000001000fd5b4

@end

