//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURLSessionTask.h"

@interface NSURLSessionTask (MTAdditions)
@property(nonatomic) _Bool useBackgroundFetch;
@property(nonatomic) _Bool userCanceledAuth;
@property(nonatomic, getter=isInteractive) _Bool interactive;
@end

