//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionView.h"

@interface UICollectionView (MTAdditions)
- (id)mt_dequeueReusableSupplementaryViewClass:(Class)arg1 supplementaryViewKind:(id)arg2 forIndexPath:(id)arg3;	// IMP=0x0000000100165f4c
- (id)mt_dequeueReusableCellClass:(Class)arg1 forIndexPath:(id)arg2;	// IMP=0x0000000100165ecc
- (void)mt_registerSupplementaryViewClass:(Class)arg1 forSupplementaryViewOfKind:(id)arg2;	// IMP=0x0000000100165e5c
- (void)mt_registerCellClass:(Class)arg1;	// IMP=0x0000000100165e04
- (id)sectionHeaderViewForItemAtIndexPath:(id)arg1;	// IMP=0x0000000100165da4
- (id)sectionHeaderViewForIndexPath:(id)arg1;	// IMP=0x0000000100165d60
- (id)sectionHeaderIndexPathForItemIndexPath:(id)arg1;	// IMP=0x0000000100165d00
@end

