//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UISplitViewController.h"

@class UIViewController;

@interface UISplitViewController (MTAdditions)
@property(readonly) UIViewController *mt_detailViewController;
@property(readonly) UIViewController *mt_masterViewController;
@end

