//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSPowerMonitorObserver.h"

@class NSString, SSDisplay;

@interface PREIdleSleepManager : NSObject <BSPowerMonitorObserver>
{
    _Bool _displayDim;	// 8 = 0x8
    _Bool _allowIdleTimerToBeReset;	// 9 = 0x9
    SSDisplay *_display;	// 16 = 0x10
}

+ (id)sharedController;	// IMP=0x0000000100004424
@property(retain, nonatomic) SSDisplay *display; // @synthesize display=_display;
@property(nonatomic) _Bool allowIdleTimerToBeReset; // @synthesize allowIdleTimerToBeReset=_allowIdleTimerToBeReset;
@property(nonatomic, getter=isDisplayDim) _Bool displayDim; // @synthesize displayDim=_displayDim;
- (void).cxx_destruct;	// IMP=0x000000010000536c
- (void)powerMonitorSystemDidWakeFromSleep:(id)arg1;	// IMP=0x00000001000052b0
- (void)powerMonitorSystemWillWakeFromSleep:(id)arg1;	// IMP=0x0000000100005258
- (void)powerMonitorSystemWillSleep:(id)arg1;	// IMP=0x0000000100005200
- (void)powerMonitorSystemSleepRequestAborted:(id)arg1;	// IMP=0x00000001000051a8
- (_Bool)powerMonitorSystemSleepRequested:(id)arg1;	// IMP=0x000000010000514c
- (void)_startAllowingIdleTimer;	// IMP=0x000000010000512c
- (void)_requestedUserEventNotificationOccurred;	// IMP=0x0000000100005128
- (void)_userEventPresenceTimerExpired;	// IMP=0x0000000100005124
- (void)_userEventOccurred;	// IMP=0x0000000100005114
- (void)_userEventsDidIdle;	// IMP=0x0000000100005108
- (void)resetIdleTimerAndUndim:(_Bool)arg1;	// IMP=0x0000000100004fbc
- (double)_nextLockTimeDuration;	// IMP=0x0000000100004f74
- (void)setPreventIdleSleep:(_Bool)arg1 forReason:(id)arg2;	// IMP=0x0000000100004efc
- (void)_preventIdleSleepForNumberOfSeconds:(float)arg1;	// IMP=0x0000000100004e10
- (void)_preventIdleSleep;	// IMP=0x0000000100004db8
- (void)_allowIdleSleep;	// IMP=0x0000000100004d60
- (void)dimDisplay;	// IMP=0x0000000100004bb8
- (void)undimDisplay;	// IMP=0x0000000100004b98
- (void)_undimDisplayForce;	// IMP=0x00000001000049b0
- (void)_setHIDUILockedState:(_Bool)arg1;	// IMP=0x0000000100004974
- (id)init;	// IMP=0x00000001000044a4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

