//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIAlertController.h"

@interface PREViewController : UIAlertController
{
}

+ (id)viewController;	// IMP=0x0000000100006900
- (void)viewDidLoad;	// IMP=0x0000000100007008

@end

