//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DADeviceObserver.h"

@class NSString;

@interface DADeviceObserverLocal : NSObject <DADeviceObserver>
{
}

- (void)endDiscoveringDevicesWithIdentifier:(struct NSObject *)arg1;	// IMP=0x0000000100007638
- (struct NSObject *)beginDiscoveringDevicesWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100007480
- (void)discoverAllDevicesWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100007460

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

