//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JSExport.h"

@class NSString;

@protocol TVHJSMediaServerDiscoveryConfiguration <JSExport>
@property(readonly, copy, nonatomic) NSString *homeSharingAccountName;
@property(readonly, copy, nonatomic) NSString *homeSharingGroupIdentifier;
@property(readonly, nonatomic) _Bool discoveringDAAPServers;
@property(readonly, nonatomic) _Bool discoveringHomeShareServers;
@property(readonly, nonatomic) _Bool discoveringMediaServers;
@property(readonly, copy, nonatomic) NSString *discoveryMode;
@end

