//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JSExport.h"

@class NSArray, NSString, TVHJSMediaEntityFetchRequest, TVHJSMediaServer;

@protocol TVHJSMediaEntityFetchController <JSExport>
+ (id)create:(TVHJSMediaServer *)arg1:(TVHJSMediaEntityFetchRequest *)arg2;
@property(copy, nonatomic) NSArray *groupingKeyPaths;
@property(nonatomic) _Bool calculatesRecentlyAdded;
@property(copy, nonatomic) NSString *logNameSuffix;
@property(copy, nonatomic) NSString *identifier;
@property(readonly, copy, nonatomic) NSArray *mediaEntities;
- (void)simulateContentsChangeWithFetchFromServer:(_Bool)arg1;
- (void)resume;
- (void)pause;
- (void)stop;
- (void)start;
@end

