//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IKJSObject.h"

#import "TVHJSVideoCredits.h"

@class NSArray, TVHKVideoCredits;

@interface TVHJSVideoCredits : IKJSObject <TVHJSVideoCredits>
{
    TVHKVideoCredits *_videoCredits;	// 8 = 0x8
}

@property(retain, nonatomic) TVHKVideoCredits *videoCredits; // @synthesize videoCredits=_videoCredits;
- (void).cxx_destruct;	// IMP=0x0000000100025fd0
@property(readonly, nonatomic) _Bool hasCredits;
@property(readonly, copy, nonatomic) NSArray *screenwriters;
@property(readonly, copy, nonatomic) NSArray *producers;
@property(readonly, copy, nonatomic) NSArray *directors;
@property(readonly, copy, nonatomic) NSArray *actors;
- (id)initWithVideoCredits:(id)arg1 appContext:(id)arg2;	// IMP=0x0000000100025c88
- (id)initWithAppContext:(id)arg1;	// IMP=0x0000000100025c00
- (id)init;	// IMP=0x0000000100025b78

@end

