//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IKJSObject.h"

#import "TVHJSImageColorAnalyzer.h"

@class NSCache, NSOperationQueue;

@interface TVHJSImageColorAnalyzer : IKJSObject <TVHJSImageColorAnalyzer>
{
    NSCache *_imageColorsCache;	// 8 = 0x8
    NSOperationQueue *_privateQueue;	// 16 = 0x10
}

@property(retain, nonatomic) NSOperationQueue *privateQueue; // @synthesize privateQueue=_privateQueue;
@property(retain, nonatomic) NSCache *imageColorsCache; // @synthesize imageColorsCache=_imageColorsCache;
- (void).cxx_destruct;	// IMP=0x000000010000a8d0
- (void)_callCallback:(id)arg1 imageColors:(id)arg2 error:(id)arg3;	// IMP=0x000000010000a65c
- (void)_cacheAnyalzedImageColors:(id)arg1 forMediaEntity:(id)arg2;	// IMP=0x000000010000a578
- (id)_cachedAnyalzedImageColorsForMediaEntity:(id)arg1;	// IMP=0x000000010000a49c
- (id)_imageColorsForMediaEntity:(id)arg1 analyzeCachedImageOnly:(_Bool)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0000000100009f98
- (id)imageColorsForCachedMediaEntityDefaultImage:(id)arg1;	// IMP=0x0000000100009c84
- (id)imageColorsForMediaEntityDefaultImage:(id)arg1:(id)arg2;	// IMP=0x00000001000098e4
- (void)dealloc;	// IMP=0x0000000100009878
- (id)initWithAppContext:(id)arg1;	// IMP=0x00000001000097a4

@end

