//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVHMediaEntityServerOperation.h"

@class NSArray, TVHJSCollectionComparator, TVHKMediaEntityFetchRequest;

@interface TVHMediaEntitiesFetchOperation : TVHMediaEntityServerOperation
{
    NSArray *_currentMediaEntities;	// 24 = 0x18
    NSArray *_mediaEntities;	// 32 = 0x20
    NSArray *_changes;	// 40 = 0x28
    TVHKMediaEntityFetchRequest *_fetchRequest;	// 48 = 0x30
    TVHJSCollectionComparator *_comparator;	// 56 = 0x38
}

@property(retain, nonatomic) TVHJSCollectionComparator *comparator; // @synthesize comparator=_comparator;
@property(copy, nonatomic) TVHKMediaEntityFetchRequest *fetchRequest; // @synthesize fetchRequest=_fetchRequest;
@property(copy, nonatomic) NSArray *changes; // @synthesize changes=_changes;
@property(copy, nonatomic) NSArray *mediaEntities; // @synthesize mediaEntities=_mediaEntities;
@property(copy, nonatomic) NSArray *currentMediaEntities; // @synthesize currentMediaEntities=_currentMediaEntities;
- (void).cxx_destruct;	// IMP=0x0000000100028ae4
- (void)_handleFetchResponse:(id)arg1;	// IMP=0x0000000100028958
- (void)executionDidBegin;	// IMP=0x00000001000286a8
- (id)initWithMediaEntityServer:(id)arg1 request:(id)arg2 appContext:(id)arg3;	// IMP=0x00000001000285a4

@end

