//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TVHMediaItemListViewCell.h"

@class UILabel;

@interface TVHPlaylistItemListViewCell : TVHMediaItemListViewCell
{
    UILabel *_artistTitleLabel;	// 8 = 0x8
}

@property(retain, nonatomic) UILabel *artistTitleLabel; // @synthesize artistTitleLabel=_artistTitleLabel;
- (void).cxx_destruct;	// IMP=0x00000001000297c8
- (void)layoutSubviews;	// IMP=0x0000000100029450
- (void)_updateColors;	// IMP=0x0000000100029280
- (void)updateWithViewElement:(id)arg1;	// IMP=0x0000000100028b60

@end

