//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TVHThemeManager : NSObject
{
}

+ (id)_100PercentWhiteColor;	// IMP=0x0000000100028370
+ (id)_60PercentWhiteColor;	// IMP=0x00000001000282e8
+ (id)_50PercentWhiteColor;	// IMP=0x0000000100028264
+ (id)_30PercentWhiteColor;	// IMP=0x00000001000281dc
+ (id)_100PercentBlackColor;	// IMP=0x0000000100028160
+ (id)_60PercentBlackColor;	// IMP=0x00000001000280d8
+ (id)_40PercentBlackColor;	// IMP=0x0000000100028050
+ (id)_darkModeNowPlayingBarsColor;	// IMP=0x0000000100028044
+ (id)_lightModeNowPlayingBarsColor;	// IMP=0x0000000100028038
+ (id)_darkModeListViewCellFocusedTextColor;	// IMP=0x000000010002802c
+ (id)_lightModeListViewCellFocusedTextColor;	// IMP=0x0000000100028020
+ (id)_darkModeListViewCellDurationFocusedTextColor;	// IMP=0x0000000100028014
+ (id)_lightModeListViewCellDurationFocusedTextColor;	// IMP=0x0000000100028008
+ (id)_darkModeListViewCellDurationTextColor;	// IMP=0x0000000100027ffc
+ (id)_lightModeListViewCellDurationTextColor;	// IMP=0x0000000100027ff0
+ (id)_darkModeListViewCellSubtitleTextColor;	// IMP=0x0000000100027fe4
+ (id)_lightModeListViewCellSubtitleTextColor;	// IMP=0x0000000100027fd8
+ (id)_darkModeListViewCellTitleTextColor;	// IMP=0x0000000100027fcc
+ (id)_lightModeListViewCellTitleTextColor;	// IMP=0x0000000100027fc0
+ (id)_darkModeMusicSongsListViewCellTitleTextColor;	// IMP=0x0000000100027fb4
+ (id)_lightModeMusicSongsListViewCellTitleTextColor;	// IMP=0x0000000100027fa8
+ (id)_listViewCellFocusedTextColorWithUserInterfaceStyle:(long long)arg1;	// IMP=0x0000000100027f5c
+ (id)nowPlayingBarsColorWithUserInterfaceStyle:(long long)arg1 andFocus:(_Bool)arg2 filterType:(id *)arg3;	// IMP=0x0000000100027ea0
+ (id)listViewCellDurationTextColorWithUserInterfaceStyle:(long long)arg1 andFocus:(_Bool)arg2;	// IMP=0x0000000100027e24
+ (id)listViewCellSubtitleTextColorWithUserInterfaceStyle:(long long)arg1 andFocus:(_Bool)arg2;	// IMP=0x0000000100027dc0
+ (id)listViewCellTitleTextColorWithUserInterfaceStyle:(long long)arg1 andFocus:(_Bool)arg2;	// IMP=0x0000000100027d5c
+ (id)musicSongsListViewCellTitleTextColorWithUserInterfaceStyle:(long long)arg1 andFocus:(_Bool)arg2;	// IMP=0x0000000100027cf8
+ (id)caption2Font;	// IMP=0x0000000100027c70
+ (id)caption1Font;	// IMP=0x0000000100027be8
+ (id)footnoteFont;	// IMP=0x0000000100027b60
+ (id)subheadFont;	// IMP=0x0000000100027ad8
+ (id)bodyFont;	// IMP=0x0000000100027a50
+ (id)calloutFont;	// IMP=0x00000001000279c8
+ (id)subtitle3Font;	// IMP=0x0000000100027940
+ (id)subtitle2Font;	// IMP=0x00000001000278b8
+ (id)subtitle1Font;	// IMP=0x0000000100027830
+ (id)headline2Font;	// IMP=0x00000001000277a8
+ (id)headlineFont;	// IMP=0x0000000100027720
+ (id)title4Font;	// IMP=0x0000000100027698
+ (id)title3Font;	// IMP=0x0000000100027610
+ (id)title2Font;	// IMP=0x0000000100027588
+ (id)title1Font;	// IMP=0x0000000100027500

@end

