//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<TVPMediaItem>, TVPMPPlaybackQueueManager;

@protocol TVPMPPlaybackQueueManagerDelegate <NSObject>

@optional
- (id <MPNowPlayingContentItemLyricsDataSource>)manager:(TVPMPPlaybackQueueManager *)arg1 lyricsDataSourceForMediaItem:(NSObject<TVPMediaItem> *)arg2;
- (long long)manager:(TVPMPPlaybackQueueManager *)arg1 editingStyleFlagsForMediaItem:(NSObject<TVPMediaItem> *)arg2;
@end

